GENERAL TASK:
Create a NEW Laravel seeder for grammar questions on the topic:
{{ $topicName }}.

If the theory URL ({{ $theoryUrl }}) is not "none", you may use it only as a reference for the grammar rules,
but you must create completely original questions.

You must:
- Inspect and follow the structure from these base seeders:
@foreach ($baseSeederClasses as $class)
- {{ $class }}
@endforeach
- Reuse the same structure, methods and logic that the base seeders use to build and insert questions.
- Follow the same array keys / fields / models that the base seeders rely on.

FILE & NAMESPACE:
- Place the new seeder class in {{ $newSeederNamespacePath }}.
@if ($newSeederClassName)
- Use {{ $newSeederClassName }} as the class name.
@endif
- Follow the same namespace and base class conventions as other seeders in this project.

LANGUAGE:
- Question text and all answer options must be in ENGLISH.
- Fields chatgpt_explanations and question_hints must be generated in {{ $hintsLanguage }}.

QUESTION QUANTITY & LEVELS:
- Use CEFR levels: {!! json_encode($levels, JSON_UNESCAPED_UNICODE) !!}.
- For EACH level generate EXACTLY {{ $questionsPerLevel }} UNIQUE questions.
- Total number of questions = {{ count($levels) }} × {{ $questionsPerLevel }} = {{ $totalQuestions }}.
- Each question must have a field that stores its level (for example: "level" => "B1").

GENERAL REQUIREMENTS FOR QUESTIONS:
- Topic: strictly {{ $topicName }} (do not mix other grammar topics).
- Use your own original questions, DO NOT copy from existing seeders or external sources.
- If this grammar topic allows it:
  - Include different sentence forms: affirmative, negative, interrogative.
  - Include a variety of time references: present, past, future.
- Avoid questions that are too similar in meaning.
- NO duplicated questions (text or structure).

FIELDS PER QUESTION
(ADAPT FIELD NAMES TO MATCH THE BASE SEEDERS, BUT KEEP THIS INFORMATION):

For each question, generate:
- text / question text with a gap for the missing part (e.g. "If I ____ more time, I would travel the world.").
- possible answers (options).
- correct answer.
- level (one of LEVELS_TO_USE).
- tags (an array of detailed tags).
- verb_hint
- chatgpt_explanations
- question_hints
- source
- questions.flag
- questions.type

VERB_HINT RULES:
- verb_hint must be in a base form of the verb or a neutral hint expression.
  - Example: if the correct answer is "had gone", verb_hint should be "go", NOT "had gone".
- verb_hint MUST NOT contain the exact correct answer.
- If a pure base form would immediately reveal the answer or is not appropriate:
  - use a short leading hint instead, such as:
    - "Use a past perfect form"
    - "Use would + base verb"
    - "Use would have + V3"

EXPLANATIONS & HINTS (chatgpt_explanations, question_hints):
- Both chatgpt_explanations and question_hints MUST be written in {{ $hintsLanguage }}.
- For each question:

  chatgpt_explanations:
  - Extended explanation in {{ $hintsLanguage }} that:
    - clearly explains the grammar rule or formula used in this question,
      e.g. patterns like "If + past perfect, would have + V3", "adjective + -er than", "the + superlative".
    - includes 1–2 extra example sentences (in English) that illustrate the rule.
    - DOES NOT contain the exact correct answer phrase from this question.

  question_hints:
  - Shorter hints in {{ $hintsLanguage }} that:
    - remind the student about the pattern, formula or typical structure.
    - may give a similar example or partial pattern.
    - AGAIN: must NOT include the exact correct answer phrase.

LEVEL EVALUATION:
- Assign a CEFR level (from LEVELS_TO_USE) to each question based on:
  - structure complexity
  - vocabulary
  - length
  - type of grammar pattern
- Store this value in a dedicated field (e.g. "level" => "B1") in each question.

TAGS:
- For every question generate a detailed "tags" field (array of strings).
- Use tags to describe:
  - main grammar area (e.g. "conditionals", "comparison", "present perfect", "passive voice").
  - sub-type (e.g. "mixed conditional", "second conditional", "superlative adjectives").
  - tense/aspect if relevant (e.g. "past perfect", "present simple", "would have + V3").
  - sentence form (e.g. "affirmative", "negative", "interrogative").
  - CEFR level (e.g. "B1").
- Example:
  - ["grammar", "conditionals", "mixed conditional", "past perfect", "would have + V3", "B2", "negative"]

SOURCE, FLAG, TYPE (FIXED REQUIREMENTS):
- Add a field like "source" indicating that these questions were generated by AI for this topic.
  - Example: "AI generated: {{ $topicName }} (SET 1)".
- All questions must have:
  - questions.flag = 2
  - questions.type = 0
- Use the exact keys/columns and structure that the base seeders use when inserting questions.

CODE STYLE:
- Follow the exact collection/array structure of the base seeders so that the new seeder can be executed without manual changes.
- Implement a run() method that inserts ALL generated questions (all levels, all quantities).
- Do not add any external dependencies. Use only standard Laravel seeder patterns already used in the base seeders.
