@extends('layouts.engram')

@section('title', $page->title)

@section('content')
    @php($blocks = $page->textBlocks ?? collect())
    @php($breadcrumbs = $breadcrumbs ?? [])
    @php($mobileSelectedCategory = $selectedCategory ?? null)
    @php($mobileCategoryPages = ($categoryPages ?? collect()))
    @php($hasCategoryPages = $mobileSelectedCategory && $mobileCategoryPages->isNotEmpty())
    @php($routePrefix = $routePrefix ?? 'theory')

    <div class="space-y-6 lg:space-y-0 lg:grid lg:grid-cols-[260px_1fr] lg:items-start lg:gap-8">
        @include('engram.theory.partials.sidebar-navigation-mobile', [
            'categories' => $categories,
            'selectedCategory' => $mobileSelectedCategory,
            'categoryPages' => $mobileCategoryPages,
            'currentPage' => $page,
            'routePrefix' => $routePrefix,
        ])

        <div class="hidden lg:block">
            @include('engram.pages.partials.sidebar', [
                'categories' => $categories,
                'selectedCategory' => $selectedCategory ?? null,
                'categoryPages' => $categoryPages ?? collect(),
                'currentPage' => $page,
                'showCategoryPagesNav' => true,
                'class' => 'lg:sticky lg:top-24',
                'routePrefix' => $routePrefix,
            ])
        </div>

        <article class="max-w-none space-y-4 lg:col-start-2">
            @foreach($blocks as $block)
                @includeIf('engram.theory.blocks.' . $block->type, [
                    'page' => $page,
                    'block' => $block,
                    'data' => json_decode($block->body ?? '[]', true),
                    'breadcrumbs' => $breadcrumbs,
                ])
            @endforeach

            @if(isset($autoGeneratedTests) && $autoGeneratedTests->isNotEmpty())
                <div class="rounded-2xl border border-border/80 bg-card shadow-soft p-6" x-data="{ expanded: true }">
                    <div class="flex items-center justify-between mb-4">
                        <h2 class="text-lg font-semibold">{{ __('public.common.tests_on_topic') }}</h2>
                        <button 
                            @click="expanded = !expanded"
                            class="text-sm text-muted-foreground hover:text-foreground transition flex items-center gap-1"
                            :aria-expanded="expanded"
                        >
                            <span x-text="expanded ? '{{ __('public.common.collapse') }}' : '{{ __('public.common.expand') }}'"></span>
                            <svg 
                                class="w-4 h-4 transition-transform" 
                                :class="{ 'rotate-180': !expanded }"
                                fill="none" 
                                stroke="currentColor" 
                                viewBox="0 0 24 24"
                            >
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                            </svg>
                        </button>
                    </div>

                    <div x-show="expanded" x-collapse>
                        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                            @foreach($autoGeneratedTests as $test)
                                <x-auto-generated-test-card :test="$test" />
                            @endforeach
                        </div>
                    </div>
                </div>
            @endif

            @if($page->tags->isNotEmpty())
                <div class="rounded-2xl border border-border/80 bg-card shadow-soft p-6" x-data="{ expanded: false }">
                    <div class="flex items-center justify-between mb-4">
                        <h2 class="text-lg font-semibold">{{ __('public.common.page_tags') }}</h2>
                        <button 
                            @click="expanded = !expanded"
                            class="text-sm text-muted-foreground hover:text-foreground transition flex items-center gap-1"
                            :aria-expanded="expanded"
                        >
                            <span x-text="expanded ? '{{ __('public.common.collapse') }}' : '{{ __('public.common.expand') }}'"></span>
                            <svg 
                                class="w-4 h-4 transition-transform" 
                                :class="{ 'rotate-180': !expanded }"
                                fill="none" 
                                stroke="currentColor" 
                                viewBox="0 0 24 24"
                            >
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                            </svg>
                        </button>
                    </div>

                    <div x-show="expanded" x-collapse>
                        <div class="flex flex-wrap gap-1">
                            @foreach($page->tags as $tag)
                                <span class="inline-block bg-secondary text-secondary-foreground font-medium text-xs px-2 py-0.5 rounded">{{ $tag->name }}</span>
                            @endforeach
                        </div>
                    </div>
                </div>
            @endif

            @if(isset($relatedTests) && $relatedTests->isNotEmpty())
                <div class="rounded-2xl border border-border/80 bg-card shadow-soft p-6" x-data="{ expanded: false }">
                    <div class="flex items-center justify-between mb-4">
                        <h2 class="text-lg font-semibold">{{ __('public.common.related_tests') }}</h2>
                        <button 
                            @click="expanded = !expanded"
                            class="text-sm text-muted-foreground hover:text-foreground transition flex items-center gap-1"
                            :aria-expanded="expanded"
                        >
                            <span x-text="expanded ? '{{ __('public.common.collapse') }}' : '{{ __('public.common.expand') }}'"></span>
                            <svg 
                                class="w-4 h-4 transition-transform" 
                                :class="{ 'rotate-180': !expanded }"
                                fill="none" 
                                stroke="currentColor" 
                                viewBox="0 0 24 24"
                            >
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                            </svg>
                        </button>
                    </div>

                    <div x-show="expanded" x-collapse>
                        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                            @foreach($relatedTests as $test)
                                <x-related-test-card :test="$test" />
                            @endforeach
                        </div>
                    </div>
                </div>
            @endif
        </article>
    </div>
@endsection
