<?php

namespace App\Services;

use App\Models\Question;
use App\Models\SavedGrammarTest;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;

class AutoGeneratedTestService
{
    /**
     * Level pairs for generating tests
     */
    private const LEVEL_PAIRS = [
        ['A1', 'A2'],
        ['A2', 'B1'],
        ['B1', 'B2'],
        ['B2', 'C1'],
        ['C1', 'C2'],
    ];

    private const QUESTIONS_PER_TEST = 15;

    /**
     * Generate auto tests for given tags
     *
     * @param Collection $tags Collection of Tag models
     * @param string $contextPrefix Prefix for test names (e.g., page title or category title)
     * @return Collection Collection of SavedGrammarTest models
     */
    public function generateTests(Collection $tags, string $contextPrefix = ''): Collection
    {
        if ($tags->isEmpty()) {
            return collect();
        }

        $tagNames = $tags->pluck('name')->toArray();
        $tests = collect();

        foreach (self::LEVEL_PAIRS as $levelPair) {
            $test = $this->getOrCreateTestForLevelPair($levelPair, $tagNames, $contextPrefix);
            
            if ($test) {
                $tests->push($test);
            }
        }

        return $tests;
    }

    /**
     * Get or create a SavedGrammarTest for a level pair
     *
     * @param array $levelPair Array with two levels [from, to]
     * @param array $tagNames Array of tag names to filter by
     * @param string $contextPrefix Prefix for test name
     * @return SavedGrammarTest|null Test model or null if not enough questions
     */
    private function getOrCreateTestForLevelPair(array $levelPair, array $tagNames, string $contextPrefix): ?SavedGrammarTest
    {
        [$levelFrom, $levelTo] = $levelPair;

        // Build query for questions with flag=2, matching tags, and levels
        $query = Question::query()
            ->where('flag', 2)
            ->whereIn('level', [$levelFrom, $levelTo])
            ->whereHas('tags', fn($q) => $q->whereIn('name', $tagNames));

        // Get total available questions
        $totalQuestions = $query->count();

        if ($totalQuestions < self::QUESTIONS_PER_TEST) {
            // Not enough questions for this level pair, return null
            return null;
        }

        // Create slug based on context and level pair
        $baseSlug = $this->createSlug($contextPrefix, $levelFrom, $levelTo, $tagNames);
        
        // Check if test already exists
        $test = SavedGrammarTest::where('slug', $baseSlug)->first();
        
        if (!$test) {
            // Create new test with filter-based mode
            $filters = $this->buildFilters($levelFrom, $levelTo, $tagNames);
            $filters['__meta'] = ['mode' => 'filters'];
            
            $testName = $this->createTestName($contextPrefix, $levelFrom, $levelTo);
            
            $test = SavedGrammarTest::create([
                'uuid' => (string) Str::uuid(),
                'name' => $testName,
                'slug' => $baseSlug,
                'filters' => $filters,
            ]);
        }
        
        return $test;
    }

    /**
     * Create a slug for the test
     *
     * @param string $contextPrefix Prefix for the slug
     * @param string $levelFrom Starting level
     * @param string $levelTo Ending level
     * @param array $tagNames Tag names
     * @return string Unique slug
     */
    private function createSlug(string $contextPrefix, string $levelFrom, string $levelTo, array $tagNames): string
    {
        // Create a deterministic slug based on context and filters
        $parts = array_filter([
            $contextPrefix,
            'auto',
            strtolower($levelFrom),
            strtolower($levelTo),
        ]);
        
        // Add a hash of tags to make it unique per tag combination
        $sortedTags = $tagNames;
        sort($sortedTags);
        $tagHash = substr(md5(implode(',', $sortedTags)), 0, 6);
        $parts[] = $tagHash;
        
        return Str::slug(implode('-', $parts));
    }

    /**
     * Create a test name
     *
     * @param string $contextPrefix Prefix for the name
     * @param string $levelFrom Starting level
     * @param string $levelTo Ending level
     * @return string Test name
     */
    private function createTestName(string $contextPrefix, string $levelFrom, string $levelTo): string
    {
        $prefix = $contextPrefix ? "{$contextPrefix}: " : '';
        return "{$prefix}Тест {$levelFrom}-{$levelTo}";
    }

    /**
     * Build filters for a generated test
     *
     * @param string $levelFrom Starting level
     * @param string $levelTo Ending level
     * @param array $tagNames Tag names for filtering
     * @return array Filters array
     */
    private function buildFilters(string $levelFrom, string $levelTo, array $tagNames): array
    {
        return [
            'only_ai_v2' => true,
            'tags' => $tagNames,
            'levels' => [$levelFrom, $levelTo],
            'num_questions' => self::QUESTIONS_PER_TEST,
            'randomize_filtered' => true,
        ];
    }
}
