<?php

namespace App\Services;

use App\Models\Question;
use Illuminate\Support\Collection;

class AutoGeneratedTestService
{
    /**
     * Level pairs for generating tests
     */
    private const LEVEL_PAIRS = [
        ['A1', 'A2'],
        ['A2', 'B1'],
        ['B1', 'B2'],
        ['B2', 'C1'],
        ['C1', 'C2'],
    ];

    private const QUESTIONS_PER_TEST = 15;

    /**
     * Generate auto tests for given tags
     *
     * @param Collection $tags Collection of Tag models
     * @return Collection Collection of test data
     */
    public function generateTests(Collection $tags): Collection
    {
        if ($tags->isEmpty()) {
            return collect();
        }

        $tagNames = $tags->pluck('name')->toArray();
        $tests = collect();

        foreach (self::LEVEL_PAIRS as $levelPair) {
            $testData = $this->generateTestForLevelPair($levelPair, $tagNames);
            
            if ($testData) {
                $tests->push($testData);
            }
        }

        return $tests;
    }

    /**
     * Generate a single test for a level pair
     *
     * @param array $levelPair Array with two levels [from, to]
     * @param array $tagNames Array of tag names to filter by
     * @return array|null Test data or null if not enough questions
     */
    private function generateTestForLevelPair(array $levelPair, array $tagNames): ?array
    {
        [$levelFrom, $levelTo] = $levelPair;

        // Build query for questions with flag=2, matching tags, and levels
        $query = Question::query()
            ->where('flag', 2)
            ->whereIn('level', [$levelFrom, $levelTo])
            ->whereHas('tags', fn($q) => $q->whereIn('name', $tagNames));

        // Get total available questions
        $totalQuestions = $query->count();

        if ($totalQuestions < self::QUESTIONS_PER_TEST) {
            // Not enough questions for this level pair, return null
            return null;
        }

        // Get random questions, shuffled
        $questions = $query
            ->inRandomOrder()
            ->limit(self::QUESTIONS_PER_TEST)
            ->get();

        return [
            'level_from' => $levelFrom,
            'level_to' => $levelTo,
            'level_label' => "{$levelFrom}-{$levelTo}",
            'questions_count' => $questions->count(),
            'total_available' => $totalQuestions,
            'question_uuids' => $questions->pluck('uuid')->toArray(),
        ];
    }

    /**
     * Build filters for a generated test
     *
     * @param string $levelFrom Starting level
     * @param string $levelTo Ending level
     * @param array $tagNames Tag names for filtering
     * @return array Filters array
     */
    public function buildFilters(string $levelFrom, string $levelTo, array $tagNames): array
    {
        return [
            'only_ai_v2' => true,
            'tags' => $tagNames,
            'levels' => [$levelFrom, $levelTo],
            'num_questions' => self::QUESTIONS_PER_TEST,
            'randomize_filtered' => true,
        ];
    }
}
