<?php

namespace App\Services;

use App\Models\Question;
use Illuminate\Support\Collection;

class AutoGeneratedTestService
{
    /**
     * Level pairs for generating tests
     */
    private const LEVEL_PAIRS = [
        ['A1', 'A2'],
        ['A2', 'B1'],
        ['B1', 'B2'],
        ['B2', 'C1'],
        ['C1', 'C2'],
    ];

    private const QUESTIONS_PER_TEST = 15;

    /**
     * Generate virtual tests for given tags without saving to the database.
     *
     * Tests are generated dynamically based on tag filters and displayed
     * without being persisted. When a user clicks on a test, the questions
     * are loaded based on the filters.
     *
     * @param Collection $tags Collection of Tag models
     * @param string $contextPrefix Prefix for test names (e.g., page title or category title)
     * @return Collection Collection of VirtualSavedTest objects
     */
    public function generateTests(Collection $tags, string $contextPrefix = ''): Collection
    {
        if ($tags->isEmpty()) {
            return collect();
        }

        $tagNames = $tags->pluck('name')->toArray();
        $tests = collect();

        foreach (self::LEVEL_PAIRS as $levelPair) {
            $test = $this->createVirtualTestForLevelPair($levelPair, $tagNames, $contextPrefix);
            
            if ($test) {
                $tests->push($test);
            }
        }

        return $tests;
    }

    /**
     * Create a virtual test for a level pair without persisting to the database.
     *
     * @param array $levelPair Array with two levels [from, to]
     * @param array $tagNames Array of tag names to filter by
     * @param string $contextPrefix Prefix for test name
     * @return VirtualSavedTest|null Virtual test or null if not enough questions
     */
    private function createVirtualTestForLevelPair(array $levelPair, array $tagNames, string $contextPrefix): ?VirtualSavedTest
    {
        [$levelFrom, $levelTo] = $levelPair;

        // Build query for questions with flag=2, matching tags, and levels
        $totalQuestions = Question::query()
            ->where('flag', 2)
            ->whereIn('level', [$levelFrom, $levelTo])
            ->whereHas('tags', fn($q) => $q->whereIn('name', $tagNames))
            ->count();

        if ($totalQuestions < self::QUESTIONS_PER_TEST) {
            // Not enough questions for this level pair, return null
            return null;
        }

        // Create virtual test without persisting
        $test = VirtualSavedTest::forLevelPair(
            $levelPair,
            $tagNames,
            $contextPrefix,
            self::QUESTIONS_PER_TEST
        );
        
        $test->setTotalQuestionsAvailable($totalQuestions);
        
        return $test;
    }
}
