<?php

namespace App\Services;

use App\Models\Page;
use App\Models\PageCategory;
use App\Models\Question;
use App\Models\SavedGrammarTest;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

/**
 * Builds the "theory-driven" course on top of existing Page_V3 theory pages
 * and existing V3 / Sentence Builder SavedGrammarTest content.
 *
 * Pure read-side methods (`scan`, `enumeratePages`) are safe to call from
 * audit commands. `build()` mutates SavedGrammarTest rows.
 *
 * Generated by GLZ-PROMPT-0068-THEORY-DRIVEN-COURSE-MVP.
 */
class TheoryDrivenCourseBuilder
{
    public const COURSE_SLUG = 'theory-driven';
    public const COURSE_TITLE = 'Повний курс по теорії';
    public const COURSE_DESCRIPTION = 'Курс, що використовує існуючі сторінки теорії як програму та змішані тести з наявного контенту V3 / Sentence Builder.';
    public const LESSON_SLUG_PREFIX = 'course-td-';
    public const QUESTIONS_PER_LESSON = 15;
    public const GENERATED_BY = 'GLZ-PROMPT-0069-THEORY-DRIVEN-COURSE-STABILIZE';

    /**
     * Pedagogical topic priority. Each entry is a list of slug-substring patterns
     * matched against (category_path + category_slug + page_slug) lowercased.
     * Lessons get the priority of the first matching group; non-matching lessons
     * fall back to PHP_INT_MAX (sorted to the tail in scan-order).
     *
     * @var array<int,array{label:string,patterns:list<string>}>
     */
    private const TOPIC_PRIORITY = [
        ['label' => 'verb-to-be',          'patterns' => ['verb-to-be', 'to_be']],
        ['label' => 'articles',            'patterns' => ['articles', 'a-an-the', 'a-an', 'a_an', 'definite-article', 'indefinite-article']],
        ['label' => 'pronouns',            'patterns' => ['pronoun', 'subject-pronoun', 'object-pronoun', 'possessive-pronoun', 'reflexive-pronoun']],
        ['label' => 'demonstratives',      'patterns' => ['demonstrative', 'this-that', 'these-those']],
        ['label' => 'nouns-quantifiers',   'patterns' => ['plural-noun', 'plural_noun', 'noun-plural', 'countable', 'uncountable', 'quantif', 'some-any', 'much-many', 'a-lot-of', 'few-little']],
        ['label' => 'present-simple',      'patterns' => ['present-simple']],
        ['label' => 'present-continuous',  'patterns' => ['present-continuous', 'present-progressive']],
        ['label' => 'past-simple',         'patterns' => ['past-simple']],
        ['label' => 'past-continuous',     'patterns' => ['past-continuous', 'past-progressive']],
        ['label' => 'future-simple',       'patterns' => ['future-simple', 'future-will', 'going-to', 'be-going-to']],
        ['label' => 'modal-verbs',         'patterns' => ['modal-verb', 'modal_verbs', 'can-could', 'can-cannot', 'must', 'should', 'have-to', 'may-might']],
        ['label' => 'adjectives',          'patterns' => ['adjective', 'adverb', 'comparative', 'superlative']],
        ['label' => 'present-perfect',     'patterns' => ['present-perfect']],
        ['label' => 'passive-voice',       'patterns' => ['passive']],
        ['label' => 'conditionals',        'patterns' => ['conditional']],
        ['label' => 'reported-speech',     'patterns' => ['reported-speech', 'reported_speech']],
        ['label' => 'relative-clauses',    'patterns' => ['relative-clause', 'relative_clause']],
        ['label' => 'gerund-infinitive',   'patterns' => ['gerund', 'infinitive']],
    ];

    public function __construct(
        private TheoryPagePromptLinkedTestsService $linkedTests,
    ) {}

    /**
     * Returns ordered list of theory pages, depth-first by category tree.
     *
     * @return array<int,array{order:int,page:Page,category:?PageCategory,category_path:string,category_slug:?string}>
     */
    public function enumeratePages(): array
    {
        $allCategories = PageCategory::query()->orderBy('id')->get();
        $childrenByParent = $allCategories->groupBy(fn (PageCategory $c) => (int) ($c->parent_id ?? 0));
        $pagesByCategory = Page::query()
            ->orderBy('id')
            ->get()
            ->groupBy(fn (Page $p) => (int) $p->page_category_id);

        $ordered = [];
        $order = 0;

        $visit = function (PageCategory $category, array $pathSlugs) use (&$visit, &$ordered, &$order, $childrenByParent, $pagesByCategory): void {
            $newPath = array_merge($pathSlugs, [(string) $category->slug]);
            $pages = $pagesByCategory->get((int) $category->id, collect());

            foreach ($pages as $page) {
                if (trim((string) $page->slug) === '') {
                    continue;
                }

                $order++;
                $ordered[] = [
                    'order' => $order,
                    'page' => $page,
                    'category' => $category,
                    'category_path' => implode('/', array_filter($newPath)),
                    'category_slug' => (string) $category->slug,
                ];
            }

            $children = $childrenByParent->get((int) $category->id, collect())->sortBy('id');
            foreach ($children as $child) {
                $visit($child, $newPath);
            }
        };

        $roots = $childrenByParent->get(0, collect())->sortBy('id');
        foreach ($roots as $root) {
            $visit($root, []);
        }

        // Pages without a category — append at the end, deterministic by id.
        $orphanPages = $pagesByCategory->get(0, collect());
        foreach ($orphanPages as $page) {
            if (trim((string) $page->slug) === '') {
                continue;
            }

            $order++;
            $ordered[] = [
                'order' => $order,
                'page' => $page,
                'category' => null,
                'category_path' => '',
                'category_slug' => null,
            ];
        }

        return $ordered;
    }

    /**
     * For each enumerated page, gather candidate tests + question UUID pool.
     *
     * @return array<int,array<string,mixed>> rows ready for both audit & build.
     */
    public function scan(): array
    {
        $rows = [];

        foreach ($this->enumeratePages() as $entry) {
            /** @var Page $page */
            $page = $entry['page'];
            $candidates = $this->linkedTests->findForPage($page);
            $candidateTests = $candidates->filter(fn ($t) => $t instanceof SavedGrammarTest)->values();
            $poolStats = $this->collectQuestionPool($candidateTests);
            $selected = $this->selectQuestions($poolStats['compose_compatible'], self::QUESTIONS_PER_LESSON);
            [$priority, $priorityLabel] = $this->resolveTopicPriority(
                (string) $entry['category_slug'],
                $entry['category_path'],
                (string) $page->slug
            );

            $rows[] = [
                'order' => $entry['order'],
                'page' => $page,
                'category' => $entry['category'],
                'category_slug' => $entry['category_slug'],
                'category_path' => $entry['category_path'],
                'page_slug' => (string) $page->slug,
                'page_title' => trim((string) $page->title),
                'lesson_slug' => self::LESSON_SLUG_PREFIX . (string) $page->slug,
                'candidate_tests_count' => $candidateTests->count(),
                'candidate_test_slugs' => $candidateTests->pluck('slug')->filter()->values()->all(),
                'total_pool_questions' => $poolStats['total'],
                'compose_compatible_questions' => count($poolStats['compose_compatible']),
                'skipped_non_compose_questions' => $poolStats['total'] - count($poolStats['compose_compatible']),
                'question_pool_count' => count($poolStats['compose_compatible']),
                'selected_uuids' => $selected,
                'selected_questions' => count($selected),
                'will_create_lesson' => $selected !== [],
                'reason' => $selected === [] ? ($poolStats['total'] > 0 ? 'no_compose_compatible_questions' : 'no_questions_for_page') : 'ok',
                'topic_priority' => $priority,
                'topic_priority_label' => $priorityLabel,
            ];
        }

        return $rows;
    }

    /**
     * Returns [priority_int, priority_label]. Lower priority_int = earlier in course.
     * Non-matching pages get PHP_INT_MAX so they fall to the tail in stable order.
     *
     * @return array{0:int,1:?string}
     */
    protected function resolveTopicPriority(string $categorySlug, string $categoryPath, string $pageSlug): array
    {
        $haystack = strtolower(implode('|', array_filter([$categoryPath, $categorySlug, $pageSlug])));

        if ($haystack === '') {
            return [PHP_INT_MAX, null];
        }

        foreach (self::TOPIC_PRIORITY as $index => $group) {
            foreach ($group['patterns'] as $pattern) {
                if (str_contains($haystack, strtolower($pattern))) {
                    return [$index, $group['label']];
                }
            }
        }

        return [PHP_INT_MAX, null];
    }

    /**
     * Idempotently materialize SavedGrammarTest rows for the theory-driven course.
     *
     * @return array<string,mixed> summary
     */
    public function build(): array
    {
        $scanRows = $this->scan();
        $eligible = array_values(array_filter($scanRows, fn ($r) => $r['will_create_lesson'] === true));

        // Stable sort by (topic_priority asc, original scan order asc).
        usort($eligible, function (array $a, array $b): int {
            $cmp = ($a['topic_priority'] <=> $b['topic_priority']);
            if ($cmp !== 0) {
                return $cmp;
            }

            return ($a['order'] <=> $b['order']);
        });

        // Renumber lesson_order on eligible only and assign final lesson slugs.
        $lessonOrder = 0;
        foreach ($eligible as &$row) {
            $lessonOrder++;
            $row['lesson_order'] = $lessonOrder;
        }
        unset($row);

        $totalEligible = count($eligible);
        $createdSlugs = [];
        $updatedSlugs = [];

        foreach ($eligible as $idx => $row) {
            $previous = $idx > 0 ? $eligible[$idx - 1]['lesson_slug'] : null;
            $next = $idx < $totalEligible - 1 ? $eligible[$idx + 1]['lesson_slug'] : null;

            [$savedTest, $wasNew] = $this->upsertLessonTest($row, $previous, $next);

            if ($wasNew) {
                $createdSlugs[] = $savedTest->slug;
            } else {
                $updatedSlugs[] = $savedTest->slug;
            }
        }

        $blueprintPath = $this->writeBlueprintJson($eligible);

        // Clean up stale course-td-* lessons (e.g. pages that no longer yield
        // a compose-compatible pool after a stabilize pass). Restricted to
        // our own slug prefix — existing V3/Polyglot tests are untouched.
        $keepSlugs = array_column($eligible, 'lesson_slug');
        $orphans = SavedGrammarTest::query()
            ->where('slug', 'like', self::LESSON_SLUG_PREFIX . '%')
            ->when($keepSlugs !== [], fn ($q) => $q->whereNotIn('slug', $keepSlugs))
            ->get();
        $orphanCount = $orphans->count();
        foreach ($orphans as $orphan) {
            $orphan->questionLinks()->delete();
            $orphan->delete();
        }

        $totalPool = array_sum(array_column($scanRows, 'total_pool_questions'));
        $totalCompose = array_sum(array_column($scanRows, 'compose_compatible_questions'));
        $totalSelected = 0;
        $totalSkippedNonCompose = array_sum(array_column($scanRows, 'skipped_non_compose_questions'));
        foreach ($eligible as $row) {
            $totalSelected += (int) ($row['selected_questions'] ?? 0);
        }

        return [
            'total_pages' => count($scanRows),
            'pages_with_questions' => $totalEligible,
            'pages_skipped' => count($scanRows) - $totalEligible,
            'lessons_created' => count($createdSlugs),
            'lessons_updated' => count($updatedSlugs),
            'orphans_removed' => $orphanCount,
            'total_pool_questions' => $totalPool,
            'compose_compatible_questions' => $totalCompose,
            'selected_questions' => $totalSelected,
            'skipped_non_compose_questions' => $totalSkippedNonCompose,
            'blueprint_path' => $blueprintPath,
            'eligible' => $eligible,
            'scan_rows' => $scanRows,
        ];
    }

    /**
     * @return array{0: SavedGrammarTest, 1: bool} [model, wasNewlyCreated]
     */
    protected function upsertLessonTest(array $row, ?string $previousSlug, ?string $nextSlug): array
    {
        $slug = $row['lesson_slug'];
        $lessonOrder = (int) $row['lesson_order'];
        /** @var Page $page */
        $page = $row['page'];

        $existing = SavedGrammarTest::query()->where('slug', $slug)->first();
        $wasNew = $existing === null;
        $savedTest = $existing ?? new SavedGrammarTest;

        $title = sprintf('Урок %d: %s', $lessonOrder, $row['page_title'] !== '' ? $row['page_title'] : $row['page_slug']);

        $filters = [
            'mode' => 'compose_tokens',
            'question_type' => Question::TYPE_COMPOSE_TOKENS,
            'lesson_type' => 'theory-driven',
            'course_slug' => self::COURSE_SLUG,
            'lesson_order' => $lessonOrder,
            'previous_lesson_slug' => $previousSlug,
            'next_lesson_slug' => $nextSlug,
            'theory_page_slug' => $row['page_slug'],
            'theory_category_slug' => $row['category_slug'],
            'theory_category_path' => $row['category_path'] !== '' ? $row['category_path'] : null,
            'completion' => [
                'rolling_window' => 100,
                'min_rating' => 4.5,
            ],
            'interface_locale' => 'uk',
            'study_locale' => 'uk',
            'target_locale' => 'en',
            'topic' => $row['page_title'] !== '' ? $row['page_title'] : $row['page_slug'],
            'tags' => array_values(array_filter([
                'Theory-Driven',
                $row['category_slug'] !== null ? Str::headline($row['category_slug']) : null,
            ])),
            'prompt_generator' => [
                'source_type' => 'theory_page',
                'theory_page' => array_filter([
                    'slug' => $row['page_slug'],
                    'title' => $row['page_title'],
                    'category_slug_path' => $row['category_path'] !== '' ? $row['category_path'] : null,
                ], fn ($v) => $v !== null && $v !== ''),
            ],
            'num_questions' => count($row['selected_uuids']),
            'generated_from_existing_content' => true,
            'generated_by' => self::GENERATED_BY,
        ];

        $savedTest->fill([
            'uuid' => $savedTest->uuid ?: $this->deterministicUuid($slug),
            'slug' => $slug,
            'name' => $title,
            'description' => sprintf('Theory-driven урок №%d на основі сторінки теорії «%s».', $lessonOrder, $row['page_title']),
            'filters' => $filters,
        ]);
        $savedTest->save();

        // Replace question links for THIS course-td-* lesson only.
        $savedTest->questionLinks()->delete();
        $payloads = [];
        foreach ($row['selected_uuids'] as $position => $questionUuid) {
            $payloads[] = [
                'question_uuid' => $questionUuid,
                'position' => $position + 1,
            ];
        }

        if ($payloads !== []) {
            $savedTest->questionLinks()->createMany($payloads);
        }

        return [$savedTest, $wasNew];
    }

    /**
     * Aggregates question UUIDs from candidate tests, splitting into total
     * (existing in DB) and compose-compatible (type = TYPE_COMPOSE_TOKENS) sets.
     * Both lists are deterministically sorted by uuid.
     *
     * @param  Collection<int,SavedGrammarTest>  $candidateTests
     * @return array{total:int,all:list<string>,compose_compatible:list<string>}
     */
    protected function collectQuestionPool(Collection $candidateTests): array
    {
        $uuids = [];

        foreach ($candidateTests as $test) {
            /** @var SavedGrammarTest $test */
            $links = $test->relationLoaded('questionLinks')
                ? $test->questionLinks
                : $test->questionLinks()->get();

            foreach ($links as $link) {
                $uuid = trim((string) $link->question_uuid);
                if ($uuid === '') {
                    continue;
                }
                $uuids[$uuid] = true;
            }
        }

        if ($uuids === []) {
            return ['total' => 0, 'all' => [], 'compose_compatible' => []];
        }

        $existingRows = Question::query()
            ->whereIn('uuid', array_keys($uuids))
            ->get(['uuid', 'type']);

        $allUuids = $existingRows->pluck('uuid')->filter()->values()->all();
        $composeUuids = $existingRows
            ->filter(fn ($q) => (string) $q->type === Question::TYPE_COMPOSE_TOKENS)
            ->pluck('uuid')
            ->filter()
            ->values()
            ->all();

        sort($allUuids, SORT_STRING);
        sort($composeUuids, SORT_STRING);

        return [
            'total' => count($allUuids),
            'all' => $allUuids,
            'compose_compatible' => $composeUuids,
        ];
    }

    /**
     * @param  list<string>  $pool
     * @return list<string>
     */
    protected function selectQuestions(array $pool, int $limit): array
    {
        if ($pool === []) {
            return [];
        }

        return array_slice($pool, 0, $limit);
    }

    protected function deterministicUuid(string $slug): string
    {
        // Stable 36-char identifier derived from slug, conforms to schema length.
        $hash = sha1('theory-driven:' . $slug);

        return sprintf(
            '%s-%s-%s-%s-%s',
            substr($hash, 0, 8),
            substr($hash, 8, 4),
            substr($hash, 12, 4),
            substr($hash, 16, 4),
            substr($hash, 20, 12)
        );
    }

    /**
     * Mirror of the Polyglot blueprint format consumed by
     * PolyglotCourseBlueprintService::resolveBlueprintPath().
     *
     * @param  array<int,array<string,mixed>>  $eligible
     */
    protected function writeBlueprintJson(array $eligible): string
    {
        $path = database_path('seeders/V3/Polyglot/Course/' . self::COURSE_SLUG . '.json');
        File::ensureDirectoryExists(dirname($path));

        $totalEligible = count($eligible);
        $lessons = [];

        foreach ($eligible as $idx => $row) {
            $lessons[] = [
                'lesson_order' => (int) $row['lesson_order'],
                'slug' => $row['lesson_slug'],
                'title' => sprintf('Урок %d: %s', (int) $row['lesson_order'], $row['page_title']),
                'topic' => $row['page_title'],
                'level' => 'A1',
                'status' => 'implemented',
                'previous_lesson_slug' => $idx > 0 ? $eligible[$idx - 1]['lesson_slug'] : null,
                'next_lesson_slug' => $idx < $totalEligible - 1 ? $eligible[$idx + 1]['lesson_slug'] : null,
                'theory_category_slug' => $row['category_slug'],
                'theory_page_slug' => $row['page_slug'],
            ];
        }

        $blueprint = [
            'schema_version' => 1,
            'course_slug' => self::COURSE_SLUG,
            'course_title' => self::COURSE_TITLE,
            'description' => self::COURSE_DESCRIPTION,
            'total_planned_lessons' => $totalEligible,
            'defaults' => [
                'interface_locale' => 'uk',
                'study_locale' => 'uk',
                'target_locale' => 'en',
                'level' => 'A1',
                'mode' => 'compose_tokens',
            ],
            'generated_by' => self::GENERATED_BY,
            'lessons' => $lessons,
        ];

        File::put(
            $path,
            json_encode($blueprint, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . "\n"
        );

        return $path;
    }
}
