'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const {targets,semantic,equality,cloneText,practiceHelper}=require('../../tools/diagnostics/seo-m42-local.cjs');
function fixture(target){return new JSDOM('<!doctype html><html><head><title>'+target.registry.title+'</title><meta name="description" content="Accepted description"><link rel="canonical" href="'+target.registry.local_url+'"><meta name="robots" content="index,follow"></head><body><h1>'+target.registry.title+'</h1><main data-theory-main><section id="block-1" class="theory-native-block"><header class="theory-section-header"><span data-theory-ui>1.</span><h2>Accepted native heading</h2></header><div class="theory-section-body"><article class="theory-item"><p>Visible complete rule.</p><p lang="en">They had been waiting.</p><p lang="uk">Вони чекали.</p><div data-theory-native-extension><details><summary>Докладніше</summary><div id="point-1-detail" class="theory-point-fragment"><p>Meaningful independent detail.</p></div></details></div></article><table><thead><tr><th>English</th><th>Українська</th><th>Note</th></tr></thead><tbody><tr><td>A complete example.</td><td>Повний переклад.</td><td>Accepted note.</td></tr></tbody></table></div></section><section id="block-2" class="theory-native-block"><div x-data="theoryPracticeSet({controls:2})"><h3>Практика</h3><p>Original question.</p><p data-m38-self-check-answers>Original answer and explanation.</p></div></section></main></body></html>');}
test('Exact finite42 accepted identities, not M41 exemplars or fuzzy URL scope',()=>{assert.equal(targets.length,42);assert.equal(new Set(targets.map(t=>t.identity)).size,42);for(const target of targets){assert.equal('http://gramlyze.loc'+target.path,target.registry.local_url);assert.ok(target.registry.source);assert.ok(target.registry.definition);assert.ok(!['past-simple-vs-past-continuous','present-simple-vs-present-continuous','present-perfect-vs-past-simple'].includes(target.slug));}});
for(const target of targets){
 test(target.registry.current_package+' / '+target.slug+' — every independent semantic boundary survives presentation-only changes',()=>{
  const before=fixture(target),after=fixture(target);try{const expected=semantic(before.window.document);after.window.document.querySelector('.theory-item').classList.add('finite-native-colour');after.window.document.querySelector('.theory-section-body').style.padding='24px';assert.equal(equality(expected,semantic(after.window.document)),true);
   for(const [mutationIndex,mutate] of [
    d=>d.querySelector('[lang="en"]').remove(),d=>d.querySelector('[lang="uk"]').remove(),d=>d.querySelector('tbody td:last-child').remove(),
    d=>d.querySelector('article').append(d.querySelector('[lang="en"]').cloneNode(true)),d=>d.querySelector('article').prepend(d.querySelector('[lang="uk"]')),
    d=>d.querySelector('.theory-point-fragment').textContent='Changed detail',d=>d.querySelector('section').id='changed-anchor',
    d=>d.querySelector('[data-m38-self-check-answers]').textContent='Changed answer',d=>d.querySelector('[x-data]').setAttribute('x-data','theoryPracticeSet({controls:1})'),
    d=>d.querySelector('h2').textContent='Changed heading',d=>d.querySelector('meta[name="robots"]').setAttribute('content','noindex'),
   ].entries()){const changed=fixture(target);try{mutate(changed.window.document);assert.throws(()=>equality(expected,semantic(changed.window.document)),'Mutation '+mutationIndex+' (loss/order/key/control/anchor/SEO) must never become its own expected snapshot');}finally{changed.window.close();}}
  }finally{before.window.close();after.window.close();}
 });
}
test('Dynamic bank/JS/UI stripped, without removing the authored basic/detail/own key',()=>{const doc=fixture(targets[0]);try{const main=doc.window.document.querySelector('main');const widget=doc.window.document.createElement('div');widget.dataset.sentenceBuilder='';widget.innerHTML='<p>Random sampled linked question.</p>';main.append(widget);assert.ok(!cloneText(main).includes('Random sampled'));assert.ok(cloneText(main).includes('Original answer and explanation.'));assert.ok(cloneText(main).includes('Meaningful independent detail.'));assert.ok(!cloneText(main,{details:false}).includes('Meaningful independent detail.'));}finally{doc.window.close();}});
test('Authored practice adapters do not rely on unexported historical helper internals',()=>{for(const group of['M39','M40','M41']){const helper=practiceHelper({group});for(const name of['caseLocator','field','option','tokenProof','keyboardProof','verifyCase','fillCorrect','resetCase','checkedState'])assert.equal(typeof helper[name],'function',group+' '+name);}});
