<?php

namespace Tests\Feature;

use App\Models\Page;
use App\Models\PageCategory;
use App\Models\Question;
use App\Services\AutoGeneratedTestService;
use App\Services\SavedTestResolver;
use App\Services\TheoryPagePromptLinkedTestsService;
use Database\Seeders\Page_V3\Adjectives\AdjectivesCategorySeeder;
use Database\Seeders\Page_V3\Adjectives\AdjectivesComparativeVsSuperlativeTheorySeeder;
use Database\Seeders\Page_V3\Adjectives\AdjectivesDegreesOfComparisonTheorySeeder;
use Database\Seeders\Page_V3\Adjectives\AdjectivesEdIngAdjectivesTheorySeeder;
use Database\Seeders\Page_V3\Adjectives\AdjectivesEqualityComparisonAsAsNotAsAsTheorySeeder;
use Database\Seeders\Page_V3\Adjectives\AdjectivesIntensifiersTheorySeeder;
use Database\Seeders\Page_V3\Adjectives\AdjectivesOrderOfAdjectivesTheorySeeder;
use Database\Seeders\Page_V3\Adjectives\AdjectivesVsAdverbsTheorySeeder;
use Database\Seeders\V3\AdjectivesAdverbsAllLevelsV3Seeder;
use Database\Seeders\V3\AdjectivesVsAdverbsAllLevelsV3Seeder;
use Database\Seeders\V3\ComparativeVsSuperlativeAllLevelsV3Seeder;
use Database\Seeders\V3\DegreesOfComparisonAllLevelsV3Seeder;
use Database\Seeders\V3\EdIngAdjectivesAllLevelsV3Seeder;
use Database\Seeders\V3\EqualityComparisonAsAsNotAsAsAllLevelsV3Seeder;
use Database\Seeders\V3\IntensifiersAllLevelsV3Seeder;
use Database\Seeders\V3\OrderOfAdjectivesAllLevelsV3Seeder;
use Database\Seeders\V3\Polyglot\PolyglotAdjectivesVsAdverbsAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotComparativeVsSuperlativeAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotComparativesLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotDegreesOfComparisonAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotEdIngAdjectivesAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotEqualityComparisonAsAsNotAsAsAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotIntensifiersAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotOrderOfAdjectivesAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotSuperlativesLessonSeeder;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Tests\Support\RebuildsComposeTestSchema;
use Tests\TestCase;

class AdjectivesSectionMixedCardsTest extends TestCase
{
    use RebuildsComposeTestSchema;

    private const LEVEL_PAIRS = [
        ['A1', 'A2'],
        ['A2', 'B1'],
        ['B1', 'B2'],
        ['B2', 'C1'],
        ['C1', 'C2'],
    ];

    protected function setUp(): void
    {
        parent::setUp();

        config([
            'coming-soon.enabled' => false,
            'tests.tech_info_enabled' => false,
        ]);

        $this->rebuildComposeTestSchema();
        $this->augmentTheorySchema();
    }

    public function test_adjectives_lesson_pages_build_five_mixed_pair_cards_from_only_page_local_seeders(): void
    {
        $this->seedAdjectivesTheoryPages();
        $this->seedAdjectivesSectionSeeders();

        $service = app(TheoryPagePromptLinkedTestsService::class);
        $cases = $this->pageCases();

        foreach ($cases as $slug => $case) {
            $page = Page::query()->where('slug', $slug)->firstOrFail();
            $tests = $service->buildForPage($page);

            $this->assertCount(5, $tests, $slug);
            $this->assertSame(
                self::LEVEL_PAIRS,
                $tests->map(fn ($test) => $test->filters['levels'] ?? [])->values()->all(),
                $slug
            );

            foreach ($tests as $test) {
                $filters = $test->filters ?? [];

                $this->assertTrue($test->isVirtual(), $slug);
                $this->assertTrue(str_starts_with((string) $test->slug, 'theory-page-' . $page->id . '-'), $slug);
                $this->assertTrue(($filters['__meta']['aggregated_theory_page_test'] ?? false), $slug);
                $this->assertTrue(($filters['__meta']['theory_page_mixed_polyglot_test'] ?? false), $slug);
                $this->assertSame(
                    collect($case['seeders'])->sort()->values()->all(),
                    collect($filters['seeder_classes'] ?? [])->sort()->values()->all(),
                    $slug
                );
                $this->assertCount(2, $filters['seeder_classes'] ?? [], $slug);
            }

            $response = $this->get(route('theory.show', ['prykmetniky-ta-pryslinknyky', $slug]));
            $response->assertOk();
            $response->assertViewHas('topicTests', function ($topicTests) use ($case, $page) {
                return collect($topicTests)->count() === 5
                    && collect($topicTests)->every(function ($test) use ($case, $page) {
                        $filters = $test->filters ?? [];

                        return str_starts_with((string) ($test->slug ?? ''), 'theory-page-' . $page->id . '-')
                            && ($filters['__meta']['theory_page_mixed_polyglot_test'] ?? false) === true
                            && count($filters['seeder_classes'] ?? []) === 2
                            && collect($filters['seeder_classes'] ?? [])->sort()->values()->all() === collect($case['seeders'])->sort()->values()->all();
                    });
            });
        }
    }

    public function test_adjectives_seeders_have_full_all_level_coverage_and_category_builds_five_cards(): void
    {
        $this->seedAdjectivesTheoryPages();
        $this->seedAdjectivesSectionSeeders();

        foreach ($this->pageCases() as $slug => $case) {
            foreach ($case['seeders'] as $seederClass) {
                $query = Question::query()->where('seeder', $seederClass);
                $this->assertSame(72, $query->count(), $seederClass);

                foreach (['A1', 'A2', 'B1', 'B2', 'C1', 'C2'] as $level) {
                    $this->assertSame(12, (clone $query)->where('level', $level)->count(), $seederClass . ' ' . $level);
                }
            }
        }

        $category = PageCategory::query()->where('slug', 'prykmetniky-ta-pryslinknyky')->firstOrFail();
        $tests = app(AutoGeneratedTestService::class)->generateTests($category->tags()->get(), $category->title);

        $this->assertCount(5, $tests);
        $this->assertSame(self::LEVEL_PAIRS, $tests->map(fn ($test) => $test->filters['levels'] ?? [])->values()->all());
    }

    public function test_adjectives_mixed_virtual_filters_keep_v3_and_ignore_legacy_course_seeders(): void
    {
        $this->seedAdjectivesTheoryPages();
        $this->seedAdjectivesSectionSeeders();

        $page = Page::query()->where('slug', 'theory-degrees-of-comparison')->firstOrFail();
        $test = app(TheoryPagePromptLinkedTestsService::class)
            ->buildForPage($page)
            ->firstWhere('slug', 'theory-page-' . $page->id . '-a1-a2');

        $this->assertNotNull($test);

        $filters = $test->filters ?? [];
        $filters['num_questions'] = 72;
        $filters['randomize_filtered'] = false;

        $query = http_build_query([
            'filters' => base64_encode((string) json_encode($filters, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)),
            'name' => $test->name,
        ]);

        $request = \Illuminate\Http\Request::create('/test/' . $test->slug . '?' . $query, 'GET');
        $this->app->instance('request', $request);

        $resolved = app(SavedTestResolver::class)->resolve($test->slug);
        $questions = $resolved->preloadedQuestions ?? collect();

        $this->assertTrue($questions->pluck('seeder')->contains(DegreesOfComparisonAllLevelsV3Seeder::class));
        $this->assertTrue($questions->pluck('seeder')->contains(PolyglotDegreesOfComparisonAllLevelsLessonSeeder::class));
        $this->assertFalse($questions->pluck('seeder')->contains(PolyglotComparativesLessonSeeder::class));
        $this->assertTrue($questions->contains(fn ($question) => (string) $question->type === '0'));
        $this->assertTrue($questions->contains(fn ($question) => (string) $question->type === '4'));
    }

    /**
     * @return array<string, array{seeders: array<int, class-string>}>
     */
    protected function pageCases(): array
    {
        return [
            'adjectives-vs-adverbs' => [
                'seeders' => [
                    AdjectivesVsAdverbsAllLevelsV3Seeder::class,
                    PolyglotAdjectivesVsAdverbsAllLevelsLessonSeeder::class,
                ],
            ],
            'theory-degrees-of-comparison' => [
                'seeders' => [
                    DegreesOfComparisonAllLevelsV3Seeder::class,
                    PolyglotDegreesOfComparisonAllLevelsLessonSeeder::class,
                ],
            ],
            'comparative-vs-superlative' => [
                'seeders' => [
                    ComparativeVsSuperlativeAllLevelsV3Seeder::class,
                    PolyglotComparativeVsSuperlativeAllLevelsLessonSeeder::class,
                ],
            ],
            'equality-comparison-asas-not-asas' => [
                'seeders' => [
                    EqualityComparisonAsAsNotAsAsAllLevelsV3Seeder::class,
                    PolyglotEqualityComparisonAsAsNotAsAsAllLevelsLessonSeeder::class,
                ],
            ],
            'order-of-adjectives' => [
                'seeders' => [
                    OrderOfAdjectivesAllLevelsV3Seeder::class,
                    PolyglotOrderOfAdjectivesAllLevelsLessonSeeder::class,
                ],
            ],
            'ed-ing-adjectives' => [
                'seeders' => [
                    EdIngAdjectivesAllLevelsV3Seeder::class,
                    PolyglotEdIngAdjectivesAllLevelsLessonSeeder::class,
                ],
            ],
            'intensifiers' => [
                'seeders' => [
                    IntensifiersAllLevelsV3Seeder::class,
                    PolyglotIntensifiersAllLevelsLessonSeeder::class,
                ],
            ],
        ];
    }

    protected function seedAdjectivesTheoryPages(): void
    {
        $this->seed(AdjectivesCategorySeeder::class);
        $this->seed(AdjectivesVsAdverbsTheorySeeder::class);
        $this->seed(AdjectivesDegreesOfComparisonTheorySeeder::class);
        $this->seed(AdjectivesComparativeVsSuperlativeTheorySeeder::class);
        $this->seed(AdjectivesEqualityComparisonAsAsNotAsAsTheorySeeder::class);
        $this->seed(AdjectivesOrderOfAdjectivesTheorySeeder::class);
        $this->seed(AdjectivesEdIngAdjectivesTheorySeeder::class);
        $this->seed(AdjectivesIntensifiersTheorySeeder::class);
    }

    protected function seedAdjectivesSectionSeeders(): void
    {
        $this->seed([
            AdjectivesAdverbsAllLevelsV3Seeder::class,
            AdjectivesVsAdverbsAllLevelsV3Seeder::class,
            DegreesOfComparisonAllLevelsV3Seeder::class,
            ComparativeVsSuperlativeAllLevelsV3Seeder::class,
            EqualityComparisonAsAsNotAsAsAllLevelsV3Seeder::class,
            OrderOfAdjectivesAllLevelsV3Seeder::class,
            EdIngAdjectivesAllLevelsV3Seeder::class,
            IntensifiersAllLevelsV3Seeder::class,
            PolyglotComparativesLessonSeeder::class,
            PolyglotSuperlativesLessonSeeder::class,
            PolyglotAdjectivesVsAdverbsAllLevelsLessonSeeder::class,
            PolyglotDegreesOfComparisonAllLevelsLessonSeeder::class,
            PolyglotComparativeVsSuperlativeAllLevelsLessonSeeder::class,
            PolyglotEqualityComparisonAsAsNotAsAsAllLevelsLessonSeeder::class,
            PolyglotOrderOfAdjectivesAllLevelsLessonSeeder::class,
            PolyglotEdIngAdjectivesAllLevelsLessonSeeder::class,
            PolyglotIntensifiersAllLevelsLessonSeeder::class,
        ]);
    }

    protected function augmentTheorySchema(): void
    {
        Schema::create('text_blocks', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->nullable()->unique();
            $table->unsignedBigInteger('page_id')->nullable();
            $table->unsignedBigInteger('page_category_id')->nullable();
            $table->string('locale', 8)->nullable();
            $table->string('type')->nullable();
            $table->string('column')->nullable();
            $table->string('heading')->nullable();
            $table->string('css_class')->nullable();
            $table->integer('sort_order')->default(0);
            $table->text('body')->nullable();
            $table->string('level')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('page_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('page_id');
            $table->timestamps();
            $table->unique(['tag_id', 'page_id']);
        });

        Schema::create('page_category_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('page_category_id');
            $table->timestamps();
            $table->unique(['tag_id', 'page_category_id']);
        });

        Schema::create('tag_text_block', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('text_block_id');
            $table->timestamps();
            $table->unique(['tag_id', 'text_block_id']);
        });

        Schema::create('site_tree_variants', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->nullable();
            $table->boolean('is_base')->default(false);
            $table->timestamps();
        });

        Schema::create('site_tree_items', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('variant_id')->nullable();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('title')->nullable();
            $table->string('linked_page_title')->nullable();
            $table->string('linked_page_url')->nullable();
            $table->string('link_method')->nullable();
            $table->unsignedInteger('level')->default(0);
            $table->boolean('is_checked')->default(false);
            $table->unsignedInteger('sort_order')->default(0);
            $table->timestamps();
        });
    }
}
