<?php

namespace Tests\Feature;

use App\Models\Page;
use App\Models\PageCategory;
use App\Models\TextBlock;
use App\Models\TheoryVariant;
use App\Models\TheoryVariantSelection;
use App\Services\AutoGeneratedTestService;
use App\Services\Theory\TextBlockToQuestionsMatcherService;
use App\Services\TheoryPagePromptLinkedTestsService;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Tests\TestCase;

class TheoryVariantTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        config([
            'app.locale' => 'uk',
            'app.supported_locales' => ['uk', 'en', 'pl'],
        ]);

        app()->setLocale('uk');

        $this->setUpTheoryVariantSchema();
        $this->swapTheoryPageServices();
    }

    public function test_guest_does_not_see_switcher_on_theory_page_or_category(): void
    {
        ['category' => $category, 'page' => $page] = $this->createTheoryFixture();
        $this->createPageVariant($page, 'uk', 'copilot-uk-v1', 'Copilot UK V1', 'Variant page title');
        $this->createCategoryVariant($category, 'uk', 'category-uk-v1', 'Category UK V1', 'Variant category title');

        $this->get("/theory/{$category->slug}")
            ->assertOk()
            ->assertDontSee('Theory Variants');

        $this->get("/theory/{$category->slug}/{$page->slug}")
            ->assertOk()
            ->assertDontSee('Theory Variants');
    }

    public function test_admin_sees_switcher_on_theory_page_or_category(): void
    {
        ['category' => $category, 'page' => $page] = $this->createTheoryFixture();
        $this->createPageVariant($page, 'uk', 'copilot-uk-v1', 'Copilot UK V1', 'Variant page title');
        $this->createCategoryVariant($category, 'uk', 'category-uk-v1', 'Category UK V1', 'Variant category title');

        $this->withSession(['admin_authenticated' => true])
            ->get("/theory/{$category->slug}")
            ->assertOk()
            ->assertSee('Theory Variants')
            ->assertSee('Base / Current')
            ->assertSee('Category UK V1');

        $this->withSession(['admin_authenticated' => true])
            ->get("/theory/{$category->slug}/{$page->slug}")
            ->assertOk()
            ->assertSee('Theory Variants')
            ->assertSee('Base / Current')
            ->assertSee('Copilot UK V1');
    }

    public function test_admin_preview_query_param_works_on_theory_page(): void
    {
        ['category' => $category, 'page' => $page] = $this->createTheoryFixture();
        $this->createPageVariant($page, 'uk', 'copilot-uk-v1', 'Copilot UK V1', 'Preview title');
        $published = $this->createPageVariant($page, 'uk', 'published-uk-v1', 'Published UK V1', 'Published title');
        $this->publishVariant($published);

        $this->withSession(['admin_authenticated' => true])
            ->get("/theory/{$category->slug}/{$page->slug}?variant=copilot-uk-v1")
            ->assertOk()
            ->assertSee('Preview title')
            ->assertSee('Preview');
    }

    public function test_guest_cannot_force_variant_preview_with_query_param(): void
    {
        ['category' => $category, 'page' => $page] = $this->createTheoryFixture();
        $this->createPageVariant($page, 'uk', 'copilot-uk-v1', 'Copilot UK V1', 'Hidden preview title');

        $this->get("/theory/{$category->slug}/{$page->slug}?variant=copilot-uk-v1")
            ->assertOk()
            ->assertSee('Base page title')
            ->assertDontSee('Hidden preview title');
    }

    public function test_public_sees_published_variant_on_theory_page(): void
    {
        ['category' => $category, 'page' => $page] = $this->createTheoryFixture();
        $variant = $this->createPageVariant($page, 'uk', 'copilot-uk-v1', 'Copilot UK V1', 'Published page title');
        $this->publishVariant($variant);

        $this->get("/theory/{$category->slug}/{$page->slug}")
            ->assertOk()
            ->assertSee('Published page title');
    }

    public function test_public_falls_back_to_base_when_no_selection_exists(): void
    {
        ['category' => $category, 'page' => $page] = $this->createTheoryFixture();
        $this->createPageVariant($page, 'uk', 'copilot-uk-v1', 'Copilot UK V1', 'Unpublished page title');

        $this->get("/theory/{$category->slug}/{$page->slug}")
            ->assertOk()
            ->assertSee('Base page title')
            ->assertDontSee('Unpublished page title');
    }

    public function test_locale_specific_selection_works_for_uk_en_and_pl(): void
    {
        ['category' => $category, 'page' => $page] = $this->createTheoryFixture();

        $ukVariant = $this->createPageVariant($page, 'uk', 'uk-v1', 'UK Variant', 'UK title');
        $enVariant = $this->createPageVariant($page, 'en', 'en-v1', 'EN Variant', 'EN title');
        $plVariant = $this->createPageVariant($page, 'pl', 'pl-v1', 'PL Variant', 'PL title');

        $this->publishVariant($ukVariant);
        $this->publishVariant($enVariant);
        $this->publishVariant($plVariant);

        app()->setLocale('uk');
        $this->get("/theory/{$category->slug}/{$page->slug}")
            ->assertOk()
            ->assertSee('UK title');

        app()->setLocale('en');
        $this->get("/theory/{$category->slug}/{$page->slug}")
            ->assertOk()
            ->assertSee('EN title');

        app()->setLocale('pl');
        $this->get("/theory/{$category->slug}/{$page->slug}")
            ->assertOk()
            ->assertSee('PL title');
    }

    public function test_base_reset_works(): void
    {
        ['category' => $category, 'page' => $page] = $this->createTheoryFixture();
        $variant = $this->createPageVariant($page, 'uk', 'copilot-uk-v1', 'Copilot UK V1', 'Published page title');
        $this->publishVariant($variant);

        $url = "/theory/{$category->slug}/{$page->slug}";

        $this->withSession(['admin_authenticated' => true])
            ->from($url)
            ->post(route('theory-variants.reset'), [
                'target_type' => 'page',
                'target_id' => $page->getKey(),
                'locale' => 'uk',
            ])
            ->assertRedirect($url);

        $this->assertDatabaseHas('theory_variant_selections', [
            'variantable_type' => Page::class,
            'variantable_id' => $page->getKey(),
            'locale' => 'uk',
            'theory_variant_id' => null,
        ]);

        $this->get($url)
            ->assertOk()
            ->assertSee('Base page title')
            ->assertDontSee('Published page title');
    }

    public function test_public_sees_published_variant_on_theory_category_page(): void
    {
        ['category' => $category] = $this->createTheoryFixture();
        $variant = $this->createCategoryVariant($category, 'uk', 'category-uk-v1', 'Category UK V1', 'Published category title');
        $this->publishVariant($variant);

        $this->get("/theory/{$category->slug}")
            ->assertOk()
            ->assertSee('Published category title');
    }

    /**
     * @return array{category: PageCategory, page: Page}
     */
    private function createTheoryFixture(): array
    {
        $category = PageCategory::query()->create([
            'title' => 'Base category title',
            'slug' => 'tenses',
            'language' => 'uk',
            'type' => 'theory',
        ]);

        $page = Page::query()->create([
            'slug' => 'present-simple',
            'title' => 'Base page title',
            'text' => 'Base page summary',
            'type' => 'theory',
            'page_category_id' => $category->getKey(),
        ]);

        TextBlock::query()->create([
            'uuid' => (string) Str::uuid(),
            'page_id' => null,
            'page_category_id' => $category->getKey(),
            'locale' => 'uk',
            'type' => 'subtitle',
            'column' => 'header',
            'sort_order' => 0,
            'body' => '<p>Base category title</p>',
        ]);

        TextBlock::query()->create([
            'uuid' => (string) Str::uuid(),
            'page_id' => null,
            'page_category_id' => $category->getKey(),
            'locale' => 'uk',
            'type' => 'box',
            'column' => 'left',
            'heading' => 'Base category heading',
            'sort_order' => 10,
            'body' => '<p>Base category body</p>',
        ]);

        TextBlock::query()->create([
            'uuid' => (string) Str::uuid(),
            'page_id' => $page->getKey(),
            'page_category_id' => $category->getKey(),
            'locale' => 'uk',
            'type' => 'subtitle',
            'column' => 'header',
            'sort_order' => 0,
            'body' => '<p>Base page title</p>',
        ]);

        TextBlock::query()->create([
            'uuid' => (string) Str::uuid(),
            'page_id' => $page->getKey(),
            'page_category_id' => $category->getKey(),
            'locale' => 'uk',
            'type' => 'box',
            'column' => 'left',
            'heading' => 'Base page heading',
            'sort_order' => 10,
            'body' => '<p>Base page body</p>',
        ]);

        return compact('category', 'page');
    }

    private function createPageVariant(
        Page $page,
        string $locale,
        string $variantKey,
        string $label,
        string $title
    ): TheoryVariant {
        return TheoryVariant::query()->create([
            'variantable_type' => Page::class,
            'variantable_id' => $page->getKey(),
            'locale' => $locale,
            'variant_key' => $variantKey,
            'label' => $label,
            'status' => 'ready',
            'payload' => [
                'title' => $title,
                'subtitle_html' => '<p>' . $label . ' subtitle</p>',
                'subtitle_text' => $label . ' subtitle',
                'locale' => $locale,
                'blocks' => [
                    [
                        'column' => 'left',
                        'type' => 'box',
                        'heading' => $label . ' heading',
                        'body' => '<p>' . $label . ' body</p>',
                        'sort_order' => 10,
                    ],
                ],
            ],
        ]);
    }

    private function createCategoryVariant(
        PageCategory $category,
        string $locale,
        string $variantKey,
        string $label,
        string $title
    ): TheoryVariant {
        return TheoryVariant::query()->create([
            'variantable_type' => PageCategory::class,
            'variantable_id' => $category->getKey(),
            'locale' => $locale,
            'variant_key' => $variantKey,
            'label' => $label,
            'status' => 'ready',
            'payload' => [
                'title' => $title,
                'subtitle_html' => '<p>' . $label . ' subtitle</p>',
                'subtitle_text' => $label . ' subtitle',
                'locale' => $locale,
                'blocks' => [
                    [
                        'column' => 'left',
                        'type' => 'box',
                        'heading' => $label . ' heading',
                        'body' => '<p>' . $label . ' body</p>',
                        'sort_order' => 10,
                    ],
                ],
            ],
        ]);
    }

    private function publishVariant(TheoryVariant $variant): void
    {
        TheoryVariantSelection::query()->updateOrCreate(
            [
                'variantable_type' => $variant->variantable_type,
                'variantable_id' => $variant->variantable_id,
                'locale' => $variant->locale,
            ],
            [
                'theory_variant_id' => $variant->getKey(),
            ]
        );
    }

    private function swapTheoryPageServices(): void
    {
        $this->app->instance(AutoGeneratedTestService::class, new class extends AutoGeneratedTestService
        {
            public function generateTests(Collection $tags, string $contextPrefix = ''): Collection
            {
                return collect();
            }
        });

        $this->app->instance(TheoryPagePromptLinkedTestsService::class, new class extends TheoryPagePromptLinkedTestsService
        {
            public function buildForPage(Page $page): Collection
            {
                return collect();
            }
        });

        $this->app->instance(TextBlockToQuestionsMatcherService::class, new class extends TextBlockToQuestionsMatcherService
        {
            public function __construct()
            {
            }

            public function findQuestionsForTextBlocks(EloquentCollection $blocks, int $limitPerBlock = 5): array
            {
                return [];
            }
        });
    }

    private function setUpTheoryVariantSchema(): void
    {
        Schema::dropIfExists('theory_variant_selections');
        Schema::dropIfExists('theory_variants');
        Schema::dropIfExists('tag_text_block');
        Schema::dropIfExists('page_category_tag');
        Schema::dropIfExists('page_tag');
        Schema::dropIfExists('text_blocks');
        Schema::dropIfExists('pages');
        Schema::dropIfExists('page_categories');
        Schema::dropIfExists('tags');
        Schema::dropIfExists('questions');
        Schema::dropIfExists('question_tag');
        Schema::dropIfExists('site_tree_variants');

        Schema::create('page_categories', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->string('slug')->unique();
            $table->string('language')->nullable();
            $table->string('type')->nullable();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('pages', function (Blueprint $table) {
            $table->id();
            $table->string('slug')->unique();
            $table->string('title');
            $table->text('text')->nullable();
            $table->string('type')->nullable();
            $table->string('seeder')->nullable();
            $table->unsignedBigInteger('page_category_id')->nullable();
            $table->timestamps();
        });

        Schema::create('text_blocks', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->nullable();
            $table->unsignedBigInteger('page_id')->nullable();
            $table->unsignedBigInteger('page_category_id')->nullable();
            $table->string('locale')->nullable();
            $table->string('type')->nullable();
            $table->string('column')->nullable();
            $table->string('heading')->nullable();
            $table->string('css_class')->nullable();
            $table->integer('sort_order')->default(0);
            $table->text('body')->nullable();
            $table->string('level')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('tags', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('category')->nullable();
            $table->timestamps();
        });

        Schema::create('page_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('page_id');
            $table->timestamps();
        });

        Schema::create('page_category_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('page_category_id');
            $table->timestamps();
        });

        Schema::create('tag_text_block', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('text_block_id');
            $table->timestamps();
        });

        Schema::create('questions', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->nullable();
            $table->text('question')->nullable();
            $table->string('level')->nullable();
            $table->unsignedTinyInteger('flag')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('question_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('question_id');
            $table->unsignedBigInteger('tag_id');
            $table->timestamps();
        });

        Schema::create('site_tree_variants', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->nullable();
            $table->boolean('is_base')->default(false);
            $table->timestamps();
        });

        Schema::create('theory_variants', function (Blueprint $table) {
            $table->id();
            $table->string('variantable_type');
            $table->unsignedBigInteger('variantable_id');
            $table->string('locale');
            $table->string('variant_key');
            $table->string('label');
            $table->string('provider')->nullable();
            $table->string('model')->nullable();
            $table->string('status')->default('ready');
            $table->json('payload');
            $table->string('source_hash')->nullable();
            $table->string('prompt_version')->nullable();
            $table->string('seeder_class')->nullable();
            $table->timestamps();
        });

        Schema::create('theory_variant_selections', function (Blueprint $table) {
            $table->id();
            $table->string('variantable_type');
            $table->unsignedBigInteger('variantable_id');
            $table->string('locale');
            $table->unsignedBigInteger('theory_variant_id')->nullable();
            $table->timestamps();
        });
    }
}
