<?php

namespace Tests\Feature;

use App\Models\Page;
use App\Models\PageCategory;
use App\Models\Question;
use App\Models\SavedGrammarTest;
use App\Models\TextBlock;
use App\Services\AutoGeneratedTestService;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Tests\TestCase;

class TheoryPagePromptLinkedTestsTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        $viewsPath = storage_path('framework/views');
        if (! is_dir($viewsPath)) {
            mkdir($viewsPath, 0777, true);
        }
        config(['view.compiled' => $viewsPath]);

        $this->setUpContentTables();
    }

    public function test_theory_page_aggregates_all_linked_seeders_into_five_level_pair_tests(): void
    {
        app()->setLocale('uk');

        $autoGeneratedTestService = \Mockery::mock(AutoGeneratedTestService::class);
        $autoGeneratedTestService->shouldNotReceive('generateTests');
        $this->app->instance(AutoGeneratedTestService::class, $autoGeneratedTestService);

        [$category, $page] = $this->createTheoryPage('Alternative Questions', 'alternative-questions');
        [, $otherPage] = $this->createTheoryPage('Reported Speech', 'reported-speech');

        $firstSeeder = 'Database\\Seeders\\V3\\AI\\ChatGptPro\\AlternativeQuestionsASeeder';
        $secondSeeder = 'Database\\Seeders\\V3\\AI\\Gemini\\AlternativeQuestionsBSeeder';
        $otherSeeder = 'Database\\Seeders\\V3\\AI\\ChatGptPro\\ReportedSpeechSeeder';

        $this->seedQuestionsForSeeder($firstSeeder, 4);
        $this->seedQuestionsForSeeder($secondSeeder, 4);
        $this->seedQuestionsForSeeder($otherSeeder, 4);

        $this->createSavedTest(
            'Alternative Questions A',
            'alternative-questions-a',
            $page,
            $firstSeeder
        );

        $this->createSavedTest(
            'Alternative Questions B',
            'alternative-questions-b',
            $page,
            $secondSeeder
        );

        $this->createSavedTest(
            'Reported Speech',
            'reported-speech',
            $otherPage,
            $otherSeeder
        );

        $response = $this->get(route('theory.show', [$category->slug, $page->slug]));

        $response->assertOk();
        $response->assertViewMissing('autoGeneratedTests');
        $response->assertSee('Alternative Questions (A1-A2)');
        $response->assertSee('Alternative Questions (A2-B1)');
        $response->assertSee('Alternative Questions (B1-B2)');
        $response->assertSee('Alternative Questions (B2-C1)');
        $response->assertSee('Alternative Questions (C1-C2)');
        $response->assertViewHas('topicTests', function ($tests) use ($firstSeeder, $secondSeeder) {
            if ($tests->count() !== 5) {
                return false;
            }

            $expectedPairs = collect([
                ['A1', 'A2'],
                ['A2', 'B1'],
                ['B1', 'B2'],
                ['B2', 'C1'],
                ['C1', 'C2'],
            ]);

            return $tests->map(fn ($test) => $test->filters['levels'] ?? [])->values()->toArray() === $expectedPairs->toArray()
                && $tests->every(function ($test) use ($firstSeeder, $secondSeeder) {
                    $filters = $test->filters ?? [];

                    return method_exists($test, 'isVirtual')
                        && $test->isVirtual()
                        && collect($filters['seeder_classes'] ?? [])->sort()->values()->all() === collect([$firstSeeder, $secondSeeder])->sort()->values()->all()
                        && ($filters['num_questions'] ?? null) === 15
                        && ($filters['randomize_filtered'] ?? false) === true
                        && ($filters['__meta']['aggregated_theory_page_test'] ?? false) === true
                        && ($test->getAttribute('total_questions_available') ?? 0) === 16;
                });
        });
    }

    public function test_theory_page_can_link_saved_tests_with_legacy_string_prompt_generator(): void
    {
        app()->setLocale('uk');

        $autoGeneratedTestService = \Mockery::mock(AutoGeneratedTestService::class);
        $autoGeneratedTestService->shouldNotReceive('generateTests');
        $this->app->instance(AutoGeneratedTestService::class, $autoGeneratedTestService);

        [$category, $page] = $this->createTheoryPage(
            'Plural Nouns — Множина іменників: правила, винятки, приклади',
            'plural-nouns-s-es-ies'
        );

        $seederClass = 'Database\\Seeders\\V3\\AI\\ChatGpt\\PluralNounsMnozinaImennikivPravilaViniatkiPrikladiV3QuestionsOnlySeeder';

        $this->seedQuestionsForSeeder($seederClass, 8);

        $this->createSavedTest(
            'Plural Nouns — Множина іменників: правила, винятки, приклади',
            'plural_nouns_mnozina_imennikiv_pravila_viniatki_prikladi',
            $page,
            $seederClass,
            sprintf(
                'source_type=theory_page; theory_page_id=%d; theory_page_ids=[%d]; theory_page.id=%d; theory_page.slug=%s; theory_page.title=%s',
                $page->id,
                $page->id,
                $page->id,
                $page->slug,
                $page->title
            )
        );

        $response = $this->get(route('theory.show', [$category->slug, $page->slug]));

        $response->assertOk();
        $response->assertViewHas('topicTests', function ($tests) use ($seederClass) {
            if ($tests->count() !== 5) {
                return false;
            }

            return $tests->every(function ($test) use ($seederClass) {
                $filters = $test->filters ?? [];

                return method_exists($test, 'isVirtual')
                    && $test->isVirtual()
                    && collect($filters['seeder_classes'] ?? [])->contains($seederClass)
                    && ($filters['num_questions'] ?? null) === 15
                    && ($test->getAttribute('total_questions_available') ?? 0) === 16;
            });
        });
    }

    public function test_theory_page_can_link_saved_tests_by_page_seeder_class_when_page_id_differs(): void
    {
        app()->setLocale('uk');

        $autoGeneratedTestService = \Mockery::mock(AutoGeneratedTestService::class);
        $autoGeneratedTestService->shouldNotReceive('generateTests');
        $this->app->instance(AutoGeneratedTestService::class, $autoGeneratedTestService);

        $pageSeederClass = 'Database\\Seeders\\Page_V3\\NounsArticlesQuantity\\NounsArticlesQuantityPluralNounsTheorySeeder';

        [$category, $page] = $this->createTheoryPage(
            'Plural Nouns — Множина іменників: правила, винятки, приклади',
            'plural-nouns-s-es-ies',
            'imennyky-artykli-ta-kilkist',
            $pageSeederClass
        );

        $seederClass = 'Database\\Seeders\\V3\\AI\\ChatGptPro\\PluralNounsMnozinaImennikivPravilaViniatkiPrikladiV3QuestionsOnlySeeder';

        $this->seedQuestionsForSeeder($seederClass, 8);

        $this->createSavedTest(
            'Plural Nouns — Множина іменників: правила, винятки, приклади',
            'plural_nouns_mnozina_imennikiv_pravila_viniatki_prikladi-seeder-link',
            $page,
            $seederClass,
            [
                'source_type' => 'theory_page',
                'theory_page_id' => 712,
                'theory_page_ids' => [712],
                'theory_page' => [
                    'id' => 712,
                    'title' => $page->title,
                    'page_seeder_class' => $pageSeederClass,
                ],
            ]
        );

        $response = $this->get(route('theory.show', [$category->slug, $page->slug]));

        $response->assertOk();
        $response->assertViewHas('topicTests', function ($tests) use ($seederClass) {
            if ($tests->count() !== 5) {
                return false;
            }

            return $tests->every(function ($test) use ($seederClass) {
                $filters = $test->filters ?? [];

                return method_exists($test, 'isVirtual')
                    && $test->isVirtual()
                    && collect($filters['seeder_classes'] ?? [])->contains($seederClass)
                    && ($filters['__meta']['aggregated_theory_page_test'] ?? false) === true
                    && ($test->getAttribute('total_questions_available') ?? 0) === 16;
            });
        });
    }

    public function test_theory_page_builds_aggregated_virtual_tests_for_prompt_linked_v3_seeder_without_saved_test(): void
    {
        app()->setLocale('uk');

        $autoGeneratedTestService = \Mockery::mock(AutoGeneratedTestService::class);
        $autoGeneratedTestService->shouldNotReceive('generateTests');
        $this->app->instance(AutoGeneratedTestService::class, $autoGeneratedTestService);

        $pageSeederClass = 'Database\\Seeders\\Page_V3\\NounsArticlesQuantity\\NounsArticlesQuantityPluralNounsTheorySeeder';

        [$category, $page] = $this->createTheoryPage(
            'Plural Nouns — Множина іменників: правила, винятки, приклади',
            'plural-nouns-s-es-ies',
            'imennyky-artykli-ta-kilkist',
            $pageSeederClass
        );

        $seederClass = 'Database\\Seeders\\V3\\AI\\ChatGpt\\PluralNounsMnozinaImennikivPravilaViniatkiPrikladiV3QuestionsOnlySeeder';

        $this->seedQuestionsForSeeder($seederClass, 8);

        $response = $this->get(route('theory.show', [$category->slug, $page->slug]));

        $response->assertOk();
        $response->assertViewHas('topicTests', function ($tests) use ($seederClass) {
            if ($tests->count() !== 5) {
                return false;
            }

            return $tests->every(function ($test) use ($seederClass) {
                $filters = $test->filters ?? [];

                return method_exists($test, 'isVirtual')
                    && $test->isVirtual()
                    && collect($filters['seeder_classes'] ?? [])->contains($seederClass)
                    && ($filters['num_questions'] ?? null) === 15
                    && ($test->getAttribute('total_questions_available') ?? 0) === 16;
            });
        });
    }

    public function test_theory_page_deduplicates_multiple_saved_tests_for_same_seeder_class(): void
    {
        app()->setLocale('uk');

        $autoGeneratedTestService = \Mockery::mock(AutoGeneratedTestService::class);
        $autoGeneratedTestService->shouldNotReceive('generateTests');
        $this->app->instance(AutoGeneratedTestService::class, $autoGeneratedTestService);

        [$category, $page] = $this->createTheoryPage('Alternative Questions', 'alternative-questions');

        $seederClass = 'Database\\Seeders\\V3\\AI\\ChatGptPro\\AlternativeQuestionsASeeder';
        $this->seedQuestionsForSeeder($seederClass, 8);

        $this->createSavedTest(
            'Alternative Questions Old',
            'alternative-questions-old',
            $page,
            $seederClass
        );

        $this->createSavedTest(
            'Alternative Questions New',
            'alternative-questions-new',
            $page,
            $seederClass
        );

        $response = $this->get(route('theory.show', [$category->slug, $page->slug]));

        $response->assertOk();
        $response->assertSee('Alternative Questions (A1-A2)');
        $response->assertDontSee('Alternative Questions New');
        $response->assertDontSee('Alternative Questions Old');
        $response->assertViewHas('topicTests', function ($tests) use ($seederClass) {
            return $tests->count() === 5
                && $tests->every(function ($test) use ($seederClass) {
                    $filters = $test->filters ?? [];

                    return collect($filters['seeder_classes'] ?? [])->values()->all() === [$seederClass];
                });
        });
    }

    protected function setUpContentTables(): void
    {
        Schema::disableForeignKeyConstraints();

        foreach ([
            'saved_grammar_test_questions',
            'saved_grammar_tests',
            'questions',
            'site_tree_items',
            'site_tree_variants',
            'tag_text_block',
            'page_category_tag',
            'page_tag',
            'tags',
            'text_blocks',
            'pages',
            'page_categories',
        ] as $table) {
            Schema::dropIfExists($table);
        }

        Schema::enableForeignKeyConstraints();

        Schema::create('page_categories', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('title');
            $table->string('slug')->unique();
            $table->string('language')->nullable();
            $table->string('type')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('pages', function (Blueprint $table) {
            $table->id();
            $table->foreignId('page_category_id')->nullable();
            $table->string('slug')->unique();
            $table->string('title');
            $table->text('text')->nullable();
            $table->string('type')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('text_blocks', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->nullable();
            $table->foreignId('page_id')->nullable();
            $table->foreignId('page_category_id')->nullable();
            $table->string('locale')->nullable();
            $table->string('type')->nullable();
            $table->string('column')->nullable();
            $table->string('heading')->nullable();
            $table->string('css_class')->nullable();
            $table->unsignedInteger('sort_order')->default(0);
            $table->text('body')->nullable();
            $table->string('level')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('tags', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('category')->nullable();
            $table->timestamps();
        });

        Schema::create('page_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('page_id');
            $table->unsignedBigInteger('tag_id');
            $table->timestamps();
        });

        Schema::create('page_category_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('page_category_id');
            $table->unsignedBigInteger('tag_id');
            $table->timestamps();
        });

        Schema::create('tag_text_block', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('text_block_id');
            $table->unsignedBigInteger('tag_id');
            $table->timestamps();
        });

        Schema::create('saved_grammar_tests', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique();
            $table->string('name');
            $table->string('slug')->unique();
            $table->json('filters');
            $table->text('description')->nullable();
            $table->timestamps();
        });

        Schema::create('saved_grammar_test_questions', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('saved_grammar_test_id');
            $table->uuid('question_uuid');
            $table->unsignedInteger('position')->default(0);
            $table->timestamps();
        });

        Schema::create('questions', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->nullable();
            $table->string('question')->nullable();
            $table->unsignedInteger('difficulty')->default(1);
            $table->string('level')->nullable();
            $table->unsignedBigInteger('category_id')->nullable();
            $table->unsignedBigInteger('source_id')->nullable();
            $table->unsignedInteger('flag')->default(0);
            $table->string('seeder')->nullable();
            $table->string('type')->nullable();
            $table->json('options_by_marker')->nullable();
            $table->timestamps();
        });

        Schema::create('site_tree_variants', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->nullable();
            $table->boolean('is_base')->default(false);
            $table->timestamps();
        });

        Schema::create('site_tree_items', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('variant_id')->nullable();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('title')->nullable();
            $table->string('linked_page_title')->nullable();
            $table->string('linked_page_url')->nullable();
            $table->string('link_method')->nullable();
            $table->unsignedInteger('level')->default(0);
            $table->boolean('is_checked')->default(false);
            $table->unsignedInteger('sort_order')->default(0);
            $table->timestamps();
        });
    }

    /**
     * @return array{0: PageCategory, 1: Page}
     */
    protected function createTheoryPage(
        string $title,
        string $slug,
        ?string $categorySlug = null,
        ?string $seederClass = null
    ): array
    {
        $category = PageCategory::create([
            'title' => 'Questions',
            'slug' => $categorySlug ?? ('questions-' . $slug),
            'language' => 'uk',
            'type' => 'theory',
            'seeder' => $seederClass,
        ]);

        $page = Page::create([
            'title' => $title,
            'slug' => $slug,
            'type' => 'theory',
            'page_category_id' => $category->id,
            'seeder' => $seederClass,
        ]);

        TextBlock::create([
            'uuid' => (string) Str::uuid(),
            'page_id' => $page->id,
            'page_category_id' => $category->id,
            'locale' => 'uk',
            'type' => 'subtitle',
            'column' => 'left',
            'body' => $title,
            'sort_order' => 1,
        ]);

        TextBlock::create([
            'uuid' => (string) Str::uuid(),
            'page_id' => $page->id,
            'page_category_id' => $category->id,
            'locale' => 'uk',
            'type' => 'box',
            'column' => 'left',
            'heading' => $title . ' overview',
            'body' => 'Theory content for ' . $title,
            'sort_order' => 2,
        ]);

        return [$category, $page];
    }

    protected function createSavedTest(
        string $name,
        string $slug,
        Page $page,
        string $seederClass,
        mixed $promptGenerator = null,
    ): SavedGrammarTest
    {
        $test = SavedGrammarTest::create([
            'uuid' => (string) Str::uuid(),
            'name' => $name,
            'slug' => $slug,
            'description' => null,
            'filters' => [
                'levels' => ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
                'num_questions' => 108,
                'difficulty_from' => 1,
                'difficulty_to' => 5,
                'seeder_classes' => [$seederClass],
                'prompt_generator' => $promptGenerator ?? [
                    'source_type' => 'theory_page',
                    'theory_page_id' => $page->id,
                    'theory_page_ids' => [$page->id],
                    'theory_page' => [
                        'id' => $page->id,
                        'slug' => $page->slug,
                        'title' => $page->title,
                        'page_seeder_class' => $page->seeder,
                    ],
                ],
            ],
        ]);

        for ($index = 1; $index <= 3; $index++) {
            $test->questionLinks()->create([
                'question_uuid' => (string) Str::uuid(),
                'position' => $index,
            ]);
        }

        return $test->fresh();
    }

    protected function seedQuestionsForSeeder(string $seederClass, int $perLevel): void
    {
        foreach (['A1', 'A2', 'B1', 'B2', 'C1', 'C2'] as $level) {
            for ($index = 1; $index <= $perLevel; $index++) {
                Question::create([
                    'uuid' => (string) Str::uuid(),
                    'question' => sprintf('%s %s question %d', class_basename($seederClass), $level, $index),
                    'difficulty' => 1,
                    'level' => $level,
                    'flag' => 0,
                    'seeder' => $seederClass,
                ]);
            }
        }
    }
}
