<?php

namespace Tests\Feature;

use App\Models\Page;
use App\Models\PageCategory;
use App\Models\SavedGrammarTest;
use App\Models\TextBlock;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Tests\TestCase;

class TheoryPagePromptLinkedTestsTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        $viewsPath = storage_path('framework/views');
        if (! is_dir($viewsPath)) {
            mkdir($viewsPath, 0777, true);
        }
        config(['view.compiled' => $viewsPath]);

        $this->setUpContentTables();
    }

    public function test_theory_page_shows_all_prompt_linked_saved_tests_in_tests_on_topic_block(): void
    {
        app()->setLocale('uk');

        [$category, $page] = $this->createTheoryPage('Alternative Questions', 'alternative-questions');
        [, $otherPage] = $this->createTheoryPage('Reported Speech', 'reported-speech');

        $firstLinkedTest = $this->createSavedTest(
            'Alternative Questions A2-B1',
            'alternative-questions-a2-b1',
            $page,
            12
        );

        $secondLinkedTest = $this->createSavedTest(
            'Alternative Questions B1-B2',
            'alternative-questions-b1-b2',
            $page,
            10
        );

        $this->createSavedTest(
            'Reported Speech Practice',
            'reported-speech-practice',
            $otherPage,
            8
        );

        $response = $this->get(route('theory.show', [$category->slug, $page->slug]));

        $response->assertOk();
        $response->assertSee($firstLinkedTest->name);
        $response->assertSee($secondLinkedTest->name);
        $response->assertDontSee('Reported Speech Practice');
        $response->assertViewHas('autoGeneratedTests', function ($tests) use ($firstLinkedTest, $secondLinkedTest) {
            return $tests->pluck('slug')->sort()->values()->all() === collect([
                $firstLinkedTest->slug,
                $secondLinkedTest->slug,
            ])->sort()->values()->all();
        });
    }

    protected function setUpContentTables(): void
    {
        Schema::disableForeignKeyConstraints();

        foreach ([
            'saved_grammar_test_questions',
            'saved_grammar_tests',
            'site_tree_items',
            'site_tree_variants',
            'tag_text_block',
            'page_category_tag',
            'page_tag',
            'tags',
            'text_blocks',
            'pages',
            'page_categories',
        ] as $table) {
            Schema::dropIfExists($table);
        }

        Schema::enableForeignKeyConstraints();

        Schema::create('page_categories', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('title');
            $table->string('slug')->unique();
            $table->string('language')->nullable();
            $table->string('type')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('pages', function (Blueprint $table) {
            $table->id();
            $table->foreignId('page_category_id')->nullable();
            $table->string('slug')->unique();
            $table->string('title');
            $table->text('text')->nullable();
            $table->string('type')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('text_blocks', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->nullable();
            $table->foreignId('page_id')->nullable();
            $table->foreignId('page_category_id')->nullable();
            $table->string('locale')->nullable();
            $table->string('type')->nullable();
            $table->string('column')->nullable();
            $table->string('heading')->nullable();
            $table->string('css_class')->nullable();
            $table->unsignedInteger('sort_order')->default(0);
            $table->text('body')->nullable();
            $table->string('level')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('tags', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('category')->nullable();
            $table->timestamps();
        });

        Schema::create('page_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('page_id');
            $table->unsignedBigInteger('tag_id');
            $table->timestamps();
        });

        Schema::create('page_category_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('page_category_id');
            $table->unsignedBigInteger('tag_id');
            $table->timestamps();
        });

        Schema::create('tag_text_block', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('text_block_id');
            $table->unsignedBigInteger('tag_id');
            $table->timestamps();
        });

        Schema::create('saved_grammar_tests', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique();
            $table->string('name');
            $table->string('slug')->unique();
            $table->json('filters');
            $table->text('description')->nullable();
            $table->timestamps();
        });

        Schema::create('saved_grammar_test_questions', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('saved_grammar_test_id');
            $table->uuid('question_uuid');
            $table->unsignedInteger('position')->default(0);
            $table->timestamps();
        });

        Schema::create('site_tree_variants', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->nullable();
            $table->boolean('is_base')->default(false);
            $table->timestamps();
        });

        Schema::create('site_tree_items', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('variant_id')->nullable();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('title')->nullable();
            $table->string('linked_page_title')->nullable();
            $table->string('linked_page_url')->nullable();
            $table->string('link_method')->nullable();
            $table->unsignedInteger('level')->default(0);
            $table->boolean('is_checked')->default(false);
            $table->unsignedInteger('sort_order')->default(0);
            $table->timestamps();
        });
    }

    /**
     * @return array{0: PageCategory, 1: Page}
     */
    protected function createTheoryPage(string $title, string $slug): array
    {
        $category = PageCategory::create([
            'title' => 'Questions',
            'slug' => 'questions-' . $slug,
            'language' => 'uk',
            'type' => 'theory',
        ]);

        $page = Page::create([
            'title' => $title,
            'slug' => $slug,
            'type' => 'theory',
            'page_category_id' => $category->id,
        ]);

        TextBlock::create([
            'uuid' => (string) Str::uuid(),
            'page_id' => $page->id,
            'page_category_id' => $category->id,
            'locale' => 'uk',
            'type' => 'subtitle',
            'column' => 'left',
            'body' => $title,
            'sort_order' => 1,
        ]);

        TextBlock::create([
            'uuid' => (string) Str::uuid(),
            'page_id' => $page->id,
            'page_category_id' => $category->id,
            'locale' => 'uk',
            'type' => 'box',
            'column' => 'left',
            'heading' => $title . ' overview',
            'body' => 'Theory content for ' . $title,
            'sort_order' => 2,
        ]);

        return [$category, $page];
    }

    protected function createSavedTest(string $name, string $slug, Page $page, int $questionCount): SavedGrammarTest
    {
        $test = SavedGrammarTest::create([
            'uuid' => (string) Str::uuid(),
            'name' => $name,
            'slug' => $slug,
            'description' => null,
            'filters' => [
                'levels' => ['A2', 'B1'],
                'num_questions' => $questionCount,
                'prompt_generator' => [
                    'source_type' => 'theory_page',
                    'theory_page_id' => $page->id,
                    'theory_page_ids' => [$page->id],
                    'theory_page' => [
                        'id' => $page->id,
                        'slug' => $page->slug,
                        'title' => $page->title,
                    ],
                ],
            ],
        ]);

        for ($index = 1; $index <= $questionCount; $index++) {
            $test->questionLinks()->create([
                'question_uuid' => (string) Str::uuid(),
                'position' => $index,
            ]);
        }

        return $test->fresh();
    }
}
