<?php

namespace Tests\Feature;

use App\Models\Page;
use App\Models\PageCategory;
use App\Services\AutoGeneratedTestService;
use App\Services\SavedTestResolver;
use App\Services\TheoryPagePromptLinkedTestsService;
use Database\Seeders\Page_V3\BasicGrammar\BasicGrammarCategorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\VerbToBe\ThereIsThereAreTheorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\VerbToBe\VerbToBeCategorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\VerbToBe\VerbToBeFutureTheorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\VerbToBe\VerbToBeNegativesTheorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\VerbToBe\VerbToBePastTheorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\VerbToBe\VerbToBePresentTheorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\VerbToBe\VerbToBeQuestionsTheorySeeder;
use Database\Seeders\V3\AI\Copilot\Opus46\ThereIsThereAreV3QuestionsOnlySeeder;
use Database\Seeders\V3\AI\Copilot\Opus46\VerbToBeFutureV3QuestionsOnlySeeder;
use Database\Seeders\V3\AI\Copilot\Opus46\VerbToBeNegativesV3QuestionsOnlySeeder;
use Database\Seeders\V3\AI\Copilot\Opus46\VerbToBePastFormsV3QuestionsOnlySeeder;
use Database\Seeders\V3\AI\Copilot\Opus46\VerbToBePresentFormsV3QuestionsOnlySeeder;
use Database\Seeders\V3\AI\Copilot\Opus46\VerbToBeQuestionsAndShortAnswersV3QuestionsOnlySeeder;
use Database\Seeders\V3\Polyglot\PolyglotPastSimpleToBeLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotThereIsThereAreLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotToBeLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotThereIsThereAreAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotVerbToBeFutureAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotVerbToBeNegativesAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotVerbToBePastAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotVerbToBePresentAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotVerbToBeQuestionsAllLevelsLessonSeeder;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Tests\Support\RebuildsComposeTestSchema;
use Tests\TestCase;

class VerbToBeSectionMixedCardsTest extends TestCase
{
    use RebuildsComposeTestSchema;

    private const LEVEL_PAIRS = [
        ['A1', 'A2'],
        ['A2', 'B1'],
        ['B1', 'B2'],
        ['B2', 'C1'],
        ['C1', 'C2'],
    ];

    protected function setUp(): void
    {
        parent::setUp();

        config([
            'coming-soon.enabled' => false,
            'tests.tech_info_enabled' => false,
        ]);

        $this->rebuildComposeTestSchema();
        $this->augmentTheorySchema();
    }

    public function test_verb_to_be_lesson_pages_build_five_mixed_pair_cards_from_only_page_local_seeders(): void
    {
        $this->seedVerbToBeTheoryPages();
        $this->seedVerbToBeSectionSeeders();

        $service = app(TheoryPagePromptLinkedTestsService::class);
        $cases = [
            'verb-to-be-present' => [
                'route_category' => 'verb-to-be',
                'seeders' => [
                    VerbToBePresentFormsV3QuestionsOnlySeeder::class,
                    PolyglotVerbToBePresentAllLevelsLessonSeeder::class,
                ],
            ],
            'verb-to-be-negatives' => [
                'route_category' => 'verb-to-be',
                'seeders' => [
                    VerbToBeNegativesV3QuestionsOnlySeeder::class,
                    PolyglotVerbToBeNegativesAllLevelsLessonSeeder::class,
                ],
            ],
            'verb-to-be-questions' => [
                'route_category' => 'verb-to-be',
                'seeders' => [
                    VerbToBeQuestionsAndShortAnswersV3QuestionsOnlySeeder::class,
                    PolyglotVerbToBeQuestionsAllLevelsLessonSeeder::class,
                ],
            ],
            'verb-to-be-past' => [
                'route_category' => 'verb-to-be',
                'seeders' => [
                    VerbToBePastFormsV3QuestionsOnlySeeder::class,
                    PolyglotVerbToBePastAllLevelsLessonSeeder::class,
                ],
            ],
            'verb-to-be-future' => [
                'route_category' => 'verb-to-be',
                'seeders' => [
                    VerbToBeFutureV3QuestionsOnlySeeder::class,
                    PolyglotVerbToBeFutureAllLevelsLessonSeeder::class,
                ],
            ],
            'there-is-there-are' => [
                'route_category' => 'verb-to-be',
                'seeders' => [
                    ThereIsThereAreV3QuestionsOnlySeeder::class,
                    PolyglotThereIsThereAreAllLevelsLessonSeeder::class,
                ],
            ],
        ];

        foreach ($cases as $slug => $case) {
            $page = Page::query()->where('slug', $slug)->firstOrFail();
            $tests = $service->buildForPage($page);

            $this->assertCount(2, $tests, $slug);

            $directTest = $tests->first(fn ($test) => ! method_exists($test, 'isVirtual') || ! $test->isVirtual());
            $mixedTest = $tests->firstWhere('slug', 'theory-page-' . $page->id . '-mixed-a1-c2');

            $this->assertNotNull($directTest, $slug);
            $this->assertNotNull($mixedTest, $slug);

            $directFilters = $directTest->filters ?? [];
            $mixedFilters = $mixedTest->filters ?? [];

            $this->assertSame('polyglot-theory-pages', $directFilters['course_slug'] ?? null, $slug);
            $this->assertSame([$case['seeders'][1]], array_values($directFilters['seeder_classes'] ?? []), $slug);
            $this->assertTrue($mixedTest->isVirtual(), $slug);
            $this->assertTrue(($mixedFilters['__meta']['aggregated_theory_page_test'] ?? false), $slug);
            $this->assertTrue(($mixedFilters['__meta']['theory_page_mixed_all_levels_test'] ?? false), $slug);
            $this->assertTrue(($mixedFilters['__meta']['theory_page_mixed_polyglot_test'] ?? false), $slug);
            $this->assertSame(['A1', 'A2', 'B1', 'B2', 'C1', 'C2'], $mixedFilters['levels'] ?? [], $slug);
            $mixedSeederClasses = collect($mixedFilters['seeder_classes'] ?? [])->values();
            foreach ($case['seeders'] as $expectedSeeder) {
                $this->assertTrue($mixedSeederClasses->contains($expectedSeeder), $slug . ' ' . $expectedSeeder);
            }

            $response = $this->get(route('theory.show', [$case['route_category'], $slug]));
            $response->assertOk();
            $response->assertViewHas('topicTests', function ($topicTests) use ($case, $page) {
                $topicTests = collect($topicTests);
                $directTest = $topicTests->first(fn ($test) => ! method_exists($test, 'isVirtual') || ! $test->isVirtual());
                $mixedTest = $topicTests->firstWhere('slug', 'theory-page-' . $page->id . '-mixed-a1-c2');
                $directFilters = $directTest?->filters ?? [];
                $mixedFilters = $mixedTest?->filters ?? [];

                return $topicTests->count() === 2
                    && ($directFilters['course_slug'] ?? null) === 'polyglot-theory-pages'
                    && array_values($directFilters['seeder_classes'] ?? []) === [$case['seeders'][1]]
                    && ($mixedFilters['__meta']['theory_page_mixed_all_levels_test'] ?? false) === true
                    && ($mixedFilters['__meta']['theory_page_mixed_polyglot_test'] ?? false) === true
                    && collect($case['seeders'])
                        ->diff(collect($mixedFilters['seeder_classes'] ?? []))
                        ->isEmpty();
            });
        }
    }

    public function test_verb_to_be_category_builds_all_five_level_pair_cards(): void
    {
        $this->seedVerbToBeTheoryPages();
        $this->seed([
            VerbToBePresentFormsV3QuestionsOnlySeeder::class,
            VerbToBeNegativesV3QuestionsOnlySeeder::class,
            VerbToBeQuestionsAndShortAnswersV3QuestionsOnlySeeder::class,
            VerbToBePastFormsV3QuestionsOnlySeeder::class,
            VerbToBeFutureV3QuestionsOnlySeeder::class,
            ThereIsThereAreV3QuestionsOnlySeeder::class,
        ]);

        $category = PageCategory::query()->where('slug', 'verb-to-be')->firstOrFail();
        $tests = app(AutoGeneratedTestService::class)->generateTests($category->tags()->get(), $category->title);

        $this->assertCount(5, $tests);
        $this->assertSame(self::LEVEL_PAIRS, $tests->map(fn ($test) => $test->filters['levels'] ?? [])->values()->all());
    }

    public function test_verb_to_be_mixed_virtual_filters_keep_flag_two_v3_questions_in_resolved_test(): void
    {
        $this->seedVerbToBeTheoryPages();
        $this->seedVerbToBeSectionSeeders();

        $page = Page::query()->where('slug', 'verb-to-be-past')->firstOrFail();
        $test = app(TheoryPagePromptLinkedTestsService::class)
            ->buildForPage($page)
            ->firstWhere('slug', 'theory-page-' . $page->id . '-mixed-a1-c2');

        $this->assertNotNull($test);

        $filters = $test->filters ?? [];
        $filters['num_questions'] = 72;
        $filters['randomize_filtered'] = false;

        $query = http_build_query([
            'filters' => base64_encode((string) json_encode($filters, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)),
            'name' => $test->name,
        ]);

        $request = \Illuminate\Http\Request::create('/test/' . $test->slug . '?' . $query, 'GET');
        $this->app->instance('request', $request);

        $resolved = app(SavedTestResolver::class)->resolve($test->slug);
        $questions = $resolved->preloadedQuestions ?? collect();

        $this->assertTrue($questions->pluck('seeder')->contains(VerbToBePastFormsV3QuestionsOnlySeeder::class));
        $this->assertTrue($questions->pluck('seeder')->contains(PolyglotVerbToBePastAllLevelsLessonSeeder::class));
        $this->assertTrue($questions->contains(fn ($question) => (string) $question->type === '0'));
        $this->assertTrue($questions->contains(fn ($question) => (string) $question->type === '4'));
    }

    protected function seedVerbToBeTheoryPages(): void
    {
        $this->seed(BasicGrammarCategorySeeder::class);
        $this->seed(VerbToBeCategorySeeder::class);
        $this->seed(VerbToBePresentTheorySeeder::class);
        $this->seed(VerbToBeNegativesTheorySeeder::class);
        $this->seed(VerbToBeQuestionsTheorySeeder::class);
        $this->seed(VerbToBePastTheorySeeder::class);
        $this->seed(VerbToBeFutureTheorySeeder::class);
        $this->seed(ThereIsThereAreTheorySeeder::class);
    }

    protected function seedVerbToBeSectionSeeders(): void
    {
        $this->seed([
            VerbToBePresentFormsV3QuestionsOnlySeeder::class,
            VerbToBeNegativesV3QuestionsOnlySeeder::class,
            VerbToBeQuestionsAndShortAnswersV3QuestionsOnlySeeder::class,
            VerbToBePastFormsV3QuestionsOnlySeeder::class,
            VerbToBeFutureV3QuestionsOnlySeeder::class,
            ThereIsThereAreV3QuestionsOnlySeeder::class,
            PolyglotToBeLessonSeeder::class,
            PolyglotPastSimpleToBeLessonSeeder::class,
            PolyglotThereIsThereAreLessonSeeder::class,
            PolyglotVerbToBePresentAllLevelsLessonSeeder::class,
            PolyglotVerbToBeNegativesAllLevelsLessonSeeder::class,
            PolyglotVerbToBeQuestionsAllLevelsLessonSeeder::class,
            PolyglotVerbToBePastAllLevelsLessonSeeder::class,
            PolyglotVerbToBeFutureAllLevelsLessonSeeder::class,
            PolyglotThereIsThereAreAllLevelsLessonSeeder::class,
        ]);
    }

    protected function augmentTheorySchema(): void
    {
        Schema::disableForeignKeyConstraints();
        foreach (['site_tree_items', 'site_tree_variants', 'page_category_tag', 'page_tag', 'tag_text_block', 'text_blocks'] as $table) {
            Schema::dropIfExists($table);
        }
        Schema::enableForeignKeyConstraints();

        Schema::create('text_blocks', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->nullable()->unique();
            $table->unsignedBigInteger('page_id')->nullable();
            $table->unsignedBigInteger('page_category_id')->nullable();
            $table->string('locale', 8)->nullable();
            $table->string('type')->nullable();
            $table->string('column')->nullable();
            $table->string('heading')->nullable();
            $table->string('css_class')->nullable();
            $table->integer('sort_order')->default(0);
            $table->text('body')->nullable();
            $table->string('level')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('page_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('page_id');
            $table->timestamps();
            $table->unique(['tag_id', 'page_id']);
        });

        Schema::create('page_category_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('page_category_id');
            $table->timestamps();
            $table->unique(['tag_id', 'page_category_id']);
        });

        Schema::create('tag_text_block', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('text_block_id');
            $table->timestamps();
            $table->unique(['tag_id', 'text_block_id']);
        });

        Schema::create('site_tree_variants', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->nullable();
            $table->boolean('is_base')->default(false);
            $table->timestamps();
        });

        Schema::create('site_tree_items', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('variant_id')->nullable();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('title')->nullable();
            $table->string('linked_page_title')->nullable();
            $table->string('linked_page_url')->nullable();
            $table->string('link_method')->nullable();
            $table->unsignedInteger('level')->default(0);
            $table->boolean('is_checked')->default(false);
            $table->unsignedInteger('sort_order')->default(0);
            $table->timestamps();
        });
    }
}
