<?php

namespace Tests\Feature;

use App\Models\Page;
use App\Models\PageCategory;
use App\Services\AutoGeneratedTestService;
use App\Services\TheoryPagePromptLinkedTestsService;
use Database\Seeders\Page_V3\Articles\SomeAny\SomeAnyCategorySeeder;
use Database\Seeders\Page_V3\Articles\SomeAny\SomeAnyThingsTheorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\BasicGrammarCategorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\WordOrder\BasicWordOrderTheorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\WordOrder\WordOrderCategorySeeder;
use Database\Seeders\V3\AI\Copilot\Opus46\BasicWordOrderV3QuestionsOnlySeeder as BasicWordOrderOpus46Seeder;
use Database\Seeders\V3\AI\Copilot\Sonate\BasicWordOrderV3QuestionsOnlySeeder as BasicWordOrderSonateSeeder;
use Database\Seeders\V3\Polyglot\PolyglotSomeAnyLessonSeeder;
use Database\Seeders\V3\WordOrderAllLevelsV3Seeder;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Tests\Support\RebuildsComposeTestSchema;
use Tests\TestCase;

class WordOrderSomeAnySmokeTest extends TestCase
{
    use RebuildsComposeTestSchema;

    private const LEVEL_PAIRS = [
        ['A1', 'A2'],
        ['A2', 'B1'],
        ['B1', 'B2'],
        ['B2', 'C1'],
        ['C1', 'C2'],
    ];

    protected function setUp(): void
    {
        parent::setUp();

        config([
            'coming-soon.enabled' => false,
            'tests.tech_info_enabled' => false,
        ]);

        $this->rebuildComposeTestSchema();
        $this->augmentTheorySchema();
    }

    public function test_word_order_basic_page_keeps_five_aggregated_v3_pair_cards(): void
    {
        $this->seed(BasicGrammarCategorySeeder::class);
        $this->seed(WordOrderCategorySeeder::class);
        $this->seed(BasicWordOrderTheorySeeder::class);
        $this->seed(WordOrderAllLevelsV3Seeder::class);
        $this->seed(BasicWordOrderOpus46Seeder::class);
        $this->seed(BasicWordOrderSonateSeeder::class);

        $page = Page::query()->where('slug', 'theory-basic-word-order')->firstOrFail();
        $tests = app(TheoryPagePromptLinkedTestsService::class)->buildForPage($page);

        $this->assertCount(5, $tests);
        $this->assertSame(self::LEVEL_PAIRS, $tests->map(fn ($test) => $test->filters['levels'] ?? [])->values()->all());

        foreach ($tests as $test) {
            $filters = $test->filters ?? [];

            $this->assertTrue($test->isVirtual());
            $this->assertTrue(($filters['__meta']['aggregated_theory_page_test'] ?? false));
            $this->assertFalse(($filters['__meta']['theory_page_mixed_polyglot_test'] ?? false));
            $this->assertSame(
                collect([
                    BasicWordOrderOpus46Seeder::class,
                    BasicWordOrderSonateSeeder::class,
                ])->sort()->values()->all(),
                collect($filters['seeder_classes'] ?? [])->sort()->values()->all()
            );
        }

        $response = $this->get(route('theory.show', ['word-order', 'theory-basic-word-order']));
        $response->assertOk();
        $response->assertViewHas('topicTests', function ($topicTests) {
            return collect($topicTests)->count() === 5
                && collect($topicTests)->every(function ($test) {
                    $filters = $test->filters ?? [];

                    return ($filters['__meta']['aggregated_theory_page_test'] ?? false) === true
                        && ($filters['__meta']['theory_page_mixed_polyglot_test'] ?? false) === false;
                });
        });

        $category = PageCategory::query()->where('slug', 'word-order')->firstOrFail();
        $categoryTests = app(AutoGeneratedTestService::class)->generateTests($category->tags()->get(), $category->title);

        $this->assertCount(5, $categoryTests);
        $this->assertSame(self::LEVEL_PAIRS, $categoryTests->map(fn ($test) => $test->filters['levels'] ?? [])->values()->all());
    }

    public function test_some_any_things_page_keeps_direct_polyglot_card_and_category_has_no_cards(): void
    {
        $this->seed(SomeAnyCategorySeeder::class);
        $this->seed(SomeAnyThingsTheorySeeder::class);
        $this->seed(PolyglotSomeAnyLessonSeeder::class);

        $response = $this->get(route('theory.show', ['some-any', 'theory-some-any-things']));

        $response->assertOk();
        $response->assertViewHas('topicTests', function ($topicTests) {
            if (collect($topicTests)->count() !== 1) {
                return false;
            }

            $test = collect($topicTests)->first();
            $filters = $test->filters ?? [];

            return $test->slug === 'polyglot-some-any-a1'
                && ($filters['lesson_type'] ?? null) === 'polyglot'
                && ($filters['mode'] ?? null) === 'compose_tokens'
                && collect($filters['seeder_classes'] ?? [])->values()->all() === [PolyglotSomeAnyLessonSeeder::class]
                && (! method_exists($test, 'isVirtual') || ! $test->isVirtual());
        });

        $category = PageCategory::query()->where('slug', 'some-any')->firstOrFail();
        $categoryTests = app(AutoGeneratedTestService::class)->generateTests($category->tags()->get(), $category->title);

        $this->assertCount(0, $categoryTests);

        $categoryResponse = $this->get(route('theory.category', ['some-any']));
        $categoryResponse->assertOk();
        $categoryResponse->assertDontSee('Тести по темі');
    }

    protected function augmentTheorySchema(): void
    {
        Schema::create('text_blocks', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->nullable()->unique();
            $table->unsignedBigInteger('page_id')->nullable();
            $table->unsignedBigInteger('page_category_id')->nullable();
            $table->string('locale', 8)->nullable();
            $table->string('type')->nullable();
            $table->string('column')->nullable();
            $table->string('heading')->nullable();
            $table->string('css_class')->nullable();
            $table->integer('sort_order')->default(0);
            $table->text('body')->nullable();
            $table->string('level')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('page_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('page_id');
            $table->timestamps();
            $table->unique(['tag_id', 'page_id']);
        });

        Schema::create('page_category_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('page_category_id');
            $table->timestamps();
            $table->unique(['tag_id', 'page_category_id']);
        });

        Schema::create('tag_text_block', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('text_block_id');
            $table->timestamps();
            $table->unique(['tag_id', 'text_block_id']);
        });

        Schema::create('site_tree_variants', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->nullable();
            $table->boolean('is_base')->default(false);
            $table->timestamps();
        });

        Schema::create('site_tree_items', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('variant_id')->nullable();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('title')->nullable();
            $table->string('linked_page_title')->nullable();
            $table->string('linked_page_url')->nullable();
            $table->string('link_method')->nullable();
            $table->unsignedInteger('level')->default(0);
            $table->boolean('is_checked')->default(false);
            $table->unsignedInteger('sort_order')->default(0);
            $table->timestamps();
        });
    }
}
