<?php

namespace Tests\Feature;

use App\Models\Page;
use App\Models\PageCategory;
use App\Services\AutoGeneratedTestService;
use App\Services\SavedTestResolver;
use App\Services\TheoryPagePromptLinkedTestsService;
use Database\Seeders\Page_V3\BasicGrammar\BasicGrammarCategorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\WordOrder\AdvancedWordOrderEmphasisTheorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\WordOrder\BasicWordOrderTheorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\WordOrder\WordOrderAdverbsAdverbialsTheorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\WordOrder\WordOrderCategorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\WordOrder\WordOrderQuestionsNegativesTheorySeeder;
use Database\Seeders\Page_V3\BasicGrammar\WordOrder\WordOrderVerbsObjectsTheorySeeder;
use Database\Seeders\V3\AdvancedWordOrderEmphasisAllLevelsV3Seeder;
use Database\Seeders\V3\BasicWordOrderAllLevelsV3Seeder;
use Database\Seeders\V3\Polyglot\PolyglotAdvancedWordOrderEmphasisAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotBasicWordOrderAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotWordOrderAdverbsAdverbialsAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotWordOrderQuestionsNegativesAllLevelsLessonSeeder;
use Database\Seeders\V3\Polyglot\PolyglotWordOrderVerbsObjectsAllLevelsLessonSeeder;
use Database\Seeders\V3\WordOrderAdverbsAdverbialsAllLevelsV3Seeder;
use Database\Seeders\V3\WordOrderAllLevelsV3Seeder;
use Database\Seeders\V3\WordOrderQuestionsNegativesAllLevelsV3Seeder;
use Database\Seeders\V3\WordOrderVerbsObjectsAllLevelsV3Seeder;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Tests\Support\RebuildsComposeTestSchema;
use Tests\TestCase;

class WordOrderSectionMixedCardsTest extends TestCase
{
    use RebuildsComposeTestSchema;

    private const LEVEL_PAIRS = [
        ['A1', 'A2'],
        ['A2', 'B1'],
        ['B1', 'B2'],
        ['B2', 'C1'],
        ['C1', 'C2'],
    ];

    protected function setUp(): void
    {
        parent::setUp();

        config([
            'coming-soon.enabled' => false,
            'tests.tech_info_enabled' => false,
        ]);

        $this->rebuildComposeTestSchema();
        $this->augmentTheorySchema();
    }

    public function test_word_order_lesson_pages_build_five_mixed_pair_cards_from_only_page_local_seeders(): void
    {
        $this->seedWordOrderTheoryPages();
        $this->seedWordOrderSectionSeeders();

        $service = app(TheoryPagePromptLinkedTestsService::class);
        $cases = [
            'theory-basic-word-order' => [
                'route_category' => 'word-order',
                'seeders' => [
                    BasicWordOrderAllLevelsV3Seeder::class,
                    PolyglotBasicWordOrderAllLevelsLessonSeeder::class,
                ],
            ],
            'theory-word-order-questions-negatives' => [
                'route_category' => 'word-order',
                'seeders' => [
                    WordOrderQuestionsNegativesAllLevelsV3Seeder::class,
                    PolyglotWordOrderQuestionsNegativesAllLevelsLessonSeeder::class,
                ],
            ],
            'theory-word-order-adverbs-adverbials' => [
                'route_category' => 'word-order',
                'seeders' => [
                    WordOrderAdverbsAdverbialsAllLevelsV3Seeder::class,
                    PolyglotWordOrderAdverbsAdverbialsAllLevelsLessonSeeder::class,
                ],
            ],
            'theory-word-order-verbs-objects' => [
                'route_category' => 'word-order',
                'seeders' => [
                    WordOrderVerbsObjectsAllLevelsV3Seeder::class,
                    PolyglotWordOrderVerbsObjectsAllLevelsLessonSeeder::class,
                ],
            ],
            'theory-advanced-word-order-emphasis' => [
                'route_category' => 'word-order',
                'seeders' => [
                    AdvancedWordOrderEmphasisAllLevelsV3Seeder::class,
                    PolyglotAdvancedWordOrderEmphasisAllLevelsLessonSeeder::class,
                ],
            ],
        ];

        foreach ($cases as $slug => $case) {
            $page = Page::query()->where('slug', $slug)->firstOrFail();
            $tests = $service->buildForPage($page);

            $this->assertCount(5, $tests, $slug);
            $this->assertSame(self::LEVEL_PAIRS, $tests->map(fn ($test) => $test->filters['levels'] ?? [])->values()->all(), $slug);

            foreach ($tests as $test) {
                $filters = $test->filters ?? [];

                $this->assertTrue($test->isVirtual(), $slug);
                $this->assertTrue(str_starts_with((string) $test->slug, 'theory-page-' . $page->id . '-'), $slug);
                $this->assertTrue(($filters['__meta']['aggregated_theory_page_test'] ?? false), $slug);
                $this->assertTrue(($filters['__meta']['theory_page_mixed_polyglot_test'] ?? false), $slug);
                $this->assertSame(
                    collect($case['seeders'])->sort()->values()->all(),
                    collect($filters['seeder_classes'] ?? [])->sort()->values()->all(),
                    $slug
                );
                $this->assertCount(2, $filters['seeder_classes'] ?? [], $slug);
                $this->assertSame(15, $filters['num_questions'] ?? null, $slug);
                $this->assertGreaterThanOrEqual(48, (int) $test->getAttribute('total_questions_available'), $slug);
            }

            $response = $this->get(route('theory.show', [$case['route_category'], $slug]));
            $response->assertOk();
            $response->assertViewHas('topicTests', function ($topicTests) use ($case, $page) {
                return collect($topicTests)->count() === 5
                    && collect($topicTests)->every(function ($test) use ($case, $page) {
                        $filters = $test->filters ?? [];

                        return str_starts_with((string) ($test->slug ?? ''), 'theory-page-' . $page->id . '-')
                            && ($filters['__meta']['theory_page_mixed_polyglot_test'] ?? false) === true
                            && collect($filters['seeder_classes'] ?? [])->sort()->values()->all() === collect($case['seeders'])->sort()->values()->all();
                    });
            });
        }
    }

    public function test_word_order_category_builds_all_five_level_pair_cards(): void
    {
        $this->seedWordOrderTheoryPages();
        $this->seed([
            WordOrderAllLevelsV3Seeder::class,
            BasicWordOrderAllLevelsV3Seeder::class,
            WordOrderQuestionsNegativesAllLevelsV3Seeder::class,
            WordOrderAdverbsAdverbialsAllLevelsV3Seeder::class,
            WordOrderVerbsObjectsAllLevelsV3Seeder::class,
            AdvancedWordOrderEmphasisAllLevelsV3Seeder::class,
            PolyglotBasicWordOrderAllLevelsLessonSeeder::class,
            PolyglotWordOrderQuestionsNegativesAllLevelsLessonSeeder::class,
            PolyglotWordOrderAdverbsAdverbialsAllLevelsLessonSeeder::class,
            PolyglotWordOrderVerbsObjectsAllLevelsLessonSeeder::class,
            PolyglotAdvancedWordOrderEmphasisAllLevelsLessonSeeder::class,
        ]);

        $category = PageCategory::query()->where('slug', 'word-order')->firstOrFail();
        $tests = app(AutoGeneratedTestService::class)->generateTests($category->tags()->get(), $category->title);

        $this->assertCount(5, $tests);
        $this->assertSame(self::LEVEL_PAIRS, $tests->map(fn ($test) => $test->filters['levels'] ?? [])->values()->all());
    }

    public function test_word_order_mixed_virtual_filters_keep_flag_two_v3_questions_in_resolved_test(): void
    {
        $this->seedWordOrderTheoryPages();
        $this->seedWordOrderSectionSeeders();

        $page = Page::query()->where('slug', 'theory-word-order-verbs-objects')->firstOrFail();
        $test = app(TheoryPagePromptLinkedTestsService::class)
            ->buildForPage($page)
            ->firstWhere('slug', 'theory-page-' . $page->id . '-a1-a2');

        $this->assertNotNull($test);

        $filters = $test->filters ?? [];
        $filters['num_questions'] = 72;
        $filters['randomize_filtered'] = false;

        $query = http_build_query([
            'filters' => base64_encode((string) json_encode($filters, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)),
            'name' => $test->name,
        ]);

        $request = \Illuminate\Http\Request::create('/test/' . $test->slug . '?' . $query, 'GET');
        $this->app->instance('request', $request);

        $resolved = app(SavedTestResolver::class)->resolve($test->slug);
        $questions = $resolved->preloadedQuestions ?? collect();

        $this->assertTrue($questions->pluck('seeder')->contains(WordOrderVerbsObjectsAllLevelsV3Seeder::class));
        $this->assertTrue($questions->pluck('seeder')->contains(PolyglotWordOrderVerbsObjectsAllLevelsLessonSeeder::class));
        $this->assertTrue($questions->contains(fn ($question) => (string) $question->type === '0'));
        $this->assertTrue($questions->contains(fn ($question) => (string) $question->type === '4'));
    }

    protected function seedWordOrderTheoryPages(): void
    {
        $this->seed(BasicGrammarCategorySeeder::class);
        $this->seed(WordOrderCategorySeeder::class);
        $this->seed(BasicWordOrderTheorySeeder::class);
        $this->seed(WordOrderQuestionsNegativesTheorySeeder::class);
        $this->seed(WordOrderAdverbsAdverbialsTheorySeeder::class);
        $this->seed(WordOrderVerbsObjectsTheorySeeder::class);
        $this->seed(AdvancedWordOrderEmphasisTheorySeeder::class);
    }

    protected function seedWordOrderSectionSeeders(): void
    {
        $this->seed([
            BasicWordOrderAllLevelsV3Seeder::class,
            WordOrderQuestionsNegativesAllLevelsV3Seeder::class,
            WordOrderAdverbsAdverbialsAllLevelsV3Seeder::class,
            WordOrderVerbsObjectsAllLevelsV3Seeder::class,
            AdvancedWordOrderEmphasisAllLevelsV3Seeder::class,
            PolyglotBasicWordOrderAllLevelsLessonSeeder::class,
            PolyglotWordOrderQuestionsNegativesAllLevelsLessonSeeder::class,
            PolyglotWordOrderAdverbsAdverbialsAllLevelsLessonSeeder::class,
            PolyglotWordOrderVerbsObjectsAllLevelsLessonSeeder::class,
            PolyglotAdvancedWordOrderEmphasisAllLevelsLessonSeeder::class,
        ]);
    }

    protected function augmentTheorySchema(): void
    {
        Schema::create('text_blocks', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->nullable()->unique();
            $table->unsignedBigInteger('page_id')->nullable();
            $table->unsignedBigInteger('page_category_id')->nullable();
            $table->string('locale', 8)->nullable();
            $table->string('type')->nullable();
            $table->string('column')->nullable();
            $table->string('heading')->nullable();
            $table->string('css_class')->nullable();
            $table->integer('sort_order')->default(0);
            $table->text('body')->nullable();
            $table->string('level')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('page_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('page_id');
            $table->timestamps();
            $table->unique(['tag_id', 'page_id']);
        });

        Schema::create('page_category_tag', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('page_category_id');
            $table->timestamps();
            $table->unique(['tag_id', 'page_category_id']);
        });

        Schema::create('tag_text_block', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('tag_id');
            $table->unsignedBigInteger('text_block_id');
            $table->timestamps();
            $table->unique(['tag_id', 'text_block_id']);
        });

        Schema::create('site_tree_variants', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->nullable();
            $table->boolean('is_base')->default(false);
            $table->timestamps();
        });

        Schema::create('site_tree_items', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('variant_id')->nullable();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('title')->nullable();
            $table->string('linked_page_title')->nullable();
            $table->string('linked_page_url')->nullable();
            $table->string('link_method')->nullable();
            $table->unsignedInteger('level')->default(0);
            $table->boolean('is_checked')->default(false);
            $table->unsignedInteger('sort_order')->default(0);
            $table->timestamps();
        });
    }
}
