<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotModalPerfectDeductionAndRegretB2LessonSeeder as V3PolyglotModalPerfectDeductionAndRegretB2LessonSeeder;

class PolyglotModalPerfectDeductionAndRegretB2LessonSeeder extends V3PolyglotModalPerfectDeductionAndRegretB2LessonSeeder
{
}
