<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotArgumentationAndAcademicToneC2LessonSeeder as V3PolyglotArgumentationAndAcademicToneC2LessonSeeder;

class PolyglotArgumentationAndAcademicToneC2LessonSeeder extends V3PolyglotArgumentationAndAcademicToneC2LessonSeeder
{
}
