<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotMixedConditionalsBasicsB2LessonSeeder as V3PolyglotMixedConditionalsBasicsB2LessonSeeder;

class PolyglotMixedConditionalsBasicsB2LessonSeeder extends V3PolyglotMixedConditionalsBasicsB2LessonSeeder
{
}
