<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotConditionalAlternativesAndNuanceC2LessonSeeder as V3PolyglotConditionalAlternativesAndNuanceC2LessonSeeder;

class PolyglotConditionalAlternativesAndNuanceC2LessonSeeder extends V3PolyglotConditionalAlternativesAndNuanceC2LessonSeeder
{
}
