<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotAdvancedArticleAndQuantifierNuanceC1LessonSeeder as V3PolyglotAdvancedArticleAndQuantifierNuanceC1LessonSeeder;

class PolyglotAdvancedArticleAndQuantifierNuanceC1LessonSeeder extends V3PolyglotAdvancedArticleAndQuantifierNuanceC1LessonSeeder
{
}
