<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotPresentPerfectContinuousBasicsLessonSeeder as V3PolyglotPresentPerfectContinuousBasicsLessonSeeder;

class PolyglotPresentPerfectContinuousBasicsLessonSeeder extends V3PolyglotPresentPerfectContinuousBasicsLessonSeeder
{
}
