<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotHedgingAndCautiousLanguageBasicsB2LessonSeeder as V3PolyglotHedgingAndCautiousLanguageBasicsB2LessonSeeder;

class PolyglotHedgingAndCautiousLanguageBasicsB2LessonSeeder extends V3PolyglotHedgingAndCautiousLanguageBasicsB2LessonSeeder
{
}
