<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotFormalRegisterAndNominalisationBasicsB2LessonSeeder as V3PolyglotFormalRegisterAndNominalisationBasicsB2LessonSeeder;

class PolyglotFormalRegisterAndNominalisationBasicsB2LessonSeeder extends V3PolyglotFormalRegisterAndNominalisationBasicsB2LessonSeeder
{
}
