<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotAdvancedCollocationAndLexicalChoiceC2LessonSeeder as V3PolyglotAdvancedCollocationAndLexicalChoiceC2LessonSeeder;

class PolyglotAdvancedCollocationAndLexicalChoiceC2LessonSeeder extends V3PolyglotAdvancedCollocationAndLexicalChoiceC2LessonSeeder
{
}
