<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotNominalisationFormalRegisterC1LessonSeeder as V3PolyglotNominalisationFormalRegisterC1LessonSeeder;

class PolyglotNominalisationFormalRegisterC1LessonSeeder extends V3PolyglotNominalisationFormalRegisterC1LessonSeeder
{
}
