<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotNonDefiningRelativeClausesLessonSeeder as V3PolyglotNonDefiningRelativeClausesLessonSeeder;

class PolyglotNonDefiningRelativeClausesLessonSeeder extends V3PolyglotNonDefiningRelativeClausesLessonSeeder
{
}
