<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotLinkingWordsReasonResultContrastB2LessonSeeder as V3PolyglotLinkingWordsReasonResultContrastB2LessonSeeder;

class PolyglotLinkingWordsReasonResultContrastB2LessonSeeder extends V3PolyglotLinkingWordsReasonResultContrastB2LessonSeeder
{
}
