<?php

namespace Database\Seeders\V2\Polyglot;

use Database\Seeders\V3\Polyglot\PolyglotPresentPerfectTimeExpressionsLessonSeeder as V3PolyglotPresentPerfectTimeExpressionsLessonSeeder;

class PolyglotPresentPerfectTimeExpressionsLessonSeeder extends V3PolyglotPresentPerfectTimeExpressionsLessonSeeder
{
}
