<?php

namespace Tests\Feature\Theory;

use App\Services\AutoGeneratedTestService;
use App\Services\Theory\TextBlockToQuestionsMatcherService;
use App\Services\TheoryPagePromptLinkedTestsService;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Mockery;
use Tests\Support\TheoryRouteMatrix;
use Tests\TestCase;

abstract class SeededTheoryTestCase extends TestCase
{
    private static bool $fixtureBootstrapped = false;

    private static ?string $databasePath = null;

    protected function setUp(): void
    {
        parent::setUp();

        $this->usePersistentSqliteDatabase();
        $this->prepareCompiledViews();
        $this->bindTheoryServiceMocks();

        if (! self::$fixtureBootstrapped) {
            $this->rebuildMinimalSchema();
            $this->seedTheoryFixture();
            self::$fixtureBootstrapped = true;
        }
    }

    protected function tearDown(): void
    {
        Mockery::close();

        parent::tearDown();
    }

    protected function assertNoRawTranslationKeys(string $html): void
    {
        $this->assertDoesNotMatchRegularExpression(
            '/(?:public|tests)\.[A-Za-z0-9_.-]+/',
            $html
        );
    }

    protected function assertNoCyrillicInH1(string $html): void
    {
        $this->assertDoesNotMatchRegularExpression('/\p{Cyrillic}/u', $this->extractFirstHeading($html, 'h1'));
    }

    protected function extractFirstHeading(string $html, string $tag = 'h1'): string
    {
        $pattern = sprintf('~<%1$s\b[^>]*>(.*?)</%1$s>~is', preg_quote($tag, '~'));

        if (! preg_match($pattern, $html, $matches)) {
            $this->fail(sprintf('Unable to find <%s> in response HTML.', $tag));
        }

        return $this->normalizeText(html_entity_decode(strip_tags($matches[1]), ENT_QUOTES | ENT_HTML5));
    }

    protected function normalizeText(string $value): string
    {
        return trim((string) preg_replace('/\s+/u', ' ', $value));
    }

    private function usePersistentSqliteDatabase(): void
    {
        $directory = storage_path('framework/testing');

        if (! is_dir($directory)) {
            mkdir($directory, 0777, true);
        }

        self::$databasePath ??= $directory . DIRECTORY_SEPARATOR . sprintf(
            'theory-suite-%s.sqlite',
            getmypid() ?: uniqid('process-', true)
        );

        if (! file_exists(self::$databasePath)) {
            touch(self::$databasePath);
        }

        config([
            'database.default' => 'sqlite',
            'database.connections.sqlite.database' => self::$databasePath,
            'database.connections.sqlite.foreign_key_constraints' => true,
        ]);

        DB::purge('sqlite');
        DB::reconnect('sqlite');
    }

    private function prepareCompiledViews(): void
    {
        $viewsPath = storage_path('framework/views-theory-tests');

        if (! is_dir($viewsPath)) {
            mkdir($viewsPath, 0777, true);
        }

        config(['view.compiled' => $viewsPath]);
    }

    private function bindTheoryServiceMocks(): void
    {
        $autoGeneratedTests = Mockery::mock(AutoGeneratedTestService::class);
        $autoGeneratedTests
            ->shouldReceive('generateTests')
            ->andReturn(collect());
        $this->app->instance(AutoGeneratedTestService::class, $autoGeneratedTests);

        $promptLinkedTests = Mockery::mock(TheoryPagePromptLinkedTestsService::class);
        $promptLinkedTests
            ->shouldReceive('buildForPage')
            ->andReturn(collect());
        $this->app->instance(TheoryPagePromptLinkedTestsService::class, $promptLinkedTests);

        $textBlockMatcher = Mockery::mock(TextBlockToQuestionsMatcherService::class);
        $textBlockMatcher
            ->shouldReceive('findQuestionsForTextBlocks')
            ->andReturn([]);
        $this->app->instance(TextBlockToQuestionsMatcherService::class, $textBlockMatcher);
    }

    private function rebuildMinimalSchema(): void
    {
        Schema::disableForeignKeyConstraints();

        foreach ([
            'seed_runs',
            'site_tree_items',
            'site_tree_variants',
            'tag_text_block',
            'page_category_tag',
            'page_tag',
            'text_blocks',
            'pages',
            'page_categories',
            'tags',
        ] as $table) {
            Schema::dropIfExists($table);
        }

        Schema::enableForeignKeyConstraints();

        Schema::create('tags', function (Blueprint $table) {
            $table->id();
            $table->string('name')->unique();
            $table->string('category')->nullable();
            $table->timestamps();
        });

        Schema::create('page_categories', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->string('slug')->unique();
            $table->string('language')->nullable();
            $table->string('type')->nullable();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();
        });

        Schema::create('pages', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('page_category_id')->nullable();
            $table->string('slug');
            $table->string('title');
            $table->text('text')->nullable();
            $table->string('type')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();

            $table->unique(['slug', 'type'], 'pages_slug_type_unique');
            $table->index('seeder');
        });

        Schema::create('text_blocks', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->nullable()->unique();
            $table->unsignedBigInteger('page_id')->nullable();
            $table->unsignedBigInteger('page_category_id')->nullable();
            $table->string('locale', 8)->nullable();
            $table->string('type')->nullable();
            $table->string('column')->nullable();
            $table->string('heading')->nullable();
            $table->string('css_class')->nullable();
            $table->unsignedInteger('sort_order')->default(0);
            $table->text('body')->nullable();
            $table->string('level')->nullable();
            $table->string('seeder')->nullable();
            $table->timestamps();

            $table->index('seeder');
        });

        Schema::create('page_tag', function (Blueprint $table) {
            $table->id();
            $table->foreignId('tag_id')->constrained('tags')->cascadeOnDelete();
            $table->foreignId('page_id')->constrained('pages')->cascadeOnDelete();
            $table->unique(['tag_id', 'page_id']);
            $table->timestamps();
        });

        Schema::create('page_category_tag', function (Blueprint $table) {
            $table->id();
            $table->foreignId('tag_id')->constrained('tags')->cascadeOnDelete();
            $table->foreignId('page_category_id')->constrained('page_categories')->cascadeOnDelete();
            $table->unique(['tag_id', 'page_category_id']);
            $table->timestamps();
        });

        Schema::create('tag_text_block', function (Blueprint $table) {
            $table->id();
            $table->foreignId('tag_id')->constrained('tags')->cascadeOnDelete();
            $table->foreignId('text_block_id')->constrained('text_blocks')->cascadeOnDelete();
            $table->unique(['tag_id', 'text_block_id']);
            $table->timestamps();
        });

        Schema::create('site_tree_variants', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->nullable()->unique();
            $table->boolean('is_base')->default(false);
            $table->timestamps();
        });

        Schema::create('site_tree_items', function (Blueprint $table) {
            $table->id();
            $table->foreignId('variant_id')->nullable()->constrained('site_tree_variants')->cascadeOnDelete();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('title');
            $table->string('level')->nullable();
            $table->boolean('is_checked')->default(true);
            $table->unsignedInteger('sort_order')->default(0);
            $table->string('linked_page_title')->nullable();
            $table->string('linked_page_url')->nullable();
            $table->string('link_method')->nullable();
            $table->timestamps();
        });

        Schema::create('seed_runs', function (Blueprint $table) {
            $table->id();
            $table->string('class_name')->unique();
            $table->timestamp('ran_at')->nullable();
        });
    }

    private function seedTheoryFixture(): void
    {
        foreach (TheoryRouteMatrix::fixtureSeederClasses() as $seederClass) {
            app($seederClass)->__invoke();
        }
    }
}
