<?php

/** Independently authored translations of every complete condition, not token substitutions. */
return [
    'Forms' => [
        'A1' => [
            ['До початку вечері я працював уже дві години.', 'Przed rozpoczęciem kolacji pracowałem już od dwóch godzin.'],
            ['Коли приїхав автобус, вони чекали вже десять хвилин.', 'Kiedy przyjechał autobus, czekali już od dziesięciu minut.'],
            ['Коли вчитель зайшов, вона навчалася вже двадцять хвилин.', 'Kiedy nauczyciel wszedł, uczyła się już od dwudziestu minut.'],
            ['До першої зупинки ми їхали автомобілем уже три години.', 'Przed pierwszym postojem jechaliśmy samochodem już od trzech godzin.'],
            ['Перед початком уроку діти вже деякий час тихо розмовляли.', 'Przed rozpoczęciem lekcji dzieci już przez pewien czas cicho rozmawiały.'],
            ['Бен захекався, бо перед цим біг угору.', 'Ben był zdyszany, ponieważ wcześniej biegł pod górę.'],
            ['До обіду Мія вже пів години робила нотатки.', 'Przed obiadem Mia już od pół godziny robiła notatki.'],
            ['Коли я народився, мої батьки жили в тій квартирі вже рік.', 'Kiedy się urodziłem, moi rodzice mieszkali w tamtym mieszkaniu już od roku.'],
            ['Коли згасло світло, я читав уже годину.', 'Kiedy zgasło światło, czytałem już od godziny.'],
            ['До того як тато знайшов ключ, ми шукали його вже десять хвилин.', 'Zanim tata znalazł klucz, szukaliśmy go już od dziesięciu minut.'],
            ['Підлога була мокра, бо Лео перед цим її мив.', 'Podłoga była mokra, ponieważ Leo wcześniej ją mył.'],
            ['До 2020 року Анна знала Лева вже п’ять років; тут описано стан.', 'Do 2020 roku Anna znała Lwa już od pięciu lat; opisano tu stan.'],
        ],
        'A2' => [
            ['Коли подзвонили у двері, малюк спав уже годину.', 'Kiedy zadzwonił dzwonek do drzwi, dziecko spało już od godziny.'],
            ['Коли крамниця нарешті відкрилася, ми обоє стояли в черзі ще з восьмої.', 'Kiedy sklep wreszcie otwarto, oboje staliśmy w kolejce już od ósmej.'],
            ['Нора весь вечір відпрацьовувала ту саму пісню, перш ніж нарешті виконала її правильно.', 'Nora przez cały wieczór ćwiczyła tę samą piosenkę, zanim w końcu zagrała ją poprawnie.'],
            ['Перш ніж побачити село, ми пройшли вже багато миль.', 'Zanim zobaczyliśmy wieś, szliśmy już przez wiele mil.'],
            ['Коли господар вийшов надвір, собака гавкав уже кілька хвилин.', 'Kiedy właściciel wyszedł na zewnątrz, pies szczekał już od kilku minut.'],
            ['Еллині руки були в борошні, бо вона перед цим пекла хліб.', 'Ręce Elli były pokryte mąką, ponieważ wcześniej piekła chleb.'],
            ['До завершення уроку Джек уже деякий час плавав у басейні.', 'Przed końcem lekcji Jack już przez pewien czas pływał w basenie.'],
            ['Коли ми прокинулися, сніг ішов ще з півночі.', 'Kiedy się obudziliśmy, śnieg padał już od północy.'],
            ['Перш ніж хтось вимкнув радіо, воно грало весь ранок.', 'Zanim ktoś wyłączył radio, grało ono przez cały ranek.'],
            ['До приходу друзів я прибирав свою кімнату вже дві години.', 'Przed przyjściem przyjaciół sprzątałem swój pokój już od dwóch godzin.'],
            ['Її очі почервоніли, бо вона плакала через сумну кінцівку.', 'Jej oczy były czerwone, ponieważ płakała z powodu smutnego zakończenia.'],
            ['До переїзду ми володіли тим будинком уже десять років; володіння — це стан.', 'Przed przeprowadzką byliśmy właścicielami tego domu już od dziesięciu lat; posiadanie jest stanem.'],
        ],
        'B1' => [
            ['Коли клієнт повернувся, механік ремонтував двигун уже годину; двигун усе ще був розібраний.', 'Kiedy klient wrócił, mechanik naprawiał silnik już od godziny; silnik nadal był rozłożony na części.'],
            ['Коли прибув керівник, кожен волонтер відповідав на дзвінки вже весь ранок.', 'Kiedy przybył przełożony, każdy wolontariusz odbierał telefony już przez cały ranek.'],
            ['До першої розмови за кордоном Сем місяцями вивчав французьку щовечора.', 'Przed pierwszą rozmową za granicą Sam przez wiele miesięcy uczył się francuskiego każdego wieczoru.'],
            ['Коли ми знайшли укриття, ми йшли крізь бурю вже сорок хвилин.', 'Kiedy znaleźliśmy schronienie, szliśmy przez burzę już od czterdziestu minut.'],
            ['Перш ніж зламатися, принтер кілька днів видавав дивні звуки.', 'Zanim drukarka przestała działać, przez kilka dni wydawała dziwne dźwięki.'],
            ['На кухні пахло часником, бо тато перед цим готував вечерю.', 'W kuchni pachniało czosnkiem, ponieważ tata wcześniej gotował kolację.'],
            ['Коли Роза потягнула спину, вона переносила коробки вже годину.', 'Kiedy Rosa nadwyrężyła plecy, przenosiła pudła już od godziny.'],
            ['Коли в червні роботи припинилися, сусіди ремонтували свій будинок ще з березня.', 'Kiedy prace przerwano w czerwcu, sąsiedzi remontowali swój dom już od marca.'],
            ['До приїзду поліції музика з квартири нагорі лунала вже весь вечір.', 'Przed przyjazdem policji muzyka z mieszkania na górze dochodziła już przez cały wieczór.'],
            ['Перед тим як вести туди групу, гід тижнями перевіряв маршрут.', 'Zanim przewodnik poprowadził tam grupę, przez wiele tygodni sprawdzał trasę.'],
            ['Трава була прим’ята там, де діти перед цим грали у футбол.', 'Trawa była przygnieciona tam, gdzie dzieci wcześniej grały w piłkę nożną.'],
            ['До перевірки столяр завершив усі чотири стільці; кожен був готовий.', 'Przed kontrolą stolarz ukończył wszystkie cztery krzesła; każde było gotowe.'],
        ],
        'B2' => [
            ['Коли фінансування припинилося, команда вже місяцями розробляла прототип; остаточного проєкту не існувало.', 'Kiedy finansowanie się skończyło, zespół od miesięcy opracowywał prototyp; ostateczny projekt nie istniał.'],
            ['Коли з’явилася перша аномалія, жоден із двох аналітиків ще не встиг довго відстежувати потік сповіщень.', 'Kiedy pojawiła się pierwsza anomalia, żaden z dwóch analityków nie monitorował strumienia alertów od dawna.'],
            ['До наказу про евакуацію рівень річки вже кілька годин невпинно піднімався.', 'Przed wydaniem nakazu ewakuacji poziom rzeki już od kilku godzin stale się podnosił.'],
            ['До слухання свідок уже кілька тижнів отримував повторні дзвінки, не дізнавшись, хто телефонував.', 'Przed rozprawą świadek już od kilku tygodni otrzymywał powtarzające się telefony, nie wiedząc, kto dzwonił.'],
            ['До відновлення електропостачання генератор біля лікарні гудів усю ніч.', 'Przed przywróceniem zasilania generator przy szpitalu buczał przez całą noc.'],
            ['Вона захрипла, бо протягом зміни перекрикувала шум обладнання.', 'Jej głos był zachrypnięty, ponieważ podczas zmiany przekrzykiwała maszyny.'],
            ['Коли автор зателефонував, редактор уже кілька годин вилучав непотрібні абзаци.', 'Kiedy autor zadzwonił, redaktor już od kilku godzin usuwał zbędne akapity.'],
            ['Коли злиття призупинило набір, компанія наймала працівників ще із січня.', 'Kiedy fuzja wstrzymała rekrutację, firma zatrudniała pracowników już od stycznia.'],
            ['До повідомлення про проблему те саме попередження блимало на екрані вже кілька днів.', 'Zanim ktoś zgłosił problem, to samo ostrzeżenie migało na ekranie już od kilku dni.'],
            ['Перш ніж погодити ціну, ми вели переговори з постачальниками вже шість місяців.', 'Zanim uzgodniliśmy cenę, negocjowaliśmy z dostawcami już od sześciu miesięcy.'],
            ['Їхній рахунок був порожній, бо протягом попереднього року вони багато витрачали на ремонт.', 'Ich konto było puste, ponieważ przez cały poprzedni rok dużo wydawali na naprawy.'],
            ['Коли почалося опитування, більшість мешканців уже були проти пропозиції; тут описано думку, а не діяльність.', 'Kiedy rozpoczęto badanie, większość mieszkańców była już przeciwna propozycji; opisano tu opinię, nie czynność.'],
        ],
        'C1' => [
            ['До появи документів слідчі розглядали зникнення як нещасний випадок, неодноразово переглядаючи цю версію.', 'Zanim ujawniono dokumenty, śledczy traktowali zaginięcie jako wypadek, wielokrotnie korygując tę wersję.'],
            ['До ухвалення спільного протоколу кожна лабораторія мережі незалежно досліджувала ефект.', 'Przed przyjęciem wspólnego protokołu każde laboratorium w sieci niezależnie badało ten efekt.'],
            ['До того як цифри виявили тенденцію, попит зростав місяцями; це не було разове збільшення.', 'Zanim dane ujawniły trend, popyt rósł przez wiele miesięcy; nie był to jednorazowy wzrost.'],
            ['До відкликання препарату пацієнти вже рік повідомляли про небажані реакції, хоча жодне окреме повідомлення не спричинило розслідування.', 'Przed wycofaniem leku pacjenci już od roku zgłaszali działania niepożądane, chociaż żadne pojedyncze zgłoszenie nie doprowadziło do dochodzenia.'],
            ['Поки слухання привертали увагу, за лаштунками вже тижнями тривали неформальні переговори.', 'Podczas gdy rozprawy przyciągały uwagę, nieformalne rozmowy za kulisami trwały już od wielu tygodni.'],
            ['Спад не здивував: ще до зриву контракту фірма невпинно втрачала досвідчених працівників.', 'Spadek nie był zaskoczeniem: przed zerwaniem kontraktu firma stale traciła doświadczonych pracowników.'],
            ['До виявлення розбіжності аудитори перемикалися між двома системами обліку, а не послідовно застосовували якусь одну.', 'Zanim wykryto rozbieżność, audytorzy przełączali się między dwoma systemami księgowymi, zamiast konsekwentnie stosować jeden.'],
            ['Коли суд призупинив дію політики, вона поступово змінювалася ще від свого запровадження.', 'Kiedy sąd zawiesił obowiązywanie polityki, zmieniała się ona stopniowo już od wprowadzenia.'],
            ['До того як інженери знайшли несправність, сигналізація вже кілька годин звучала з перервами.', 'Zanim inżynierowie znaleźli usterkę, alarm już od kilku godzin odzywał się z przerwami.'],
            ['Протягом десятиліття до заборони заводи скидали відходи в естуарій; речення підкреслює тривалу практику.', 'Przez dekadę przed zakazem fabryki odprowadzały odpady do estuarium; zdanie podkreśla długotrwałą praktykę.'],
            ['Дискусія поляризувалася, бо коментатори подавали питання як вибір між двома крайнощами.', 'Debata była spolaryzowana, ponieważ komentatorzy przedstawiali problem jako wybór między dwiema skrajnościami.'],
            ['До початку провадження спірна земля десятиліттями належала трасту; йдеться про юридичне володіння.', 'Przed rozpoczęciem postępowania sporna ziemia od dziesięcioleci należała do funduszu powierniczego; chodzi o własność prawną.'],
        ],
        'C2' => [
            ['До виправлення послідовні брифінги подавали оцінку як установлений факт, а не просто згадали її раз.', 'Przed sprostowaniem kolejne briefingi przedstawiały szacunek jako ustalony fakt, a nie tylko raz go przywołały.'],
            ['До офіційного голосування позиція, що здавалася одностайною, поступово формувалася через приватні обговорення.', 'Przed formalnym głosowaniem stanowisko wyglądające na jednomyślne stopniowo wyłaniało się w prywatnych rozmowach.'],
            ['До відкриття архіву історики перевіряли версію за непрямими свідченнями, але перевірка ще не була завершена.', 'Przed otwarciem archiwum historycy sprawdzali relację na podstawie pośrednich dowodów, ale weryfikacja pozostawała nieukończona.'],
            ['Протягом років до розкриття інформації посадовці проводили розмежування, які пізніші публічні підсумки стерли.', 'Przez lata przed ujawnieniem informacji urzędnicy wprowadzali rozróżnienia, które późniejsze publiczne podsumowania zatarły.'],
            ['Поки публічна дискусія загострювалася, менша група паралельно вивчала практичні наслідки ще із січня.', 'Gdy debata publiczna się zaostrzała, mniejsza grupa równolegle badała praktyczne konsekwencje już od stycznia.'],
            ['Остаточний текст був внутрішньо суперечливий, бо послідовні редактори змінювали його охоплення в протилежних напрямках.', 'Ostateczny tekst był wewnętrznie niespójny, ponieważ kolejni redaktorzy zmieniali jego zakres w przeciwnych kierunkach.'],
            ['До опечатування архіву дослідники переносили крихкі документи до цифрової колекції; процес усе ще не був завершений.', 'Przed zapieczętowaniem archiwum badacze przenosili delikatne dokumenty do kolekcji cyfrowej; proces nadal nie był ukończony.'],
            ['До судового рішення це тлумачення невпинно набувало переконливості, хоча так і не стало офіційною позицією.', 'Przed orzeczeniem ta interpretacja stale zyskiwała wiarygodność, choć nigdy nie stała się oficjalnym stanowiskiem.'],
            ['Упродовж місяців до врегулювання листування, на перший погляд звичайне, передавало дедалі відвертіші погрози.', 'Przez miesiące przed ugodą korespondencja wyglądająca na rutynową przekazywała coraz bardziej jednoznaczne groźby.'],
            ['Аудит виявив, що підрядники неодноразово заявляли про відповідність вимогам протягом періоду перед поновленням, а не лише одного разу.', 'Audyt wykazał, że wykonawcy wielokrotnie deklarowali zgodność w okresie poprzedzającym odnowienie, a nie tylko raz.'],
            ['Уявна згода вводила в оману: протягом усіх переговорів учасники по-різному тлумачили той самий термін.', 'Pozorny konsensus był mylący: przez całe negocjacje uczestnicy różnie interpretowali ten sam termin.'],
            ['До публікації колегія оцінила рівно дванадцять подань і закрила кожну справу; твердження стосується завершених результатів.', 'Przed publikacją panel ocenił dokładnie dwanaście wniosków i zamknął każdą sprawę; twierdzenie dotyczy ukończonych wyników.'],
        ],
    ],
    'Negatives' => require __DIR__.'/ppc_quality_mixed_sources_negatives.php',
    'Questions' => require __DIR__.'/ppc_quality_mixed_sources_questions.php',
    'TimeExpressions' => require __DIR__.'/ppc_quality_mixed_sources_time.php',
];
