<?php

return [
    'A1' => [
        ppcQualityItem('I {a1} before dinner; I had spent that time resting.', 'had not been working', 'work', 'працювати', 'negative'),
        ppcQualityItem('They {a1} long when the doors opened; they had arrived only a minute earlier.', "hadn't been waiting", 'wait', 'чекати', 'not_long'),
        ppcQualityItem('She {a1} before the teacher came in; her books were still in her bag.', 'had not been studying', 'study', 'навчатися', 'negative'),
        ppcQualityItem('We {a1} for long before the car stopped; we were still near home.', "hadn't been driving", 'drive', 'керувати автомобілем', 'not_long'),
        ppcQualityItem('The children {a1} before class; they had all been silent.', "hadn't been talking", 'talk', 'розмовляти', 'negative'),
        ppcQualityItem('Leo {a1} before he felt tired; he had stayed in bed.', 'had not been running', 'run', 'бігти', 'negative'),
        ppcQualityItem('Nina {a1} notes before lunch; her notebook was empty.', "hadn't been making", 'make', 'робити', 'negative'),
        ppcQualityItem('They {a1} there long when they moved again; they had stayed only a week.', 'had not been living', 'live', 'жити', 'not_long'),
        ppcQualityItem('I {a1} before the lights went out; I had been watching TV.', "hadn't been reading", 'read', 'читати', 'negative'),
        ppcQualityItem('We {a1} for the key before Dad found it; we already knew where it was.', 'had not been looking', 'look', 'шукати (з for)', 'negative'),
        ppcQualityItem('The boys {a1} football before lunch; they had been indoors all morning.', "hadn't been playing", 'play', 'грати', 'negative'),
        ppcQualityItem('She {a1} well before the trip; she had woken up every hour.', 'had not been sleeping', 'sleep', 'спати', 'not_well'),
    ],
    'A2' => [
        ppcQualityItem('The baby {a1} before the nurse arrived; it had been awake for hours.', 'had not been sleeping', 'sleep', 'спати', 'negative'),
        ppcQualityItem('We {a1} for long when the gate opened; there were only two people ahead of us.', "hadn't been queuing", 'queue', 'стояти в черзі', 'not_long'),
        ppcQualityItem('Tom {a1} the piano before the concert; he had spent the week travelling.', 'had not been practising', 'practise', 'тренуватися', 'negative'),
        ppcQualityItem('The group {a1} for long before the rain started; the station was still in sight.', "hadn't been walking", 'walk', 'йти пішки', 'not_long'),
        ppcQualityItem('The dog {a1} before we woke up; the house had been quiet.', "hadn't been barking", 'bark', 'гавкати', 'negative'),
        ppcQualityItem('Ella {a1} before her friends came; all the cakes were from the shop.', 'had not been baking', 'bake', 'пекти', 'negative'),
        ppcQualityItem('Jack {a1} before the lesson; his swimsuit was still dry.', "hadn't been swimming", 'swim', 'плавати', 'negative'),
        ppcQualityItem('It {a1} for long when school closed; only a little snow covered the path.', 'had not been snowing', 'snow', 'сніжити', 'not_long'),
        ppcQualityItem('The radio {a1} before breakfast; nobody had turned it on.', "hadn't been playing", 'play', 'грати', 'negative'),
        ppcQualityItem('I {a1} my room before Mum arrived; I had been doing homework instead.', 'had not been cleaning', 'clean', 'прибирати', 'negative'),
        ppcQualityItem('Rosa {a1} before we met; her red eyes were caused by dust.', "hadn't been crying", 'cry', 'плакати', 'negative'),
        ppcQualityItem('Ben {a1} well before the race; he had skipped most of his meals.', 'had not been eating', 'eat', 'їсти', 'not_well'),
    ],
    'B1' => [
        ppcQualityItem('The mechanic {a1} the van before the owner returned; the tools had remained locked away.', 'had not been repairing', 'repair', 'ремонтувати', 'negative'),
        ppcQualityItem('I {a1} calls for long when the system crashed; my shift had just started.', "hadn't been answering", 'answer', 'відповідати на', 'not_long'),
        ppcQualityItem('Sam {a1} French before his trip; he had only memorised a few phrases that morning.', 'had not been learning', 'learn', 'вивчати', 'negative'),
        ppcQualityItem('We {a1} for long when we reached the lake, despite feeling exhausted already.', "hadn't been hiking", 'hike', 'йти в піший похід', 'not_long'),
        ppcQualityItem('The printer {a1} those noises before the repair; they started only after the technician left.', "hadn't been making", 'make', 'видавати', 'negative'),
        ppcQualityItem('Dad {a1} before the alarm rang; the smoke had come from the neighbour’s flat.', 'had not been cooking', 'cook', 'готувати', 'negative'),
        ppcQualityItem('Rosa {a1} boxes before her back began to hurt; she had been sitting at a desk.', "hadn't been carrying", 'carry', 'переносити', 'negative'),
        ppcQualityItem('The neighbours {a1} for long when they ran out of money; only one room had changed.', 'had not been renovating', 'renovate', 'ремонтувати будівлю', 'not_long'),
        ppcQualityItem('Water {a1} through the ceiling before the storm; that leak was entirely new.', "hadn't been coming", 'come', 'просочуватися', 'negative'),
        ppcQualityItem('The guide {a1} the route regularly before that walk; her map was years out of date.', 'had not been checking', 'check', 'перевіряти', 'negative'),
        ppcQualityItem('The children {a1} outside before the grass was damaged; workers had driven across it.', "hadn't been playing", 'play', 'грати', 'negative'),
        ppcQualityItem('The patient {a1} well before admission, although he had managed a little food each day.', 'had not been eating', 'eat', 'їсти', 'not_well'),
    ],
    'B2' => [
        ppcQualityItem('The team {a1} a new design before the review; it had merely reused an old prototype.', 'had not been developing', 'develop', 'розробляти', 'negative'),
        ppcQualityItem('The analyst {a1} the feed for long when the anomaly appeared, so she lacked a reliable baseline.', "hadn't been monitoring", 'monitor', 'відстежувати', 'not_long'),
        ppcQualityItem('The river {a1} before the dam was opened; the earlier readings showed no upward movement.', 'had not been rising', 'rise', 'підніматися', 'negative'),
        ppcQualityItem('The witness {a1} threatening calls for long when she contacted the police; the first had come that day.', "hadn't been receiving", 'receive', 'отримувати', 'not_long'),
        ppcQualityItem('The generator {a1} before the fault was fixed; it had been completely silent.', "hadn't been humming", 'hum', 'гудіти', 'negative'),
        ppcQualityItem('She {a1} during the shift; her hoarse voice was due to an infection.', 'had not been shouting', 'shout', 'кричати', 'negative'),
        ppcQualityItem('The editor {a1} paragraphs before the author called; the draft remained exactly as submitted.', "hadn't been cutting", 'cut', 'вилучати', 'negative'),
        ppcQualityItem('The firm {a1} staff for long when recruitment froze; the campaign had begun only days earlier.', 'had not been hiring', 'hire', 'наймати', 'not_long'),
        ppcQualityItem('The warning {a1} before the update; it appeared for the first time after installation.', "hadn't been flashing", 'flash', 'блимати', 'negative'),
        ppcQualityItem('We {a1} with that supplier before the agreement; an agent had handled all the discussions.', 'had not been negotiating', 'negotiate', 'вести переговори', 'negative'),
        ppcQualityItem('The council {a1} money on repairs before the collapse; the maintenance budget was untouched.', "hadn't been spending", 'spend', 'витрачати', 'negative'),
        ppcQualityItem('The engine {a1} well before the breakdown; it had stalled repeatedly, though it still ran between stalls.', 'had not been running', 'run', 'працювати (про двигун)', 'not_well'),
    ],
    'C1' => [
        ppcQualityItem('Before the files emerged, investigators {a1} the case as an accident; their working assumption was deliberate interference.', 'had not been treating', 'treat', 'розглядати як', 'negative'),
        ppcQualityItem('The laboratories {a1} the effect independently for long when the shared protocol changed their methods.', "hadn't been investigating", 'investigate', 'досліджувати', 'not_long'),
        ppcQualityItem('Demand {a1} before the subsidy; the supposed earlier increase was a statistical correction, not a trend.', 'had not been growing', 'grow', 'зростати', 'negative'),
        ppcQualityItem('Patients {a1} reactions for long before the recall, although the medication had been available for years.', "hadn't been reporting", 'report', 'повідомляти про', 'not_long'),
        ppcQualityItem('Informal talks {a1} during the hearings; both sides had suspended contact before the hearings opened.', "hadn't been continuing", 'continue', 'тривати', 'negative'),
        ppcQualityItem('The firm {a1} staff before the contract failed; its workforce had remained stable throughout the negotiations.', 'had not been losing', 'lose', 'втрачати', 'negative'),
        ppcQualityItem('The auditors {a1} between systems before the discrepancy appeared; they had applied one method consistently.', "hadn't been switching", 'switch', 'перемикатися', 'negative'),
        ppcQualityItem('The policy {a1} for long when judicial review interrupted its gradual development.', 'had not been evolving', 'evolve', 'поступово змінюватися', 'not_long'),
        ppcQualityItem('The alarm {a1} before the inspection; later testing produced the first audible warning.', "hadn't been sounding", 'sound', 'звучати', 'negative'),
        ppcQualityItem('Factories {a1} waste into the estuary before the spill; the contamination came from a single storage failure.', 'had not been discharging', 'discharge', 'скидати', 'negative'),
        ppcQualityItem('Commentators {a1} the debate as a binary choice before that speech; their earlier accounts distinguished several positions.', "hadn't been framing", 'frame', 'подавати як', 'negative'),
        ppcQualityItem('The participants {a1} well before mediation; contact was frequent, but their messages repeatedly caused misunderstandings.', 'had not been communicating', 'communicate', 'спілкуватися', 'not_well'),
    ],
    'C2' => [
        ppcQualityItem('Before the leak, officials {a1} that estimate as established fact; every briefing had labelled it provisional.', 'had not been presenting', 'present', 'подавати', 'negative'),
        ppcQualityItem('The apparent consensus {a1} for long before it fractured; a late concession had brought the positions together only briefly.', "hadn't been emerging", 'emerge', 'формуватися', 'not_long'),
        ppcQualityItem('Historians {a1} that account before the archive opened; they had accepted it without attempting verification.', 'had not been testing', 'test', 'перевіряти', 'negative'),
        ppcQualityItem('The panel {a1} that distinction for long before abandoning it, despite describing the distinction as an established tradition.', "hadn't been drawing", 'draw', 'проводити (розмежування)', 'not_long'),
        ppcQualityItem('The group {a1} practical implications before the vote; it had confined discussion to abstract principles.', "hadn't been exploring", 'explore', 'вивчати', 'negative'),
        ppcQualityItem('The editors {a1} the text’s scope before publication; the inconsistencies were already present in the first draft.', 'had not been altering', 'alter', 'змінювати', 'negative'),
        ppcQualityItem('Researchers {a1} records before the archive closed; permission to digitise them had never been granted.', "hadn't been transferring", 'transfer', 'переносити', 'negative'),
        ppcQualityItem('The interpretation {a1} credibility for long when the ruling reversed the brief upward trend.', 'had not been gaining', 'gain', 'набувати', 'not_long'),
        ppcQualityItem('The correspondence {a1} threats before the settlement; the later reading imposed an intention absent from the original exchanges.', "hadn't been conveying", 'convey', 'передавати', 'negative'),
        ppcQualityItem('Contractors {a1} full compliance before renewal; their repeated reports had explicitly acknowledged unresolved breaches.', 'had not been claiming', 'claim', 'заявляти про', 'negative'),
        ppcQualityItem('The parties {a1} the term differently before the amendment; ambiguity arose only after its wording changed.', "hadn't been interpreting", 'interpret', 'тлумачити', 'negative'),
        ppcQualityItem('The committee {a1} well before the restructure; it met regularly, but its decisions repeatedly contradicted one another.', 'had not been functioning', 'function', 'функціонувати', 'not_well'),
    ],
];
