<?php

return [
    'A1' => [
        ppcQualityItem('I {a1} for two hours before dinner started.', 'had been working', 'work', 'працювати'),
        ppcQualityItem('They {a1} for ten minutes when the bus came.', 'had been waiting', 'wait', 'чекати'),
        ppcQualityItem('She {a1} for twenty minutes when the teacher came in.', 'had been studying', 'study', 'навчатися'),
        ppcQualityItem('We {a1} for three hours before our first stop.', 'had been driving', 'drive', 'керувати автомобілем'),
        ppcQualityItem('The children {a1} quietly for a while before class began.', 'had been talking', 'talk', 'розмовляти'),
        ppcQualityItem('Ben was out of breath because he {a1} uphill.', 'had been running', 'run', 'бігти', 'cause'),
        ppcQualityItem('Mia {a1} notes for half an hour before lunch.', 'had been making', 'make', 'робити', 'spelling'),
        ppcQualityItem('My parents {a1} in that flat for a year when I was born.', 'had been living', 'live', 'жити'),
        ppcQualityItem('I {a1} for an hour when the lights went out.', 'had been reading', 'read', 'читати'),
        ppcQualityItem('We {a1} for the key for ten minutes before Dad found it.', 'had been looking', 'look', 'шукати (з for)'),
        ppcQualityItem('The floor was wet because Leo {a1} it.', 'had been washing', 'wash', 'мити', 'cause'),
        ppcQualityItem('Anna {a1} Lev for five years by 2020; this describes a state.', 'had known', 'know', 'знати', 'state', ['had known', 'had been knowing', 'had knew', 'had know', 'had being known']),
    ],
    'A2' => [
        ppcQualityItem('The baby {a1} for an hour when the doorbell rang.', 'had been sleeping', 'sleep', 'спати'),
        ppcQualityItem('Both of us {a1} since eight when the shop finally opened.', 'had been queuing', 'queue', 'стояти в черзі'),
        ppcQualityItem('Nora {a1} the same song all evening before she got it right.', 'had been practising', 'practise', 'тренуватися'),
        ppcQualityItem('We {a1} for miles before we saw the village.', 'had been walking', 'walk', 'йти пішки'),
        ppcQualityItem('The dog {a1} for several minutes when its owner came outside.', 'had been barking', 'bark', 'гавкати'),
        ppcQualityItem('Ella’s hands were covered in flour because she {a1} bread.', 'had been baking', 'bake', 'пекти', 'cause'),
        ppcQualityItem('Jack {a1} in the pool for a while before the lesson ended.', 'had been swimming', 'swim', 'плавати', 'spelling'),
        ppcQualityItem('It {a1} since midnight when we woke up.', 'had been snowing', 'snow', 'сніжити'),
        ppcQualityItem('The radio {a1} all morning before someone turned it off.', 'had been playing', 'play', 'грати'),
        ppcQualityItem('I {a1} my room for two hours before my friends arrived.', 'had been cleaning', 'clean', 'прибирати'),
        ppcQualityItem('Her eyes were red because she {a1} at the sad ending.', 'had been crying', 'cry', 'плакати', 'cause'),
        ppcQualityItem('By the move, we {a1} that house for ten years; ownership is a state.', 'had owned', 'own', 'володіти', 'state', ['had owned', 'had been owning', 'had own', 'had being owned', 'had owns']),
    ],
    'B1' => [
        ppcQualityItem('The mechanic {a1} the engine for an hour when the customer returned; it was still in pieces.', 'had been repairing', 'repair', 'ремонтувати'),
        ppcQualityItem('Each volunteer {a1} calls all morning when the supervisor arrived.', 'had been answering', 'answer', 'відповідати на'),
        ppcQualityItem('Sam {a1} French every evening for months before his first conversation abroad.', 'had been learning', 'learn', 'вивчати'),
        ppcQualityItem('By the time we found shelter, we {a1} through the storm for forty minutes.', 'had been hiking', 'hike', 'йти в піший похід'),
        ppcQualityItem('The printer {a1} strange noises for days before it stopped working.', 'had been making', 'make', 'видавати'),
        ppcQualityItem('The kitchen smelled of garlic because Dad {a1} dinner.', 'had been cooking', 'cook', 'готувати', 'cause'),
        ppcQualityItem('Rosa {a1} the boxes for an hour before she hurt her back.', 'had been carrying', 'carry', 'переносити', 'spelling'),
        ppcQualityItem('The neighbours {a1} their house since March when work stopped in June.', 'had been renovating', 'renovate', 'ремонтувати будівлю'),
        ppcQualityItem('Music {a1} from the upstairs flat all evening before the police arrived.', 'had been coming', 'come', 'доноситися'),
        ppcQualityItem('The guide {a1} the route for weeks before taking the group there.', 'had been checking', 'check', 'перевіряти'),
        ppcQualityItem('The grass was flat where the children {a1} football.', 'had been playing', 'play', 'грати', 'cause'),
        ppcQualityItem('By the inspection, the carpenter {a1} all four chairs; every chair was ready.', 'had finished', 'finish', 'завершити', 'complete', ['had finished', 'had been finishing', 'had finish', 'had finishing', 'had being finished']),
    ],
    'B2' => [
        ppcQualityItem('The team {a1} the prototype for months when funding ended; no final design existed.', 'had been developing', 'develop', 'розробляти'),
        ppcQualityItem('Neither of the two analysts {a1} the alert stream for long when the first anomaly appeared.', 'had been monitoring', 'monitor', 'відстежувати'),
        ppcQualityItem('The river {a1} steadily for hours before the evacuation order was issued.', 'had been rising', 'rise', 'підніматися'),
        ppcQualityItem('By the hearing, the witness {a1} repeated calls for several weeks without learning who made them.', 'had been receiving', 'receive', 'отримувати'),
        ppcQualityItem('A generator {a1} outside the hospital all night before mains power returned.', 'had been humming', 'hum', 'гудіти'),
        ppcQualityItem('Her voice was hoarse because she {a1} over the machinery during the shift.', 'had been shouting', 'shout', 'кричати', 'cause'),
        ppcQualityItem('The editor {a1} unnecessary paragraphs for hours when the author called.', 'had been cutting', 'cut', 'вилучати', 'spelling'),
        ppcQualityItem('The company {a1} staff since January when the merger put recruitment on hold.', 'had been hiring', 'hire', 'наймати'),
        ppcQualityItem('The same warning {a1} on the screen for days before anyone reported it.', 'had been flashing', 'flash', 'блимати'),
        ppcQualityItem('We {a1} with suppliers for six months before agreeing on a price.', 'had been negotiating', 'negotiate', 'вести переговори'),
        ppcQualityItem('Their account was empty because they {a1} heavily on repairs throughout the previous year.', 'had been spending', 'spend', 'витрачати', 'cause'),
        ppcQualityItem('When the survey began, most residents {a1} the proposal; this describes an opinion, not an activity.', 'had opposed', 'oppose', 'бути проти', 'state', ['had opposed', 'had been opposing', 'had oppose', 'had opposing', 'had being opposed']),
    ],
    'C1' => [
        ppcQualityItem('Until the records surfaced, investigators {a1} the disappearance as an accident, repeatedly revising that account.', 'had been treating', 'treat', 'розглядати як'),
        ppcQualityItem('Every laboratory in the network {a1} the effect independently before the common protocol was adopted.', 'had been investigating', 'investigate', 'досліджувати'),
        ppcQualityItem('Demand {a1} for months before the figures revealed the trend; it was not a one-off increase.', 'had been growing', 'grow', 'зростати'),
        ppcQualityItem('By the recall, patients {a1} adverse reactions for a year, although no single report had triggered an inquiry.', 'had been reporting', 'report', 'повідомляти про'),
        ppcQualityItem('While the hearings attracted attention, informal talks {a1} behind the scenes for weeks.', 'had been continuing', 'continue', 'тривати'),
        ppcQualityItem('The decline was unsurprising: the firm {a1} experienced staff steadily before the contract collapsed.', 'had been losing', 'lose', 'втрачати', 'cause'),
        ppcQualityItem('Before the discrepancy emerged, auditors {a1} between the two accounting systems rather than applying either consistently.', 'had been switching', 'switch', 'перемикатися', 'spelling'),
        ppcQualityItem('The policy {a1} gradually since its introduction when the court suspended it.', 'had been evolving', 'evolve', 'поступово змінюватися'),
        ppcQualityItem('The alarm {a1} intermittently for hours before the engineers traced the fault.', 'had been sounding', 'sound', 'звучати'),
        ppcQualityItem('For a decade before the ban, factories {a1} waste into the estuary; the sentence stresses the sustained practice.', 'had been discharging', 'discharge', 'скидати'),
        ppcQualityItem('The debate was polarised because commentators {a1} the issue as a choice between two extremes.', 'had been framing', 'frame', 'подавати як', 'cause'),
        ppcQualityItem('Before proceedings began, the disputed land {a1} to the trust for decades; this is legal ownership.', 'had belonged', 'belong', 'належати', 'state', ['had belonged', 'had been belonging', 'had belong', 'had belonging', 'had being belonged']),
    ],
    'C2' => [
        ppcQualityItem('Before the correction, successive briefings {a1} an estimate as established fact, not merely citing it once.', 'had been presenting', 'present', 'подавати'),
        ppcQualityItem('What looked like a unanimous position {a1} gradually through private exchanges before the formal vote.', 'had been emerging', 'emerge', 'формуватися'),
        ppcQualityItem('Until the archive opened, historians {a1} the account against indirect evidence, with verification still incomplete.', 'had been testing', 'test', 'перевіряти'),
        ppcQualityItem('For years before disclosure, officials {a1} distinctions that the public summaries later erased.', 'had been drawing', 'draw', 'проводити (розмежування)'),
        ppcQualityItem('As the public debate intensified, a smaller group {a1} the practical implications in parallel since January.', 'had been exploring', 'explore', 'вивчати'),
        ppcQualityItem('The final text was internally inconsistent because successive editors {a1} its scope in opposite directions.', 'had been altering', 'alter', 'змінювати', 'cause'),
        ppcQualityItem('Before the archive was sealed, researchers {a1} fragile records into a digital collection, a process still unfinished.', 'had been transferring', 'transfer', 'переносити', 'spelling'),
        ppcQualityItem('By the ruling, that interpretation {a1} credibility steadily, despite never becoming the official position.', 'had been gaining', 'gain', 'набувати'),
        ppcQualityItem('For months before the settlement, apparently routine correspondence {a1} increasingly explicit threats.', 'had been conveying', 'convey', 'передавати'),
        ppcQualityItem('The audit found that contractors {a1} compliance repeatedly throughout the period preceding renewal, not just on one occasion.', 'had been claiming', 'claim', 'заявляти про'),
        ppcQualityItem('The apparent consensus was misleading: participants {a1} the same term differently throughout the negotiations.', 'had been interpreting', 'interpret', 'тлумачити', 'cause'),
        ppcQualityItem('By publication, the panel {a1} exactly twelve submissions and closed every file; the claim concerns completed outcomes.', 'had assessed', 'assess', 'оцінити', 'complete', ['had assessed', 'had been assessing', 'had assess', 'had assessing', 'had being assessed']),
    ],
];
