<?php

return [
    'A1' => [
        ppcQualityQuestion('{a1} for two hours before dinner?', 'Had you been working', 'work', 'працювати', 'yesno', 'you'),
        ppcQualityQuestion('{a1} since morning when the bus came?', 'Had she been waiting', 'wait', 'чекати', 'yesno', 'she'),
        ppcQualityQuestion('{a1} for twenty minutes before the teacher came in?', 'Had they been studying', 'study', 'навчатися', 'yesno', 'they'),
        ppcQualityQuestion('{a1} before lunch: reading or drawing?', 'What had he been doing', 'do', 'робити', 'object_q', 'he'),
        ppcQualityQuestion('{a1} before your first stop: one hour or two?', 'How long had you been driving', 'drive', 'керувати автомобілем', 'duration_q', 'you'),
        ppcQualityShort('You had waited for an hour. I asked, “Had you been waiting long?” You answered: {a1}.', 'Yes, I had', ['Yes, I had', 'No, I had not', 'Yes, you had', 'Yes, I been', 'Yes, I did']),
        ppcQualityQuestion('{a1} notes all morning before lunch?', 'Had Mia been making', 'make', 'робити', 'yesno', 'Mia'),
        ppcQualityQuestion('{a1} before the move: in Kyiv or in Lviv?', 'Where had they been living', 'live', 'жити', 'place_q', 'they'),
        ppcQualityQuestion('{a1} when the lights went out: ten minutes or an hour?', 'How long had he been reading', 'read', 'читати', 'duration_q', 'he'),
        ppcQualityQuestion('{a1} for the key before Dad found it?', 'Had you been looking', 'look', 'шукати (з for)', 'yesno', 'you'),
        ppcQualityShort('The boys were indoors all morning. Had they been playing outside before lunch? — {a1}.', "No, they hadn't", ["No, they hadn't", 'Yes, they had', "No, he hadn't", "No, they weren't", 'No, they been']),
        ppcQualityQuestion('{a1} well before the trip?', 'Had she been sleeping', 'sleep', 'спати', 'yesno', 'she'),
    ],
    'A2' => [
        ppcQualityQuestion('{a1} for an hour when the doorbell rang?', 'Had the baby been sleeping', 'sleep', 'спати', 'yesno', 'the baby'),
        ppcQualityQuestion('{a1} long when the shop opened?', 'Had both of you been queuing', 'queue', 'стояти в черзі', 'yesno', 'both of you'),
        ppcQualityQuestion('{a1} that song all evening before the concert?', 'Had Nora been practising', 'practise', 'тренуватися', 'yesno', 'Nora'),
        ppcQualityQuestion('{a1} before the train arrived: at the station or outside?', 'Where had Ben been waiting', 'wait', 'чекати', 'place_q', 'Ben'),
        ppcQualityQuestion('{a1} before you reached the village: five minutes or an hour?', 'How long had you been walking', 'walk', 'йти пішки', 'duration_q', 'you'),
        ppcQualityShort('Jack was already wet from an hour in the pool. Had he been swimming before the lesson? — {a1}.', 'Yes, he had', ['Yes, he had', 'No, he had not', 'Yes, she had', 'Yes, he was', 'Yes, he been']),
        ppcQualityQuestion('{a1} bread all morning before the guests arrived?', 'Had Ella been baking', 'bake', 'пекти', 'yesno', 'Ella'),
        ppcQualityQuestion('{a1} before you came in: music or the news?', 'What had the radio been playing', 'play', 'грати', 'object_q', 'the radio'),
        ppcQualityQuestion('{a1} before the guests came: half an hour or two hours?', 'How long had you been cleaning', 'clean', 'прибирати', 'duration_q', 'you'),
        ppcQualityQuestion('{a1} all night when you woke up?', 'Had it been snowing', 'snow', 'сніжити', 'yesno', 'it'),
        ppcQualityShort('Rosa’s eyes were red from dust, not tears. Had she been crying before we met? — {a1}.', "No, she hadn't", ["No, she hadn't", 'Yes, she had', "No, they hadn't", 'No, she did not', 'No, she been']),
        ppcQualityQuestion('{a1} enough before the race?', 'Had Ben been eating', 'eat', 'їсти', 'yesno', 'Ben'),
    ],
    'B1' => [
        ppcQualityQuestion('{a1} the engine for an hour when the customer returned?', 'Had the mechanic been repairing', 'repair', 'ремонтувати', 'yesno', 'the mechanic'),
        ppcQualityQuestion('{a1} calls regularly before the system failed?', 'Had each volunteer been answering', 'answer', 'відповідати на', 'yesno', 'each volunteer'),
        ppcQualityQuestion('{a1} French for months before his first trip abroad?', 'Had Sam been learning', 'learn', 'вивчати', 'yesno', 'Sam'),
        ppcQualityQuestion('{a1} before lunch if she was not preparing for an exam?', 'Why had Rosa been studying', 'study', 'навчатися', 'reason_q', 'Rosa'),
        ppcQualityQuestion('{a1} before finding shelter: forty minutes or longer?', 'How long had they been hiking', 'hike', 'йти в піший похід', 'duration_q', 'they'),
        ppcQualityShort('Dad had spent an hour at the stove before the alarm rang. Had he been cooking? — {a1}.', 'Yes, he had', ['Yes, he had', 'No, he had not', 'Yes, they had', 'Yes, he did', 'Yes, he been']),
        ppcQualityQuestion('{a1} heavy boxes before her back started hurting?', 'Had Rosa been carrying', 'carry', 'переносити', 'yesno', 'Rosa'),
        ppcQualityQuestion('{a1} before class: in the kitchen or in the bedroom?', 'Where had Mia been practising', 'practise', 'тренуватися', 'place_q', 'Mia'),
        ppcQualityQuestion('{a1} before work stopped in June: since March or only since May?', 'How long had the neighbours been renovating', 'renovate', 'ремонтувати будівлю', 'duration_q', 'the neighbours'),
        ppcQualityQuestion('{a1} the route for weeks before the group’s arrival?', 'Had the guide been checking', 'check', 'перевіряти', 'yesno', 'the guide'),
        ppcQualityShort('The children had stayed indoors; workers damaged the grass. Had the children been playing outside? — {a1}.', "No, they hadn't", ["No, they hadn't", 'Yes, they had', "No, it hadn't", 'No, they did not', 'No, they been']),
        ppcQualityQuestion('The nurse asked whether {a1} well before admission.', 'the patient had been eating', 'eat', 'їсти', 'embedded', 'the patient', ['the patient had been eating', 'had the patient been eating', 'the patient had eating', 'the patient had being eating', 'the patient had been eat']),
    ],
    'B2' => [
        ppcQualityQuestion('{a1} the prototype for months when funding ended, or was development already complete?', 'Had the team been developing', 'develop', 'розробляти', 'yesno', 'the team'),
        ppcQualityQuestion('{a1} the feed long enough to recognise a normal pattern before the anomaly appeared?', 'Had the analyst been monitoring', 'monitor', 'відстежувати', 'yesno', 'the analyst'),
        ppcQualityQuestion('{a1} steadily before the dam opened, or did the increase start only afterwards?', 'Had the river been rising', 'rise', 'підніматися', 'yesno', 'the river'),
        ppcQualityQuestion('{a1} those calls before the hearing if nobody had given her number to the press?', 'Why had she been receiving', 'receive', 'отримувати', 'reason_q', 'she'),
        ppcQualityQuestion('{a1} before mains power returned: one night or several?', 'How long had the generator been humming', 'hum', 'гудіти', 'duration_q', 'the generator'),
        ppcQualityShort('The editor repeatedly deleted paragraphs throughout the morning. Had she been cutting the draft before lunch? — {a1}.', 'Yes, she had', ['Yes, she had', 'No, she had not', 'Yes, he had', 'Yes, she did', 'Yes, she been']),
        ppcQualityQuestion('{a1} over the machinery before her voice became hoarse?', 'Had she been shouting', 'shout', 'кричати', 'yesno', 'she'),
        ppcQualityQuestion('{a1} before the signing ceremony: in person or online?', 'Where had the delegates been negotiating', 'negotiate', 'вести переговори', 'place_q', 'the delegates'),
        ppcQualityQuestion('The investigator asked how long {a1} staff before recruitment froze.', 'the firm had been hiring', 'hire', 'наймати', 'embedded', 'the firm', ['the firm had been hiring', 'had the firm been hiring', 'the firm had hiring', 'the firm had being hiring', 'the firm had been hire']),
        ppcQualityQuestion('{a1} before the update, despite the later claim that it was a new warning?', 'Had the light not been flashing', 'flash', 'блимати', 'negative_q', 'the light', ['Had the light not been flashing', 'Had the light flashing not', 'Had the light not flashing', 'Had the light not being flashing', 'Had the light not been flash']),
        ppcQualityShort('The maintenance budget had remained untouched. Had the council been spending money on repairs before the collapse? — {a1}.', "No, it hadn't", ["No, it hadn't", 'Yes, it had', "No, they hadn't", 'No, it did not', 'No, it been']),
        ppcQualityQuestion('Can you explain why {a1} badly before the breakdown?', 'the engine had been running', 'run', 'працювати (про двигун)', 'embedded', 'the engine', ['the engine had been running', 'had the engine been running', 'the engine had running', 'the engine had being running', 'the engine had been run']),
    ],
    'C1' => [
        ppcQualityQuestion('{a1} the case as accidental before the records challenged that assumption?', 'Had the investigators been treating', 'treat', 'розглядати як', 'yesno', 'the investigators'),
        ppcQualityQuestion('{a1} the effect independently before the shared protocol replaced their methods?', 'Had every laboratory been investigating', 'investigate', 'досліджувати', 'yesno', 'every laboratory'),
        ppcQualityQuestion('{a1} steadily before the subsidy, or was the apparent trend merely a statistical correction?', 'Had demand been growing', 'grow', 'зростати', 'yesno', 'demand'),
        ppcQualityQuestion('{a1} adverse reactions before the recall, given that the earlier summaries reported none?', 'Why had patients been reporting', 'report', 'повідомляти про', 'reason_q', 'patients'),
        ppcQualityQuestion('The chair wanted to know how long {a1} behind the scenes before the public hearings.', 'informal talks had been continuing', 'continue', 'тривати', 'embedded', 'informal talks', ['informal talks had been continuing', 'had informal talks been continuing', 'informal talks had continuing', 'informal talks had being continuing', 'informal talks had been continue']),
        ppcQualityShort('Payroll records showed a steady departure of experienced workers before cancellation. Had the firm been losing staff? — {a1}.', 'Yes, it had', ['Yes, it had', 'No, it had not', 'Yes, they had', 'Yes, it did', 'Yes, it been']),
        ppcQualityQuestion('{a1} between accounting systems before the discrepancy arose, rather than following a single method?', 'Had the auditors been switching', 'switch', 'перемикатися', 'yesno', 'the auditors'),
        ppcQualityQuestion('The inquiry asked where {a1} waste before the ban.', 'the factories had been discharging', 'discharge', 'скидати', 'embedded', 'the factories', ['the factories had been discharging', 'had the factories been discharging', 'the factories had discharging', 'the factories had being discharging', 'the factories had been discharge']),
        ppcQualityQuestion('{a1} before the engineers traced the fault: intermittently for hours or only once?', 'How long had the alarm been sounding', 'sound', 'звучати', 'duration_q', 'the alarm'),
        ppcQualityQuestion('{a1} gradually before judicial review, despite the official claim of complete stability?', 'Had the policy not been evolving', 'evolve', 'поступово змінюватися', 'negative_q', 'the policy', ['Had the policy not been evolving', 'Had the policy evolving not', 'Had the policy not evolving', 'Had the policy not being evolving', 'Had the policy not been evolve']),
        ppcQualityShort('Earlier commentary had distinguished several positions, not two. Had commentators been framing the debate as binary before the speech? — {a1}.', "No, they hadn't", ["No, they hadn't", 'Yes, they had', "No, it hadn't", 'No, they did not', 'No, they been']),
        ppcQualityQuestion('The mediator asked why {a1} so poorly before her appointment, despite meeting regularly.', 'the parties had been communicating', 'communicate', 'спілкуватися', 'embedded', 'the parties', ['the parties had been communicating', 'had the parties been communicating', 'the parties had communicating', 'the parties had being communicating', 'the parties had been communicate']),
    ],
    'C2' => [
        ppcQualityQuestion('{a1} the estimate as established fact repeatedly before the correction, or had they consistently called it provisional?', 'Had successive briefings been presenting', 'present', 'подавати', 'yesno', 'successive briefings'),
        ppcQualityQuestion('The review asked whether {a1} gradually before the vote rather than appearing in a single negotiation.', 'consensus had been emerging', 'emerge', 'формуватися', 'embedded', 'consensus', ['consensus had been emerging', 'had consensus been emerging', 'consensus had emerging', 'consensus had being emerging', 'consensus had been emerge']),
        ppcQualityQuestion('{a1} the account against indirect evidence before the archive opened, or had they accepted it without verification?', 'Had historians been testing', 'test', 'перевіряти', 'yesno', 'historians'),
        ppcQualityQuestion('{a1} that distinction before disclosure, and on what grounds had they treated it as legally significant?', 'Why had officials been drawing', 'draw', 'проводити (розмежування)', 'reason_q', 'officials'),
        ppcQualityQuestion('The report did not establish how long {a1} practical implications before moving to abstract principles.', 'the group had been exploring', 'explore', 'вивчати', 'embedded', 'the group', ['the group had been exploring', 'had the group been exploring', 'the group had exploring', 'the group had being exploring', 'the group had been explore']),
        ppcQualityShort('Successive revisions widened and then narrowed the scope before publication. Had the editors been altering it? — {a1}.', 'Yes, they had', ['Yes, they had', 'No, they had not', 'Yes, it had', 'Yes, they did', 'Yes, they been']),
        ppcQualityQuestion('{a1} fragile records before the archive closed: the curators themselves or an external contractor?', 'Who had been transferring', 'transfer', 'переносити', 'subject_q', 'Who', ['Who had been transferring', 'Who had they been transferring', 'Who had transferring', 'Who had being transferring', 'Who had been transfer']),
        ppcQualityQuestion('The tribunal asked where {a1} such assurances before renewal, since the written reports acknowledged breaches.', 'the contractors had been giving', 'give', 'давати', 'embedded', 'the contractors', ['the contractors had been giving', 'had the contractors been giving', 'the contractors had giving', 'the contractors had being giving', 'the contractors had been give']),
        ppcQualityQuestion('{a1} credibility before the ruling reversed the trend, independently of whether it was ever formally endorsed?', 'How long had the interpretation been gaining', 'gain', 'набувати', 'duration_q', 'the interpretation'),
        ppcQualityQuestion('{a1} threats before the settlement, contrary to the later characterisation of it as merely routine?', 'Had the correspondence not been conveying', 'convey', 'передавати', 'negative_q', 'the correspondence', ['Had the correspondence not been conveying', 'Had the correspondence conveying not', 'Had the correspondence not conveying', 'Had the correspondence not being conveying', 'Had the correspondence not been convey']),
        ppcQualityShort('The shared definition remained unchanged until the amendment. Had the parties been interpreting the term differently beforehand? — {a1}.', "No, they hadn't", ["No, they hadn't", 'Yes, they had', "No, it hadn't", 'No, they did not', 'No, they been']),
        ppcQualityQuestion('The inquiry asked how {a1} before restructuring, distinguishing regular meetings from coherent decision-making.', 'the committee had been functioning', 'function', 'функціонувати', 'embedded', 'the committee', ['the committee had been functioning', 'had the committee been functioning', 'the committee had functioning', 'the committee had being functioning', 'the committee had been function']),
    ],
];
