<?php

return [
    'A1' => [
        ppcQualityItem('They had been waiting {a1} two hours when the doors opened.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('She started work at nine and was still working at noon: she had been working {a1} nine.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
        ppcQualityItem('On that Monday, he ran from dawn to noon without a break: he had been running {a1} morning.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityItem('We stopped preparing at noon; dinner began at one. We had been preparing {a1} dinner began.', 'before', '', '', 'prior', ['before', 'after', 'while', 'since', 'as soon as']),
        ppcQualityItem('{a1} we arrived at noon, it had been raining for hours; the rain continued afterwards.', 'By the time', '', '', 'deadline', ['By the time', 'Since the time', 'For the time', 'During the time', 'Until the time']),
        ppcQualityItem('The bell rang and I stopped reading. I had been reading {a1} then.', 'until', '', '', 'endpoint', ['until', 'since', 'for', 'during', 'by']),
        ppcQualityItem('The answer is twenty minutes: {a1} had you been studying before the exam?', 'How long', '', '', 'elapsed', ['How long', 'How often', 'What time', 'Since when', 'How many']),
        ppcQualityItem('The team had been testing the system {a1} three weeks before the launch.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('They moved in during 2019 and left in 2021: they had been living there {a1} 2019.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
        ppcQualityItem('On that Tuesday, Mia wrote from breakfast to bedtime: she had been writing {a1} day.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityItem('The report was unfinished at noon: she had been working on it {a1} an hour, not completed it in an hour.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('He started at six and was still writing at eight: he had been writing {a1} six o’clock.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
    ],
    'A2' => [
        ppcQualityItem('The baby had been sleeping {a1} half an hour when the phone rang.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('Nora began practising when she got home: she had been practising {a1} she got home when her friend called.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
        ppcQualityItem('It snowed without a break on Friday night: it had been snowing {a1} night when we woke up.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityItem('Ella stopped baking at eleven and the guests came at twelve: she had been baking {a1} they came.', 'before', '', '', 'prior', ['before', 'after', 'while', 'since', 'as soon as']),
        ppcQualityItem('{a1} the shop finally opened, we had been queuing for forty minutes; we then entered.', 'By the time', '', '', 'deadline', ['By the time', 'Since the time', 'For the time', 'During the time', 'At the time of']),
        ppcQualityItem('The teacher arrived and Jack left the pool: he had been swimming {a1} that moment.', 'until', '', '', 'endpoint', ['until', 'since', 'for', 'during', 'at']),
        ppcQualityItem('We want the total duration, not the start: {a1} had the dog been barking before its owner came outside?', 'How long', '', '', 'elapsed', ['How long', 'How often', 'What time', 'Since when', 'How many']),
        ppcQualityItem('Before her first concert, Nora had been practising the piano {a1} several months.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('The journey began after breakfast: we had been walking {a1} breakfast when we reached the village.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
        ppcQualityItem('The radio played continuously during that one afternoon: it had been playing {a1} afternoon before Dad switched it off.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityItem('Only one wall was ready when Mum arrived: I had been painting {a1} two hours, not finishing the room in two hours.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('Ben ate breakfast every school day before the move. {a1} had he been eating breakfast: daily or weekly?', 'How often', '', '', 'frequency', ['How often', 'How long', 'What time', 'Since when', 'How much']),
    ],
    'B1' => [
        ppcQualityItem('By the customer’s return, the mechanic had been repairing the van {a1} the previous ninety minutes.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('Sam began learning French in March and kept going: he had been learning it {a1} March when he travelled in August.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
        ppcQualityItem('During that single shift, calls never stopped: the volunteers had been answering calls {a1} evening before the system failed.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityItem('Rosa finished moving boxes at ten; her back hurt at eleven. She had been carrying boxes {a1} the pain began.', 'before', '', '', 'prior', ['before', 'after', 'while', 'since', 'as soon as']),
        ppcQualityItem('{a1} the police arrived, music had been coming from the flat for hours; it continued during their visit.', 'By the time', '', '', 'deadline', ['By the time', 'Since the time', 'For the time', 'During the time', 'Until the time']),
        ppcQualityItem('At noon the storm stopped our walk. We had been hiking {a1} then, but not afterwards.', 'until', '', '', 'endpoint', ['until', 'since', 'for', 'during', 'by']),
        ppcQualityItem('The guide wants the elapsed time, not a calendar date: {a1} had they been checking the route before departure?', 'How long', '', '', 'elapsed', ['How long', 'How often', 'Since when', 'What time', 'How many']),
        ppcQualityItem('The neighbours started on 1 March and stopped on 1 June: they had been renovating {a1} three months.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('The first strange noise occurred after Monday’s repair and continued: the printer had been making that noise {a1} Monday.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
        ppcQualityItem('On that one Saturday, Dad cooked continuously from morning to evening: he had been cooking {a1} day before the guests arrived.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityItem('Only half the route was checked by noon: the guide had been checking it {a1} hours, not completed it in hours.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('Three evening sessions a week were normal before the exam: {a1} had Sam been studying?', 'How often', '', '', 'frequency', ['How often', 'How long', 'Since when', 'What time', 'How many']),
    ],
    'B2' => [
        ppcQualityItem('When the project lost funding, development was incomplete: the team had been developing the prototype {a1} eighteen months.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('The analyst began monitoring when the update went live: she had been monitoring continuously {a1} the update went live when the fault appeared.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
        ppcQualityItem('During that single week, rain fell daily without interruption: it had been raining {a1} week before the evacuation.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityItem('The witness stopped receiving calls on Monday; the hearing began on Friday. She had been receiving them {a1} the hearing began.', 'before', '', '', 'prior', ['before', 'after', 'while', 'since', 'as soon as']),
        ppcQualityItem('{a1} mains power returned, the generator had been running for twelve hours; technicians kept it running during the checks.', 'By the time', '', '', 'deadline', ['By the time', 'Since the time', 'For the time', 'During the time', 'Until the time']),
        ppcQualityItem('Recruitment froze on 1 June. The firm had been hiring steadily {a1} that date, but made no appointments afterwards.', 'until', '', '', 'endpoint', ['until', 'since', 'for', 'during', 'at']),
        ppcQualityItem('The audit needs a duration, not a starting date: {a1} had the council been spending money on repairs before the collapse?', 'How long', '', '', 'elapsed', ['How long', 'How often', 'Since when', 'What time', 'How many']),
        ppcQualityItem('Negotiations ran continuously through the entire preceding winter: the delegates had been negotiating {a1} that winter before signing in March.', 'throughout', '', '', 'throughout', ['throughout', 'since', 'until', 'by', 'at']),
        ppcQualityItem('The first warning appeared when installation ended and kept flashing: it had been flashing {a1} installation ended when we reported it.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
        ppcQualityItem('In that one year, repair spending continued every month: the firm had been spending on repairs {a1} year before the review.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityItem('The editor had been cutting the draft {a1} three hours when the author called; only half the required cuts were complete.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('The engine stalled twice per journey before repair: {a1} had it been stalling, rather than how long had each stall lasted?', 'How often', '', '', 'frequency', ['How often', 'How long', 'Since when', 'What time', 'How many']),
    ],
    'C1' => [
        ppcQualityTimeMulti('At disclosure in 2020, investigators had been pursuing the explanation {a1} 2010, meaning {a2} a decade, without reaching a conclusion.', ['since', 'for'], ['start', 'duration']),
        ppcQualityItem('Independent testing began with the pilot study and continued: each laboratory had been investigating the effect {a1} the pilot study when the protocol changed.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
        ppcQualityItem('Demand grew in every month of that one quarter: it had been growing {a1} quarter before the subsidy ended.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityTimeMulti('The March trial triggered reports: they had been arriving {a1} it ended; testing had been going on {a2} it ended, not afterwards.', ['since', 'before'], ['start', 'prior']),
        ppcQualityItem('{a1} the recall was announced, patients had been reporting reactions for a year; reports continued after the announcement.', 'By the time', '', '', 'deadline', ['By the time', 'Since the time', 'For the time', 'During the time', 'Until the time']),
        ppcQualityTimeMulti('Departures began in January and stopped when the contract ended: the firm had been losing staff {a1} January {a2} that endpoint.', ['since', 'until'], ['start', 'endpoint']),
        ppcQualityItem('The inquiry asks for elapsed duration, irrespective of interruptions: {a1} had the alarm been sounding intermittently before the inspection?', 'How long', '', '', 'elapsed', ['How long', 'How often', 'Since when', 'What time', 'How many']),
        ppcQualityItem('The practice persisted during the entire audited decade: factories had been discharging waste {a1} that decade before the ban.', 'throughout', '', '', 'throughout', ['throughout', 'since', 'until', 'by', 'at']),
        ppcQualityItem('The first revision followed the policy’s introduction: it had been evolving {a1} its introduction when the court suspended it.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
        ppcQualityItem('Across that single month of hearings, the talks continued daily: the parties had been negotiating {a1} month before agreement.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityItem('No final report existed at the deadline: the auditors had been investigating {a1} six months, rather than completing the inquiry in six months.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('The audit asks for switching frequency, not total duration: {a1} had the accountants been switching systems before the discrepancy?', 'How often', '', '', 'frequency', ['How often', 'How long', 'Since when', 'What time', 'How many']),
    ],
    'C2' => [
        ppcQualityTimeMulti('At the 2023 review, verification remained incomplete: teams had been testing {a1} 2018, or {a2} five years, not merely during one annual session.', ['since', 'for'], ['start', 'duration']),
        ppcQualityTimeMulti('Convergence began with preliminary exchanges: consensus had been emerging {a1} those exchanges and {a2} the entire negotiation period before the vote exposed its limits.', ['since', 'throughout'], ['start', 'throughout']),
        ppcQualityItem('Within that single decade, reinterpretation never ceased: scholars had been revising the account {a1} decade before the archive opened.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityItem('Officials abandoned the distinction at disclosure. They had been drawing it {a1} disclosure occurred, but neither during nor after disclosure.', 'before', '', '', 'prior', ['before', 'after', 'while', 'since', 'as soon as']),
        ppcQualityTimeMulti('{a1} the archive closed, researchers had been digitising records {a2} eighteen months; remote work continued afterwards, so closure was not the activity’s endpoint.', ['By the time', 'for'], ['deadline', 'duration']),
        ppcQualityTimeMulti('The term’s introduction began a shared usage: parties had been interpreting it consistently {a1} its introduction {a2} the amendment, which ended that consistency.', ['since', 'until'], ['start', 'endpoint']),
        ppcQualityItem('The tribunal needs the total elapsed interval, not the date of the first claim: {a1} had the contractors been claiming compliance before renewal?', 'How long', '', '', 'elapsed', ['How long', 'How often', 'Since when', 'What time', 'How many']),
        ppcQualityItem('Alterations occurred across the entire revision period: successive editors had been changing the scope {a1} that period before publication.', 'throughout', '', '', 'throughout', ['throughout', 'since', 'until', 'by', 'at']),
        ppcQualityItem('Credibility began to increase with the first independent replication: the interpretation had been gaining ground {a1} that replication when the ruling reversed the trend.', 'since', '', '', 'start', ['since', 'for', 'during', 'until', 'by']),
        ppcQualityItem('In that single year, the exchanges repeatedly carried threats: the correspondence had been conveying threats {a1} year before the settlement.', 'all', '', '', 'whole', ['all', 'whole', 'entire', 'every', 'each']),
        ppcQualityItem('Assessment remained unfinished at publication: the panel had been examining submissions {a1} twelve weeks, not completed twelve submissions in twelve weeks.', 'for', '', '', 'duration', ['for', 'since', 'until', 'at', 'by']),
        ppcQualityItem('The issue is recurrence, not duration: {a1} had the committee been contradicting its own decisions before restructuring?', 'How often', '', '', 'frequency', ['How often', 'How long', 'Since when', 'What time', 'How many']),
    ],
];
