<?php

return [
    'A1' => [
        ['До вечері я не працював; я провів цей час відпочиваючи.', 'Przed kolacją nie pracowałem; spędziłem ten czas na odpoczynku.'],
        ['Коли двері відчинилися, вони чекали зовсім недовго: вони прийшли лише хвилину тому.', 'Kiedy otwarto drzwi, nie czekali długo: przyszli zaledwie minutę wcześniej.'],
        ['До приходу вчителя вона не навчалася; її книжки все ще лежали в сумці.', 'Przed przyjściem nauczyciela nie uczyła się; jej książki nadal były w torbie.'],
        ['Ми їхали зовсім недовго, коли машина зупинилася; ми були ще біля дому.', 'Nie jechaliśmy długo, kiedy samochód się zatrzymał; nadal byliśmy blisko domu.'],
        ['Перед уроком діти не розмовляли; усі мовчали.', 'Przed lekcją dzieci nie rozmawiały; wszystkie milczały.'],
        ['До того як відчути втому, Лео не бігав; він залишався в ліжку.', 'Zanim poczuł zmęczenie, Leo nie biegał; pozostawał w łóżku.'],
        ['До обіду Ніна не робила нотаток; її зошит був порожній.', 'Przed obiadem Nina nie robiła notatek; jej zeszyt był pusty.'],
        ['Коли вони знову переїхали, вони жили там зовсім недовго: лише тиждень.', 'Kiedy znowu się przeprowadzili, nie mieszkali tam długo: zaledwie tydzień.'],
        ['До вимкнення світла я не читав; я дивився телевізор.', 'Przed zgaśnięciem światła nie czytałem; oglądałem telewizję.'],
        ['Перш ніж тато знайшов ключ, ми його не шукали; ми вже знали, де він лежить.', 'Zanim tata znalazł klucz, nie szukaliśmy go; już wiedzieliśmy, gdzie jest.'],
        ['До обіду хлопці не грали у футбол; вони весь ранок були в приміщенні.', 'Przed obiadem chłopcy nie grali w piłkę; przez cały ranek byli w domu.'],
        ['Перед поїздкою вона спала погано; вона прокидалася щогодини.', 'Przed podróżą nie spała dobrze; budziła się co godzinę.'],
    ],
    'A2' => [
        ['До приходу медсестри малюк не спав; він не засинав уже кілька годин.', 'Przed przyjściem pielęgniarki dziecko nie spało; było obudzone od wielu godzin.'],
        ['Коли ворота відчинилися, ми стояли в черзі недовго; перед нами було лише двоє людей.', 'Kiedy otwarto bramę, nie staliśmy w kolejce długo; przed nami były tylko dwie osoby.'],
        ['Перед концертом Том не тренувався грати на піаніно; він провів тиждень у подорожі.', 'Przed koncertem Tom nie ćwiczył gry na pianinie; spędził tydzień w podróży.'],
        ['До початку дощу група йшла недовго; станцію ще було видно.', 'Przed rozpoczęciem deszczu grupa nie szła długo; stacja nadal była widoczna.'],
        ['Поки ми не прокинулися, собака не гавкав; у будинку було тихо.', 'Zanim się obudziliśmy, pies nie szczekał; w domu było cicho.'],
        ['До приходу друзів Елла нічого не пекла; усі тістечка були з крамниці.', 'Przed przyjściem przyjaciół Ella nie piekła; wszystkie ciasta były ze sklepu.'],
        ['До уроку Джек не плавав; його купальний костюм залишався сухим.', 'Przed lekcją Jack nie pływał; jego strój kąpielowy nadal był suchy.'],
        ['Коли школу закрили, сніг ішов недовго; стежку вкривало зовсім мало снігу.', 'Kiedy zamknięto szkołę, śnieg nie padał długo; ścieżkę pokrywało go niewiele.'],
        ['До сніданку радіо не грало; ніхто його не вмикав.', 'Przed śniadaniem radio nie grało; nikt go nie włączył.'],
        ['До приходу мами я не прибирав кімнату; натомість я робив домашнє завдання.', 'Przed przyjściem mamy nie sprzątałem pokoju; zamiast tego odrabiałem lekcje.'],
        ['До нашої зустрічі Роза не плакала; її очі почервоніли від пилу.', 'Przed naszym spotkaniem Rosa nie płakała; jej oczy były czerwone od kurzu.'],
        ['Перед забігом Бен погано харчувався; він пропускав більшість прийомів їжі.', 'Przed biegiem Ben nie odżywiał się dobrze; opuszczał większość posiłków.'],
    ],
    'B1' => [
        ['До повернення власника механік не ремонтував фургон; інструменти залишалися замкненими.', 'Przed powrotem właściciela mechanik nie naprawiał furgonetki; narzędzia pozostawały zamknięte.'],
        ['Коли система зламалася, я відповідав на дзвінки недовго; моя зміна щойно почалася.', 'Kiedy system przestał działać, nie odbierałem telefonów długo; moja zmiana dopiero się zaczęła.'],
        ['До подорожі Сем не вивчав французьку; він лише запам’ятав кілька фраз того ранку.', 'Przed podróżą Sam nie uczył się francuskiego; zapamiętał tylko kilka zwrotów tego ranka.'],
        ['Коли ми дісталися озера, похід тривав недовго, хоча ми вже були виснажені.', 'Kiedy dotarliśmy do jeziora, nie wędrowaliśmy długo, choć już czuliśmy się wyczerpani.'],
        ['До ремонту принтер не видавав тих звуків; вони з’явилися лише після відходу майстра.', 'Przed naprawą drukarka nie wydawała tych dźwięków; zaczęły się dopiero po wyjściu technika.'],
        ['До сигналу тривоги тато не готував; дим ішов із сусідньої квартири.', 'Przed alarmem tata nie gotował; dym pochodził z mieszkania sąsiada.'],
        ['До появи болю в спині Роза не переносила коробок; вона сиділа за столом.', 'Zanim zaczęły ją boleć plecy, Rosa nie przenosiła pudeł; siedziała przy biurku.'],
        ['Коли в сусідів закінчилися гроші, ремонт тривав недовго; змінилася лише одна кімната.', 'Kiedy sąsiadom skończyły się pieniądze, nie remontowali długo; zmienił się tylko jeden pokój.'],
        ['До бурі вода крізь стелю не просочувалася; це протікання було зовсім новим.', 'Przed burzą woda nie przedostawała się przez sufit; ten przeciek był całkiem nowy.'],
        ['До того походу гід не перевіряла маршрут регулярно; її мапа була багаторічної давнини.', 'Przed tą wycieczką przewodniczka nie sprawdzała trasy regularnie; jej mapa była sprzed wielu lat.'],
        ['До пошкодження газону діти надворі не грали; по ньому проїхали робітники.', 'Zanim uszkodzono trawnik, dzieci nie bawiły się na zewnątrz; przejechali po nim robotnicy.'],
        ['До госпіталізації пацієнт погано харчувався, хоча щодня йому вдавалося трохи поїсти.', 'Przed przyjęciem do szpitala pacjent nie odżywiał się dobrze, choć codziennie udawało mu się trochę zjeść.'],
    ],
    'B2' => [
        ['До розгляду команда не розробляла нового проєкту; вона лише повторно використала старий прототип.', 'Przed przeglądem zespół nie opracowywał nowego projektu; wykorzystał jedynie stary prototyp.'],
        ['Коли з’явилася аномалія, аналітикиня відстежувала потік недовго, тому не мала надійної бази для порівняння.', 'Kiedy pojawiła się anomalia, analityczka nie monitorowała strumienia długo, więc nie miała wiarygodnego punktu odniesienia.'],
        ['До відкриття дамби рівень річки не піднімався; попередні виміри не показували руху вгору.', 'Przed otwarciem zapory poziom rzeki nie rósł; wcześniejsze odczyty nie wskazywały wzrostu.'],
        ['До звернення в поліцію свідок отримувала погрозливі дзвінки недовго; перший надійшов того ж дня.', 'Przed zgłoszeniem się na policję świadek nie otrzymywała telefonów z groźbami długo; pierwszy nastąpił tego samego dnia.'],
        ['До усунення несправності генератор не гудів; він зовсім не видавав звуку.', 'Przed usunięciem usterki generator nie buczał; pozostawał zupełnie cichy.'],
        ['Під час зміни вона не кричала; причиною захриплості була інфекція.', 'Podczas zmiany nie krzyczała; jej chrypka była skutkiem infekcji.'],
        ['До дзвінка автора редактор не вилучав абзаців; чернетка була точнісінько такою, як її подали.', 'Przed telefonem autora redaktor nie usuwał akapitów; szkic pozostawał dokładnie taki jak w chwili złożenia.'],
        ['Коли набір заморозили, фірма наймала працівників недовго; кампанія почалася лише кілька днів тому.', 'Kiedy zamrożono rekrutację, firma nie zatrudniała pracowników długo; kampania zaczęła się zaledwie kilka dni wcześniej.'],
        ['До оновлення попередження не блимало; уперше воно з’явилося після встановлення.', 'Przed aktualizacją ostrzeżenie nie migało; pojawiło się po raz pierwszy po instalacji.'],
        ['До угоди ми не вели переговорів із тим постачальником; усі обговорення провадив агент.', 'Przed umową nie negocjowaliśmy z tym dostawcą; wszystkie rozmowy prowadził agent.'],
        ['До обвалу рада не витрачала гроші на ремонт; бюджет технічного обслуговування залишався недоторканим.', 'Przed zawaleniem rada nie wydawała pieniędzy na naprawy; budżet utrzymania pozostawał nietknięty.'],
        ['До поломки двигун працював погано; він неодноразово глухнув, хоча між цими зупинками ще працював.', 'Przed awarią silnik nie pracował dobrze; wielokrotnie gasł, choć działał pomiędzy tymi przerwami.'],
    ],
    'C1' => [
        ['До появи матеріалів слідчі не розглядали справу як нещасний випадок; їхнім робочим припущенням було навмисне втручання.', 'Przed ujawnieniem akt śledczy nie traktowali sprawy jako wypadku; ich roboczym założeniem była celowa ingerencja.'],
        ['До зміни методів за спільним протоколом лабораторії незалежно досліджували ефект недовго.', 'Zanim wspólny protokół zmienił ich metody, laboratoria nie badały efektu niezależnie od dawna.'],
        ['До субсидії попит не зростав; уявне попереднє збільшення було статистичним виправленням, а не тенденцією.', 'Przed subsydium popyt nie rósł; rzekomy wcześniejszy wzrost był korektą statystyczną, nie trendem.'],
        ['До відкликання препарату пацієнти повідомляли про реакції недовго, хоча препарат був доступний роками.', 'Przed wycofaniem leku pacjenci nie zgłaszali reakcji długo, choć lek był dostępny od lat.'],
        ['Під час слухань неформальні переговори не тривали; обидві сторони призупинили контакт ще до їхнього початку.', 'Podczas rozpraw nieformalne rozmowy nie trwały; obie strony zawiesiły kontakt przed ich rozpoczęciem.'],
        ['До зриву контракту фірма не втрачала працівників; чисельність персоналу залишалася сталою протягом усіх переговорів.', 'Przed zerwaniem kontraktu firma nie traciła pracowników; liczebność załogi pozostawała stała przez całe negocjacje.'],
        ['До появи розбіжності аудитори не перемикалися між системами; вони послідовно застосовували один метод.', 'Zanim pojawiła się rozbieżność, audytorzy nie przełączali się między systemami; konsekwentnie stosowali jedną metodę.'],
        ['Коли судовий перегляд перервав поступовий розвиток політики, вона змінювалася ще недовго.', 'Kiedy kontrola sądowa przerwała stopniowy rozwój polityki, nie ewoluowała ona od dawna.'],
        ['До перевірки сигналізація не звучала; пізніше тестування спричинило перше звукове попередження.', 'Przed kontrolą alarm się nie odzywał; późniejsze testy wywołały pierwsze słyszalne ostrzeżenie.'],
        ['До аварійного витоку заводи не скидали відходи в естуарій; забруднення виникло через одну несправність сховища.', 'Przed wyciekiem fabryki nie odprowadzały odpadów do estuarium; skażenie wynikało z jednej awarii magazynu.'],
        ['До тієї промови коментатори не подавали дискусію як двійковий вибір; їхні попередні пояснення розрізняли кілька позицій.', 'Przed tym przemówieniem komentatorzy nie przedstawiali debaty jako wyboru binarnego; wcześniejsze relacje rozróżniały kilka stanowisk.'],
        ['До посередництва учасники спілкувалися погано: контактували часто, але їхні повідомлення раз у раз спричиняли непорозуміння.', 'Przed mediacją uczestnicy nie komunikowali się dobrze: kontakt był częsty, lecz ich wiadomości wielokrotnie powodowały nieporozumienia.'],
    ],
    'C2' => [
        ['До витоку посадовці не подавали оцінку як установлений факт; кожен брифінг називав її попередньою.', 'Przed wyciekiem urzędnicy nie przedstawiali szacunku jako ustalonego faktu; każdy briefing określał go jako wstępny.'],
        ['До розколу уявна згода формувалася недовго; пізня поступка зблизила позиції лише ненадовго.', 'Zanim pozorny konsensus się rozpadł, nie kształtował się długo; późne ustępstwo zbliżyło stanowiska tylko na krótko.'],
        ['До відкриття архіву історики не перевіряли ту версію; вони приймали її, не намагаючись перевірити.', 'Przed otwarciem archiwum historycy nie sprawdzali tej relacji; przyjmowali ją bez próby weryfikacji.'],
        ['До відмови від розмежування колегія проводила його недовго, хоча називала його усталеною традицією.', 'Przed porzuceniem tego rozróżnienia panel nie stosował go długo, choć opisywał je jako utrwaloną tradycję.'],
        ['До голосування група не вивчала практичних наслідків; вона обмежувала обговорення абстрактними принципами.', 'Przed głosowaniem grupa nie badała praktycznych konsekwencji; ograniczała dyskusję do abstrakcyjnych zasad.'],
        ['До публікації редактори не змінювали охоплення тексту; суперечності вже були в першій чернетці.', 'Przed publikacją redaktorzy nie zmieniali zakresu tekstu; niespójności były obecne już w pierwszym szkicu.'],
        ['До закриття архіву дослідники не переносили документи; дозволу на оцифрування їм ніколи не надали.', 'Przed zamknięciem archiwum badacze nie przenosili dokumentów; nigdy nie udzielono im zgody na digitalizację.'],
        ['Коли судове рішення розвернуло коротку тенденцію до зростання, тлумачення набувало переконливості ще недовго.', 'Kiedy orzeczenie odwróciło krótki trend wzrostowy, interpretacja nie zyskiwała wiarygodności od dawna.'],
        ['До врегулювання листування не передавало погроз; пізніше прочитання приписало початковим повідомленням відсутній у них намір.', 'Przed ugodą korespondencja nie przekazywała gróźb; późniejsza interpretacja narzuciła pierwotnym wymianom nieobecny w nich zamiar.'],
        ['До поновлення підрядники не заявляли про повну відповідність; їхні повторні звіти прямо визнавали неусунені порушення.', 'Przed odnowieniem wykonawcy nie deklarowali pełnej zgodności; ich kolejne raporty wyraźnie przyznawały istnienie nierozwiązanych naruszeń.'],
        ['До поправки сторони не тлумачили термін по-різному; неоднозначність виникла лише після зміни формулювання.', 'Przed poprawką strony nie interpretowały terminu różnie; niejednoznaczność powstała dopiero po zmianie brzmienia.'],
        ['До реорганізації комітет функціонував погано: засідав регулярно, але його рішення раз у раз суперечили одне одному.', 'Przed reorganizacją komitet nie funkcjonował dobrze: spotykał się regularnie, lecz jego decyzje wielokrotnie sobie przeczyły.'],
    ],
];
