<?php

return [
    'A1' => [
        ['Ти працював уже дві години до вечері?', 'Czy przed kolacją pracowałeś już od dwóch godzin?'],
        ['Коли приїхав автобус, вона чекала ще зранку?', 'Czy kiedy przyjechał autobus, czekała już od rana?'],
        ['До приходу вчителя вони навчалися вже двадцять хвилин?', 'Czy przed przyjściem nauczyciela uczyli się już od dwudziestu minut?'],
        ['Що він робив перед обідом: читав чи малював?', 'Co robił przed obiadem: czytał czy rysował?'],
        ['Як довго ти їхав автомобілем до першої зупинки: годину чи дві?', 'Jak długo jechałeś samochodem przed pierwszym postojem: godzinę czy dwie?'],
        ['Ти чекав уже годину. Я запитав: «Ти довго чекав?» Ти відповів: «Так, довго».', 'Czekałeś już od godziny. Zapytałem: „Czy czekałeś długo?” Odpowiedziałeś: „Tak”.'],
        ['Мія весь ранок робила нотатки до обіду?', 'Czy Mia robiła notatki przez cały ranek przed obiadem?'],
        ['Де вони жили до переїзду: у Києві чи у Львові?', 'Gdzie mieszkali przed przeprowadzką: w Kijowie czy we Lwowie?'],
        ['Як довго він читав, коли згасло світло: десять хвилин чи годину?', 'Jak długo czytał, kiedy zgasło światło: dziesięć minut czy godzinę?'],
        ['Ти шукав ключ, перш ніж тато його знайшов?', 'Czy szukałeś klucza, zanim tata go znalazł?'],
        ['Хлопці весь ранок були в приміщенні. Вони грали надворі до обіду? — Ні.', 'Chłopcy przez cały ranek byli w domu. Czy przed obiadem grali na zewnątrz? — Nie.'],
        ['Вона добре спала перед поїздкою?', 'Czy dobrze spała przed podróżą?'],
    ],
    'A2' => [
        ['Малюк спав уже годину, коли подзвонили у двері?', 'Czy dziecko spało już od godziny, kiedy zadzwonił dzwonek do drzwi?'],
        ['Ви обоє довго стояли в черзі, коли крамниця відкрилася?', 'Czy oboje długo staliście w kolejce, kiedy otwarto sklep?'],
        ['Нора весь вечір відпрацьовувала ту пісню перед концертом?', 'Czy Nora przez cały wieczór ćwiczyła tę piosenkę przed koncertem?'],
        ['Де Бен чекав до прибуття поїзда: на станції чи надворі?', 'Gdzie Ben czekał przed przyjazdem pociągu: na stacji czy na zewnątrz?'],
        ['Як довго ти йшов до села: п’ять хвилин чи годину?', 'Jak długo szedłeś, zanim dotarłeś do wsi: pięć minut czy godzinę?'],
        ['Джек уже був мокрий після години в басейні. Він плавав перед уроком? — Так.', 'Jack był już mokry po godzinie w basenie. Czy pływał przed lekcją? — Tak.'],
        ['Елла весь ранок пекла хліб до приходу гостей?', 'Czy Ella piekła chleb przez cały ranek przed przyjściem gości?'],
        ['Що грало по радіо до твого приходу: музика чи новини?', 'Co radio nadawało przed twoim przyjściem: muzykę czy wiadomości?'],
        ['Як довго ти прибирав до приходу гостей: пів години чи дві години?', 'Jak długo sprzątałeś przed przyjściem gości: pół godziny czy dwie godziny?'],
        ['Коли ти прокинувся, сніг ішов уже всю ніч?', 'Czy kiedy się obudziłeś, śnieg padał już przez całą noc?'],
        ['Очі Рози почервоніли від пилу, а не сліз. Вона плакала до нашої зустрічі? — Ні.', 'Oczy Rosy były czerwone od kurzu, nie od łez. Czy płakała przed naszym spotkaniem? — Nie.'],
        ['Бен достатньо харчувався перед забігом?', 'Czy Ben jadł wystarczająco dużo przed biegiem?'],
    ],
    'B1' => [
        ['Коли клієнт повернувся, механік ремонтував двигун уже годину?', 'Czy kiedy klient wrócił, mechanik naprawiał silnik już od godziny?'],
        ['Кожен волонтер регулярно відповідав на дзвінки до збою системи?', 'Czy każdy wolontariusz regularnie odbierał telefony przed awarią systemu?'],
        ['Сем місяцями вивчав французьку перед першою закордонною подорожжю?', 'Czy Sam przez wiele miesięcy uczył się francuskiego przed pierwszą podróżą za granicę?'],
        ['Чому Роза навчалася до обіду, якщо вона не готувалася до іспиту?', 'Dlaczego Rosa uczyła się przed obiadem, jeśli nie przygotowywała się do egzaminu?'],
        ['Як довго вони йшли в похід до того, як знайшли укриття: сорок хвилин чи довше?', 'Jak długo wędrowali, zanim znaleźli schronienie: czterdzieści minut czy dłużej?'],
        ['До сигналу тривоги тато провів годину біля плити. Він готував? — Так.', 'Przed alarmem tata spędził godzinę przy kuchence. Czy gotował? — Tak.'],
        ['Роза переносила важкі коробки до того, як у неї заболіла спина?', 'Czy Rosa przenosiła ciężkie pudła, zanim zaczęły ją boleć plecy?'],
        ['Де Мія тренувалася до уроку: на кухні чи в спальні?', 'Gdzie Mia ćwiczyła przed lekcją: w kuchni czy w sypialni?'],
        ['Як довго сусіди ремонтували будинок до зупинки робіт у червні: з березня чи лише з травня?', 'Jak długo sąsiedzi remontowali dom przed przerwaniem prac w czerwcu: od marca czy dopiero od maja?'],
        ['Гід тижнями перевіряла маршрут до прибуття групи?', 'Czy przewodniczka przez wiele tygodni sprawdzała trasę przed przybyciem grupy?'],
        ['Діти залишалися в приміщенні; газон пошкодили робітники. Діти грали надворі? — Ні.', 'Dzieci pozostały w domu; trawnik uszkodzili robotnicy. Czy dzieci bawiły się na zewnątrz? — Nie.'],
        ['Медсестра запитала, чи пацієнт добре харчувався до госпіталізації.', 'Pielęgniarka zapytała, czy pacjent dobrze się odżywiał przed przyjęciem do szpitala.'],
    ],
    'B2' => [
        ['Коли фінансування припинилося, команда вже місяцями розробляла прототип чи розробку вже завершили?', 'Czy kiedy finansowanie się skończyło, zespół od miesięcy opracowywał prototyp, czy prace były już ukończone?'],
        ['До появи аномалії аналітикиня відстежувала потік достатньо довго, щоб розпізнати нормальний шаблон?', 'Czy przed pojawieniem się anomalii analityczka monitorowała strumień wystarczająco długo, aby rozpoznać normalny wzorzec?'],
        ['Рівень річки невпинно піднімався до відкриття дамби чи підвищення почалося лише потім?', 'Czy poziom rzeki stale rósł przed otwarciem zapory, czy wzrost zaczął się dopiero później?'],
        ['Чому вона отримувала ті дзвінки перед слуханням, якщо ніхто не передавав її номер пресі?', 'Dlaczego otrzymywała te telefony przed rozprawą, jeśli nikt nie podał jej numeru prasie?'],
        ['Як довго генератор гудів до відновлення електропостачання: одну ніч чи кілька?', 'Jak długo generator buczał przed przywróceniem zasilania: jedną noc czy kilka?'],
        ['Редакторка весь ранок неодноразово вилучала абзаци. Вона скорочувала чернетку до обіду? — Так.', 'Redaktorka przez cały ranek wielokrotnie usuwała akapity. Czy skracała szkic przed obiadem? — Tak.'],
        ['Вона перекрикувала шум обладнання до того, як захрипла?', 'Czy przekrzykiwała maszyny, zanim zachrypła?'],
        ['Де делегати вели переговори перед підписанням: особисто чи онлайн?', 'Gdzie delegaci negocjowali przed podpisaniem: osobiście czy online?'],
        ['Слідчий запитав, як довго фірма наймала працівників до замороження набору.', 'Śledczy zapytał, jak długo firma zatrudniała pracowników przed zamrożeniem rekrutacji.'],
        ['Хіба світло не блимало до оновлення, попри пізнішу заяву, що це було нове попередження?', 'Czy światło nie migało przed aktualizacją, pomimo późniejszego twierdzenia, że było to nowe ostrzeżenie?'],
        ['Бюджет технічного обслуговування залишався недоторканим. Рада витрачала гроші на ремонт до обвалу? — Ні.', 'Budżet utrzymania pozostawał nietknięty. Czy rada wydawała pieniądze na naprawy przed zawaleniem? — Nie.'],
        ['Можеш пояснити, чому двигун працював погано до поломки?', 'Czy możesz wyjaśnić, dlaczego silnik źle pracował przed awarią?'],
    ],
    'C1' => [
        ['Слідчі розглядали справу як випадковість до того, як документи поставили це припущення під сумнів?', 'Czy śledczy traktowali sprawę jako przypadek, zanim dokumenty podważyły to założenie?'],
        ['Кожна лабораторія незалежно досліджувала ефект до того, як спільний протокол замінив їхні методи?', 'Czy każde laboratorium niezależnie badało efekt, zanim wspólny protokół zastąpił ich metody?'],
        ['Попит невпинно зростав до субсидії чи уявна тенденція була лише статистичним виправленням?', 'Czy popyt stale rósł przed subsydium, czy pozorny trend był jedynie korektą statystyczną?'],
        ['Чому пацієнти повідомляли про небажані реакції до відкликання, якщо попередні підсумки не повідомляли про жодну?', 'Dlaczego pacjenci zgłaszali działania niepożądane przed wycofaniem leku, skoro wcześniejsze podsumowania nie odnotowywały żadnych?'],
        ['Голова хотів знати, як довго неформальні переговори тривали за лаштунками до публічних слухань.', 'Przewodniczący chciał wiedzieć, jak długo nieformalne rozmowy trwały za kulisami przed publicznymi rozprawami.'],
        ['Документи з оплати праці показували постійний відхід досвідчених працівників до скасування. Фірма втрачала персонал? — Так.', 'Dokumenty płacowe wykazywały stałe odchodzenie doświadczonych pracowników przed anulowaniem. Czy firma traciła personel? — Tak.'],
        ['Аудитори перемикалися між системами обліку до появи розбіжності замість дотримуватися одного методу?', 'Czy audytorzy przełączali się między systemami księgowymi przed wystąpieniem rozbieżności, zamiast stosować jedną metodę?'],
        ['Під час розслідування запитали, куди заводи скидали відходи до заборони.', 'W dochodzeniu zapytano, gdzie fabryki odprowadzały odpady przed zakazem.'],
        ['Як довго сигналізація звучала до того, як інженери знайшли несправність: із перервами кілька годин чи лише раз?', 'Jak długo alarm się odzywał, zanim inżynierowie znaleźli usterkę: z przerwami przez wiele godzin czy tylko raz?'],
        ['Хіба політика не змінювалася поступово до судового перегляду, попри офіційну заяву про цілковиту стабільність?', 'Czy polityka nie zmieniała się stopniowo przed kontrolą sądową, mimo oficjalnego twierdzenia o pełnej stabilności?'],
        ['Попередні коментарі розрізняли кілька позицій, а не дві. Коментатори подавали дискусію як двійковий вибір до промови? — Ні.', 'Wcześniejsze komentarze rozróżniały kilka stanowisk, nie dwa. Czy komentatorzy przedstawiali debatę jako binarną przed przemówieniem? — Nie.'],
        ['Посередниця запитала, чому сторони так погано спілкувалися до її призначення, хоча зустрічалися регулярно.', 'Mediatorka zapytała, dlaczego strony tak słabo się komunikowały przed jej powołaniem, choć spotykały się regularnie.'],
    ],
    'C2' => [
        ['Послідовні брифінги неодноразово подавали оцінку як установлений факт до виправлення чи постійно називали її попередньою?', 'Czy kolejne briefingi wielokrotnie przedstawiały szacunek jako ustalony fakt przed sprostowaniem, czy konsekwentnie nazywały go wstępnym?'],
        ['Під час перевірки запитали, чи згода поступово формувалася до голосування, а не виникла за одні переговори.', 'W przeglądzie zapytano, czy konsensus stopniowo wyłaniał się przed głosowaniem, zamiast pojawić się podczas jednych negocjacji.'],
        ['Історики перевіряли версію за непрямими свідченнями до відкриття архіву чи приймали її без перевірки?', 'Czy historycy sprawdzali relację na podstawie pośrednich dowodów przed otwarciem archiwum, czy przyjmowali ją bez weryfikacji?'],
        ['Чому посадовці проводили те розмежування до розкриття інформації і на якій підставі вважали його юридично значущим?', 'Dlaczego urzędnicy wprowadzali to rozróżnienie przed ujawnieniem informacji i na jakiej podstawie uznawali je za prawnie istotne?'],
        ['Звіт не встановив, як довго група вивчала практичні наслідки до переходу до абстрактних принципів.', 'Raport nie ustalił, jak długo grupa badała praktyczne konsekwencje przed przejściem do abstrakcyjnych zasad.'],
        ['Послідовні правки розширювали, а потім звужували охоплення до публікації. Редактори його змінювали? — Так.', 'Kolejne poprawki rozszerzały, a następnie zawężały zakres przed publikacją. Czy redaktorzy go zmieniali? — Tak.'],
        ['Хто переносив крихкі документи до закриття архіву: самі куратори чи зовнішній підрядник?', 'Kto przenosił delikatne dokumenty przed zamknięciem archiwum: sami kuratorzy czy zewnętrzny wykonawca?'],
        ['Трибунал запитав, де підрядники давали такі запевнення до поновлення, адже письмові звіти визнавали порушення.', 'Trybunał zapytał, gdzie wykonawcy składali takie zapewnienia przed odnowieniem, skoro pisemne raporty przyznawały naruszenia.'],
        ['Як довго тлумачення набувало переконливості до того, як рішення розвернуло тенденцію, незалежно від його формального схвалення?', 'Jak długo interpretacja zyskiwała wiarygodność przed odwróceniem trendu przez orzeczenie, niezależnie od tego, czy kiedykolwiek ją formalnie poparto?'],
        ['Хіба листування не передавало погроз до врегулювання, усупереч пізнішому опису його як просто звичайного?', 'Czy korespondencja nie przekazywała gróźb przed ugodą, wbrew późniejszemu określeniu jej jako jedynie rutynowej?'],
        ['Спільне визначення залишалося незмінним до поправки. Сторони тлумачили термін по-різному до неї? — Ні.', 'Wspólna definicja pozostawała niezmieniona do poprawki. Czy strony wcześniej interpretowały termin różnie? — Nie.'],
        ['Під час розслідування запитали, як комітет функціонував до реорганізації, розрізняючи регулярні засідання й узгоджене ухвалення рішень.', 'W dochodzeniu zapytano, jak komitet funkcjonował przed reorganizacją, rozróżniając regularne spotkania i spójne podejmowanie decyzji.'],
    ],
];
