<?php

return [
    'A1' => [
        ['Коли двері відчинилися, вони чекали вже дві години.', 'Kiedy otwarto drzwi, czekali już od dwóch godzin.'],
        ['Вона почала працювати о дев’ятій і ще працювала опівдні: на той час вона працювала з дев’ятої.', 'Zaczęła pracować o dziewiątej i nadal pracowała w południe: pracowała już od dziewiątej.'],
        ['Того понеділка він біг без перерви від світанку до полудня: він бігав увесь ранок.', 'W tamten poniedziałek biegał bez przerwy od świtu do południa: biegał przez cały ranek.'],
        ['Ми закінчили готувати опівдні, а вечеря почалася о першій. Ми готували до початку вечері.', 'Skończyliśmy przygotowania w południe, a kolacja zaczęła się o pierwszej. Przygotowywaliśmy ją przed rozpoczęciem kolacji.'],
        ['На той момент, коли ми прибули опівдні, дощ ішов уже кілька годин; він тривав і потім.', 'W chwili, gdy przybyliśmy w południe, deszcz padał już od wielu godzin; padał również później.'],
        ['Пролунав дзвінок, і я перестав читати. Я читав до того моменту.', 'Zadzwonił dzwonek i przestałem czytać. Czytałem do tamtej chwili.'],
        ['Відповідь — двадцять хвилин: як довго ти навчався перед іспитом?', 'Odpowiedź brzmi: dwadzieścia minut. Jak długo uczyłeś się przed egzaminem?'],
        ['До запуску команда тестувала систему вже три тижні.', 'Przed uruchomieniem zespół testował system już od trzech tygodni.'],
        ['Вони оселилися там у 2019 році й виїхали у 2021: на той час вони жили там із 2019 року.', 'Wprowadzili się tam w 2019 roku i wyjechali w 2021: mieszkali tam od 2019 roku.'],
        ['Того вівторка Мія писала від сніданку до сну: вона писала весь день.', 'W tamten wtorek Mia pisała od śniadania do pory snu: pisała przez cały dzień.'],
        ['Опівдні звіт був незавершений: вона працювала над ним уже годину, а не завершила його за годину.', 'W południe raport był nieukończony: pracowała nad nim od godziny, a nie ukończyła go w godzinę.'],
        ['Він почав о шостій і ще писав о восьмій: на той час він писав із шостої години.', 'Zaczął o szóstej i nadal pisał o ósmej: pisał już od szóstej.'],
    ],
    'A2' => [
        ['Коли задзвонив телефон, малюк спав уже пів години.', 'Kiedy zadzwonił telefon, dziecko spało już od pół godziny.'],
        ['Нора почала тренуватися після повернення додому: коли подзвонила подруга, вона тренувалася від самого повернення.', 'Nora zaczęła ćwiczyć po powrocie do domu: kiedy zadzwoniła przyjaciółka, ćwiczyła już od powrotu.'],
        ['У п’ятницю вночі сніг ішов без перерви: коли ми прокинулися, він ішов уже всю ніч.', 'W piątkową noc śnieg padał bez przerwy: kiedy się obudziliśmy, padał już przez całą noc.'],
        ['Елла закінчила пекти об одинадцятій, а гості прийшли о дванадцятій: вона пекла ще до їхнього приходу.', 'Ella skończyła piec o jedenastej, a goście przyszli o dwunastej: piekła przed ich przyjściem.'],
        ['На той момент, коли крамниця нарешті відкрилася, ми стояли в черзі вже сорок хвилин; тоді ми зайшли.', 'W chwili, gdy sklep wreszcie otwarto, staliśmy w kolejce już od czterdziestu minut; następnie weszliśmy.'],
        ['Учитель прийшов, і Джек вийшов із басейну: він плавав до того моменту.', 'Nauczyciel przyszedł i Jack wyszedł z basenu: pływał do tamtej chwili.'],
        ['Нас цікавить загальна тривалість, а не початок: як довго собака гавкав до виходу господаря надвір?', 'Chcemy poznać łączny czas trwania, nie początek: jak długo pies szczekał przed wyjściem właściciela na zewnątrz?'],
        ['Перед першим концертом Нора тренувалася грати на піаніно вже кілька місяців.', 'Przed pierwszym koncertem Nora ćwiczyła grę na pianinie już od kilku miesięcy.'],
        ['Подорож почалася після сніданку: коли ми дісталися села, ми йшли ще від сніданку.', 'Podróż zaczęła się po śniadaniu: kiedy dotarliśmy do wsi, szliśmy już od śniadania.'],
        ['Протягом саме того пообіддя радіо грало безперервно: воно грало все пообіддя до того, як тато його вимкнув.', 'Podczas tamtego jednego popołudnia radio grało bez przerwy: grało przez całe popołudnie, zanim tata je wyłączył.'],
        ['Коли мама прийшла, була готова лише одна стіна: я фарбував уже дві години, а не завершив кімнату за дві години.', 'Kiedy mama przyszła, gotowa była tylko jedna ściana: malowałem od dwóch godzin, a nie skończyłem pokój w dwie godziny.'],
        ['До переїзду Бен снідав кожного навчального дня. Як часто він снідав: щодня чи щотижня?', 'Przed przeprowadzką Ben jadł śniadanie każdego dnia szkolnego. Jak często jadł śniadanie: codziennie czy co tydzień?'],
    ],
    'B1' => [
        ['На момент повернення клієнта механік ремонтував фургон протягом попередніх дев’яноста хвилин.', 'W chwili powrotu klienta mechanik naprawiał furgonetkę przez poprzednie dziewięćdziesiąt minut.'],
        ['Сем почав учити французьку в березні й продовжував: коли він поїхав у серпні, він учив її ще з березня.', 'Sam zaczął uczyć się francuskiego w marcu i kontynuował: kiedy wyjechał w sierpniu, uczył się już od marca.'],
        ['Протягом саме тієї зміни дзвінки не припинялися: до збою системи волонтери відповідали на них уже весь вечір.', 'Podczas tamtej jednej zmiany telefony nie milkły: przed awarią systemu wolontariusze odbierali je już przez cały wieczór.'],
        ['Роза закінчила переносити коробки о десятій; спина заболіла об одинадцятій. Вона переносила коробки до появи болю.', 'Rosa skończyła przenosić pudła o dziesiątej; plecy zabolały ją o jedenastej. Przenosiła pudła przed pojawieniem się bólu.'],
        ['На той момент, коли поліція приїхала, музика лунала з квартири вже кілька годин; вона не припинилася під час візиту.', 'W chwili przyjazdu policji muzyka dochodziła z mieszkania już od wielu godzin; trwała podczas ich wizyty.'],
        ['Опівдні буря зупинила наш похід. Ми йшли до того моменту, але не після нього.', 'W południe burza przerwała naszą wędrówkę. Wędrowaliśmy do tamtej chwili, ale nie później.'],
        ['Гід хоче знати минулу тривалість, а не календарну дату: як довго вони перевіряли маршрут до від’їзду?', 'Przewodnik chce poznać czas trwania, nie datę: jak długo sprawdzali trasę przed wyjazdem?'],
        ['Сусіди почали 1 березня й зупинилися 1 червня: вони ремонтували будинок три місяці.', 'Sąsiedzi zaczęli 1 marca i przerwali 1 czerwca: remontowali przez trzy miesiące.'],
        ['Перший дивний звук з’явився після ремонту в понеділок і не зникав: принтер видавав його від понеділка.', 'Pierwszy dziwny dźwięk pojawił się po poniedziałkowej naprawie i nie ustawał: drukarka wydawała go od poniedziałku.'],
        ['Тієї однієї суботи тато готував безперервно від ранку до вечора: до приходу гостей він готував уже весь день.', 'W tamtą jedną sobotę tata gotował bez przerwy od rana do wieczora: przed przyjściem gości gotował już przez cały dzień.'],
        ['До полудня перевірили лише половину маршруту: гід перевіряла його годинами, а не завершила перевірку за кілька годин.', 'Do południa sprawdzono tylko połowę trasy: przewodniczka sprawdzała ją przez wiele godzin, a nie ukończyła kontroli w kilka godzin.'],
        ['До іспиту зазвичай було три вечірні заняття на тиждень: як часто Сем навчався?', 'Przed egzaminem normą były trzy wieczorne sesje tygodniowo: jak często Sam się uczył?'],
    ],
    'B2' => [
        ['Коли проєкт втратив фінансування, розробка була незавершена: команда розробляла прототип уже вісімнадцять місяців.', 'Kiedy projekt stracił finansowanie, prace były nieukończone: zespół opracowywał prototyp już od osiemnastu miesięcy.'],
        ['Аналітикиня почала відстежувати потік, коли оновлення запрацювало: на момент появи несправності вона відстежувала його безперервно від запуску оновлення.', 'Analityczka zaczęła monitorować strumień, kiedy aktualizacja zaczęła działać: gdy pojawiła się usterka, monitorowała go bez przerwy od uruchomienia aktualizacji.'],
        ['Саме того тижня дощ ішов щодня без перерви: до евакуації він ішов уже весь тиждень.', 'W tamtym jednym tygodniu deszcz padał codziennie bez przerwy: przed ewakuacją padał już przez cały tydzień.'],
        ['Свідок перестала отримувати дзвінки в понеділок, а слухання почалося в п’ятницю. Вона отримувала їх ще до початку слухання.', 'Świadek przestała otrzymywać telefony w poniedziałek, a rozprawa zaczęła się w piątek. Otrzymywała je przed rozpoczęciem rozprawy.'],
        ['На той момент, коли електропостачання відновили, генератор працював уже дванадцять годин; майстри залишили його працювати під час перевірок.', 'W chwili przywrócenia zasilania generator pracował już od dwunastu godzin; technicy pozostawili go włączonego podczas kontroli.'],
        ['Набір заморозили 1 червня. Фірма постійно наймала працівників до тієї дати, але потім нікого не призначила.', 'Rekrutację zamrożono 1 czerwca. Firma stale zatrudniała do tej daty, ale później nikogo nie przyjęła.'],
        ['Аудиту потрібна тривалість, а не дата початку: як довго рада витрачала гроші на ремонт до обвалу?', 'Audyt potrzebuje czasu trwania, nie daty rozpoczęcia: jak długo rada wydawała pieniądze na naprawy przed zawaleniem?'],
        ['Переговори тривали безперервно протягом усієї попередньої зими: до підписання в березні делегати вели переговори всю ту зиму.', 'Negocjacje trwały bez przerwy przez całą poprzednią zimę: przed podpisaniem w marcu delegaci negocjowali przez całą tamtą zimę.'],
        ['Попередження вперше з’явилося після завершення встановлення й далі блимало: коли ми повідомили про нього, воно блимало ще від завершення встановлення.', 'Ostrzeżenie pojawiło się po zakończeniu instalacji i nadal migało: kiedy je zgłosiliśmy, migało już od zakończenia instalacji.'],
        ['Саме того року витрати на ремонт тривали щомісяця: до розгляду фірма витрачала гроші на ремонт уже весь рік.', 'W tamtym jednym roku wydatki na naprawy trwały co miesiąc: przed przeglądem firma wydawała na naprawy już przez cały rok.'],
        ['Коли автор зателефонував, редактор скорочував чернетку вже три години; була готова лише половина потрібних скорочень.', 'Kiedy autor zadzwonił, redaktor skracał szkic już od trzech godzin; gotowa była tylko połowa wymaganych skrótów.'],
        ['До ремонту двигун глухнув двічі за поїздку: як часто він глухнув, а не як довго тривала кожна зупинка?', 'Przed naprawą silnik gasł dwa razy na podróż: jak często gasł, a nie jak długo trwało każde zgaśnięcie?'],
    ],
    'C1' => [
        ['На момент розкриття інформації у 2020 році слідчі працювали над версією із 2010 року, тобто вже десятиліття, не дійшовши висновку.', 'W chwili ujawnienia informacji w 2020 roku śledczy badali wyjaśnienie od 2010 roku, czyli przez dekadę, nie dochodząc do wniosku.'],
        ['Незалежне тестування почалося з пілотного дослідження й тривало: на момент зміни протоколу кожна лабораторія досліджувала ефект ще від пілотного дослідження.', 'Niezależne testy zaczęły się wraz z badaniem pilotażowym i trwały: kiedy zmieniono protokół, każde laboratorium badało efekt już od badania pilotażowego.'],
        ['Попит зростав щомісяця саме того кварталу: до завершення субсидії він зростав уже весь квартал.', 'Popyt rósł w każdym miesiącu tamtego jednego kwartału: przed końcem subsydium rósł już przez cały kwartał.'],
        ['Березневий експеримент спричинив повідомлення: вони надходили від його завершення; тестування відбувалося до завершення експерименту, а не після.', 'Marcowa próba wywołała zgłoszenia: napływały od jej zakończenia; testy trwały przed zakończeniem próby, nie po nim.'],
        ['На момент оголошення відкликання пацієнти повідомляли про реакції вже рік; повідомлення надходили й після оголошення.', 'W chwili ogłoszenia wycofania leku pacjenci zgłaszali reakcje już od roku; zgłoszenia napływały również później.'],
        ['Відхід працівників почався в січні й припинився із завершенням контракту: фірма втрачала персонал від січня до того кінцевого моменту.', 'Odejścia pracowników zaczęły się w styczniu i ustały wraz z końcem kontraktu: firma traciła personel od stycznia do tego końcowego momentu.'],
        ['Під час розслідування запитують про загальний минулий проміжок незалежно від перерв: як довго сигналізація звучала з перервами до перевірки?', 'W dochodzeniu pytają o cały miniony okres niezależnie od przerw: jak długo alarm odzywał się z przerwami przed kontrolą?'],
        ['Практика тривала протягом усього перевіреного десятиліття: до заборони заводи скидали відходи впродовж усього того десятиліття.', 'Praktyka utrzymywała się przez całą audytowaną dekadę: przed zakazem fabryki odprowadzały odpady przez całą tamtą dekadę.'],
        ['Перша зміна сталася після запровадження політики: на момент призупинення судом вона змінювалася ще від свого запровадження.', 'Pierwsza zmiana nastąpiła po wprowadzeniu polityki: kiedy sąd ją zawiesił, ewoluowała już od wprowadzenia.'],
        ['Упродовж саме того місяця слухань переговори тривали щодня: до угоди сторони вели переговори вже весь місяць.', 'Podczas tamtego jednego miesiąca rozpraw rozmowy trwały codziennie: przed porozumieniem strony negocjowały już przez cały miesiąc.'],
        ['На момент завершення строку остаточного звіту не існувало: аудитори розслідували вже шість місяців, а не завершили розслідування за шість місяців.', 'W terminie końcowym ostateczny raport nie istniał: audytorzy prowadzili dochodzenie od sześciu miesięcy, a nie ukończyli go w sześć miesięcy.'],
        ['Аудит запитує про частоту перемикань, а не загальну тривалість: як часто бухгалтери перемикалися між системами до появи розбіжності?', 'Audyt pyta o częstotliwość przełączeń, nie łączny czas trwania: jak często księgowi przełączali się między systemami przed rozbieżnością?'],
    ],
    'C2' => [
        ['На перевірці 2023 року верифікація залишалася незавершеною: команди тестували з 2018 року, тобто п’ять років, а не лише протягом одного щорічного заняття.', 'Podczas przeglądu w 2023 roku weryfikacja pozostawała nieukończona: zespoły testowały od 2018 roku, czyli przez pięć lat, a nie tylko podczas jednej corocznej sesji.'],
        ['Зближення почалося з попередніх обговорень: згода формувалася від тих обговорень і протягом усього періоду переговорів, перш ніж голосування виявило її межі.', 'Zbliżenie zaczęło się od wstępnych rozmów: konsensus wyłaniał się od tych rozmów i przez cały okres negocjacji, zanim głosowanie ujawniło jego ograniczenia.'],
        ['Упродовж саме того десятиліття переосмислення не припинялося: до відкриття архіву науковці переглядали версію вже все десятиліття.', 'W tamtej jednej dekadzie reinterpretacja nie ustawała: przed otwarciem archiwum uczeni rewidowali relację już przez całą dekadę.'],
        ['Посадовці відмовилися від розмежування в момент розкриття інформації. Вони проводили його до розкриття, але не під час і не після.', 'Urzędnicy porzucili rozróżnienie w chwili ujawnienia informacji. Stosowali je przed ujawnieniem, ale nie podczas niego ani później.'],
        ['На момент закриття архіву дослідники оцифровували документи вже вісімнадцять місяців; віддалена робота тривала й потім, тож закриття не було кінцем діяльності.', 'W chwili zamknięcia archiwum badacze digitalizowali dokumenty już od osiemnastu miesięcy; praca zdalna trwała również później, więc zamknięcie nie było końcem czynności.'],
        ['Запровадження терміна започаткувало спільне вживання: сторони однаково тлумачили його від запровадження до поправки, яка припинила цю узгодженість.', 'Wprowadzenie terminu rozpoczęło wspólne użycie: strony interpretowały go spójnie od wprowadzenia do poprawki, która zakończyła tę zgodność.'],
        ['Трибуналу потрібен загальний минулий проміжок, а не дата першої заяви: як довго підрядники заявляли про відповідність до поновлення?', 'Trybunał potrzebuje całego minionego okresu, nie daty pierwszej deklaracji: jak długo wykonawcy deklarowali zgodność przed odnowieniem?'],
        ['Зміни відбувалися протягом усього періоду правок: до публікації послідовні редактори змінювали охоплення впродовж усього того періоду.', 'Zmiany występowały przez cały okres redakcji: przed publikacją kolejni redaktorzy zmieniali zakres przez cały tamten okres.'],
        ['Переконливість почала зростати після першого незалежного відтворення: на момент рішення, що розвернуло тенденцію, тлумачення набувало підтримки ще від того відтворення.', 'Wiarygodność zaczęła rosnąć wraz z pierwszą niezależną replikacją: kiedy orzeczenie odwróciło trend, interpretacja zyskiwała poparcie już od tej replikacji.'],
        ['Саме того року обмін повідомленнями неодноразово містив погрози: до врегулювання листування передавало погрози вже весь рік.', 'W tamtym jednym roku wymiany wielokrotnie zawierały groźby: przed ugodą korespondencja przekazywała groźby już przez cały rok.'],
        ['До публікації оцінювання залишалося незавершеним: колегія розглядала подання вже дванадцять тижнів, а не завершила дванадцять подань за дванадцять тижнів.', 'Przed publikacją ocena pozostawała nieukończona: panel badał wnioski od dwunastu tygodni, a nie ukończył dwunastu wniosków w dwanaście tygodni.'],
        ['Питання стосується повторюваності, а не тривалості: як часто комітет суперечив власним рішенням до реорганізації?', 'Chodzi o powtarzalność, nie czas trwania: jak często komitet przeczył własnym decyzjom przed reorganizacją?'],
    ],
];
