<?php

namespace App\Http\Controllers;

use App\Models\Page;
use App\Models\PageCategory;
use App\Models\SiteTreeItem;
use App\Models\SiteTreeVariant;
use App\Models\TextBlock;
use App\Modules\LanguageManager\Services\LocaleService;
use App\Services\AutoGeneratedTestService;
use App\Services\TheoryVariantResolver;
use App\Services\TheoryPagePromptLinkedTestsService;
use App\Services\Theory\TextBlockToQuestionsMatcherService;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;

class PageController extends Controller
{
    protected ?string $pageType = null;

    protected string $routePrefix = 'pages';

    protected string $indexView = 'engram.pages.index';

    protected ?string $categoryView = null;

    protected string $showView = 'engram.pages.show';

    protected string $sectionTitle = 'Теорія';

    protected ?array $siteTreeOrdering = null;

    protected ?string $resolvedCategoryLanguage = null;

    public function __construct(
        private AutoGeneratedTestService $autoGeneratedTestService,
        private TheoryPagePromptLinkedTestsService $theoryPagePromptLinkedTestsService,
        private TextBlockToQuestionsMatcherService $textBlockToQuestionsMatcherService,
        private TheoryVariantResolver $theoryVariantResolver,
    ) {}

    protected function preferredLocale(): string
    {
        return app()->getLocale() ?: $this->fallbackLocale();
    }

    protected function fallbackLocale(): string
    {
        return LocaleService::getDefaultLanguage()?->code
            ?? config('language-manager.fallback_locale', 'uk');
    }

    protected function chooseLocaleForBlocks(Collection $blocks, string $preferred, string $fallback): string
    {
        if ($blocks->firstWhere('locale', $preferred)) {
            return $preferred;
        }

        if ($blocks->firstWhere('locale', $fallback)) {
            return $fallback;
        }

        return $preferred;
    }

    protected function filterBlocksByChosenLocale(Collection $blocks, string $preferred, string $fallback): array
    {
        $usedLocale = $this->chooseLocaleForBlocks($blocks, $preferred, $fallback);

        return [$blocks->where('locale', $usedLocale)->values(), $usedLocale];
    }

    /**
     * Display the available categories with the first category's pages.
     */
    public function index()
    {
        $preferredLocale = $this->preferredLocale();
        $fallbackLocale = $this->fallbackLocale();
        $locales = array_unique([$preferredLocale, $fallbackLocale]);

        $categories = $this->categoryList();
        $selectedCategory = $categories->first();
        $ordering = $this->siteTreeOrdering ?? [];

        $selectedCategory?->load([
            'pages' => fn ($query) => $this->applyPageTypeFilter($query)->orderBy('title'),
            'textBlocks' => fn ($query) => $query->whereIn('locale', $locales)->whereNull('page_id'),
        ]);

        if ($selectedCategory) {
            $selectedCategory->setRelation(
                'pages',
                $this->sortPagesWithOrdering($selectedCategory->pages, $ordering)
            );
        }

        $this->localizeDisplayedTitles(
            $categories,
            $selectedCategory,
            $selectedCategory?->pages,
            null,
            $preferredLocale,
            $fallbackLocale
        );

        return view($this->indexView, [
            'categories' => $categories,
            'selectedCategory' => $selectedCategory,
            'categoryPages' => $selectedCategory?->pages ?? collect(),
            'categoryDescription' => $this->categoryDescriptionData($selectedCategory, $preferredLocale, $fallbackLocale),
            'routePrefix' => $this->routePrefix,
            'sectionTitle' => $this->resolvedSectionTitle(),
        ]);
    }

    /**
     * Display a specific category with its related theory pages.
     */
    public function category(PageCategory $category)
    {
        $preferredLocale = $this->preferredLocale();
        $fallbackLocale = $this->fallbackLocale();
        $locales = array_unique([$preferredLocale, $fallbackLocale]);

        $categories = $this->categoryList();
        $resolvedCategory = $categories->firstWhere('id', $category->getKey());

        if ($resolvedCategory instanceof PageCategory) {
            $category->setAttribute(
                'recursive_pages_count',
                (int) ($resolvedCategory->getAttribute('recursive_pages_count') ?? $category->pages->count())
            );
        }

        $ordering = $this->siteTreeOrdering ?? [];
        $category->load([
            'pages' => fn ($query) => $this->applyPageTypeFilter($query)->orderBy('title'),
            'textBlocks' => fn ($query) => $query->whereIn('locale', $locales)->whereNull('page_id'),
            'tags',
        ]);

        $category->setRelation(
            'pages',
            $this->sortPagesWithOrdering($category->pages, $ordering)
        );

        $this->localizeDisplayedTitles(
            $categories,
            $category,
            $category->pages,
            null,
            $preferredLocale,
            $fallbackLocale
        );

        // Get auto-generated tests
        $autoGeneratedTests = $this->autoGeneratedTestService->generateTests($category->tags, $category->title);

        $resolvedTitle = $category->title;
        $variantViewData = [
            'availableVariants' => collect(),
            'currentVariant' => null,
            'currentVariantKey' => 'base',
            'currentVariantSource' => 'base',
            'publishedVariant' => null,
            'publishedVariantKey' => 'base',
            'variantTargetType' => 'category',
            'variantTargetId' => $category->getKey(),
            'variantLocale' => $preferredLocale,
        ];
        $categoryDescription = $this->categoryDescriptionData($category, $preferredLocale, $fallbackLocale);

        if ($this->usesTheoryVariantResolution()) {
            $variantResolution = $this->theoryVariantResolver->resolve(
                $category,
                $category->textBlocks,
                $preferredLocale,
                $fallbackLocale,
                request()
            );

            $category->setRelation('textBlocks', $variantResolution['blocks']);
            $resolvedTitle = $variantResolution['title'];
            $categoryDescription = [
                'blocks' => $variantResolution['blocks'],
                'subtitleBlock' => $variantResolution['subtitleBlock'],
                'columns' => $variantResolution['columns'],
                'locale' => $variantResolution['locale'],
                'hasBlocks' => $variantResolution['blocks']->isNotEmpty(),
            ];
            $variantViewData = [
                'availableVariants' => $variantResolution['availableVariants'],
                'currentVariant' => $variantResolution['currentVariant'],
                'currentVariantKey' => $variantResolution['currentVariantKey'],
                'currentVariantSource' => $variantResolution['currentVariantSource'],
                'publishedVariant' => $variantResolution['publishedVariant'],
                'publishedVariantKey' => $variantResolution['publishedVariantKey'],
                'variantTargetType' => $variantResolution['targetType'],
                'variantTargetId' => $variantResolution['targetId'],
                'variantLocale' => $variantResolution['locale'],
            ];
        }

        // Use category-specific view if defined, otherwise fall back to indexView
        $view = $this->categoryView ?? $this->indexView;

        return view($view, [
            'categories' => $categories,
            'selectedCategory' => $category,
            'categoryPages' => $category->pages,
            'categoryDescription' => $categoryDescription,
            'autoGeneratedTests' => $autoGeneratedTests,
            'routePrefix' => $this->routePrefix,
            'sectionTitle' => $this->resolvedSectionTitle(),
            'resolvedTitle' => $resolvedTitle,
            ...$variantViewData,
        ]);
    }

    /**
     * Display the specified theory page using structured text blocks.
     */
    public function show(PageCategory $category, string $pageSlug)
    {
        $preferredLocale = $this->preferredLocale();
        $fallbackLocale = $this->fallbackLocale();
        $locales = array_unique([$preferredLocale, $fallbackLocale]);

        $page = Page::query()
            ->with([
                'textBlocks' => fn ($query) => $query
                    ->whereIn('locale', $locales)
                    ->with('tags')
                    ->orderBy('sort_order'),
                'tags',
            ])
            ->forType($this->pageType)
            ->where('slug', $pageSlug)
            ->where('page_category_id', $category->getKey())
            ->firstOrFail();

        $allBlocks = $page->textBlocks;

        $categories = $this->categoryList();

        $categoryPages = Page::query()
            ->where('page_category_id', $category->getKey())
            ->where('id', '!=', $page->getKey())
            ->forType($this->pageType)
            ->inRandomOrder()
            ->limit(3)
            ->get();

        if ($categoryPages->isEmpty()) {
            $categoryPages = collect([$page]);
        }

        $this->localizeDisplayedTitles(
            $categories,
            $category,
            $categoryPages,
            $page,
            $preferredLocale,
            $fallbackLocale
        );

        $resolvedTitle = $page->title;
        $blocks = collect();
        $subtitleBlock = null;
        $columns = [
            'left' => collect(),
            'right' => collect(),
        ];
        $locale = $preferredLocale;
        $practiceReferenceBlocks = collect();
        $variantViewData = [
            'availableVariants' => collect(),
            'currentVariant' => null,
            'currentVariantKey' => 'base',
            'currentVariantSource' => 'base',
            'publishedVariant' => null,
            'publishedVariantKey' => 'base',
            'variantTargetType' => 'page',
            'variantTargetId' => $page->getKey(),
            'variantLocale' => $preferredLocale,
        ];

        if ($this->usesTheoryVariantResolution()) {
            $variantResolution = $this->theoryVariantResolver->resolve(
                $page,
                $allBlocks,
                $preferredLocale,
                $fallbackLocale,
                request()
            );

            $resolvedTitle = $variantResolution['title'];
            $blocks = $variantResolution['blocks'];
            $locale = $variantResolution['locale'];
            $subtitleBlock = $variantResolution['subtitleBlock'];
            $columns = $variantResolution['columns'];
            $practiceReferenceBlocks = $variantResolution['practiceReferenceBlocks'];
            $page->setRelation('textBlocks', $blocks);
            $variantViewData = [
                'availableVariants' => $variantResolution['availableVariants'],
                'currentVariant' => $variantResolution['currentVariant'],
                'currentVariantKey' => $variantResolution['currentVariantKey'],
                'currentVariantSource' => $variantResolution['currentVariantSource'],
                'publishedVariant' => $variantResolution['publishedVariant'],
                'publishedVariantKey' => $variantResolution['publishedVariantKey'],
                'variantTargetType' => $variantResolution['targetType'],
                'variantTargetId' => $variantResolution['targetId'],
                'variantLocale' => $variantResolution['locale'],
            ];
        } else {
            [$blocks, $locale] = $this->filterBlocksByChosenLocale($allBlocks, $preferredLocale, $fallbackLocale);
            $page->setRelation('textBlocks', $blocks);
            $subtitleBlock = $blocks->firstWhere(fn ($block) => $block->type === 'subtitle');
            $columns = [
                'left' => $blocks->filter(fn ($block) => $block->column === 'left'),
                'right' => $blocks->filter(fn ($block) => $block->column === 'right'),
            ];
            $practiceReferenceBlocks = $blocks;
        }

        // Theory pages surface aggregated virtual tests built from all linked Page_V3/V3 seeders.
        $topicTests = $this->theoryPagePromptLinkedTestsService->buildForPage($page);

        // Get practice questions for each text block (tag-based matching)
        $practiceQuestionsByBlock = $this->textBlockToQuestionsMatcherService->findQuestionsForTextBlocks($practiceReferenceBlocks, 5);

        $breadcrumbs = [
            ['label' => __('public.common.home'), 'url' => localized_route('home')],
            ['label' => $this->resolvedSectionTitle(), 'url' => localized_route($this->routePrefix.'.index')],
            ['label' => $category->title, 'url' => localized_route($this->routePrefix.'.category', $category->slug)],
            ['label' => $resolvedTitle],
        ];

        return view($this->showView, [
            'page' => $page,
            'breadcrumbs' => $breadcrumbs,
            'subtitleBlock' => $subtitleBlock,
            'columns' => $columns,
            'locale' => $locale,
            'categories' => $categories,
            'selectedCategory' => $category,
            'categoryPages' => $categoryPages,
            'topicTests' => $topicTests,
            'practiceQuestionsByBlock' => $practiceQuestionsByBlock,
            'routePrefix' => $this->routePrefix,
            'sectionTitle' => $this->resolvedSectionTitle(),
            'resolvedTitle' => $resolvedTitle,
            ...$variantViewData,
        ]);
    }

    protected function usesTheoryVariantResolution(): bool
    {
        return $this->pageType === 'theory';
    }

    protected function resolvedSectionTitle(): string
    {
        if ($this->pageType === 'theory' || in_array($this->routePrefix, ['theory', 'copilot.theory'], true)) {
            return __('frontend.copilot_theory.theory');
        }

        return $this->sectionTitle;
    }

    protected function localizeDisplayedTitles(
        ?Collection $categories,
        ?PageCategory $selectedCategory,
        ?Collection $categoryPages,
        ?Page $currentPage,
        string $preferredLocale,
        string $fallbackLocale
    ): void {
        $locales = array_values(array_unique(array_filter([$preferredLocale, $fallbackLocale])));

        if ($locales === []) {
            return;
        }

        $categoryModels = $this->collectCategoryModelsForLocalization($categories, $selectedCategory);
        $pageModels = $this->collectPageModelsForLocalization($categoryModels, $categoryPages, $currentPage);

        $localizedTitles = $this->loadLocalizedTitlesForModels(
            $categoryModels->map(fn (PageCategory $category) => $category->getKey())->filter()->unique()->values()->all(),
            $pageModels->map(fn (Page $page) => $page->getKey())->filter()->unique()->values()->all(),
            $locales
        );

        $this->applyLocalizedTitlesToModels($categoryModels, $localizedTitles['categories'] ?? [], $preferredLocale, $fallbackLocale);
        $this->applyLocalizedTitlesToModels($pageModels, $localizedTitles['pages'] ?? [], $preferredLocale, $fallbackLocale);

        if ($preferredLocale !== $fallbackLocale) {
            $this->applyLocalizedPagePreviewsToModels(
                $pageModels,
                $localizedTitles['page_previews'] ?? [],
                $preferredLocale,
                $fallbackLocale
            );
        }
    }

    protected function collectCategoryModelsForLocalization(?Collection $categories, ?PageCategory $selectedCategory): Collection
    {
        $models = collect();
        $visit = function (?Collection $items) use (&$models, &$visit): void {
            foreach ($items ?? collect() as $category) {
                if (! $category instanceof PageCategory || ! $category->getKey()) {
                    continue;
                }

                $models->push($category);

                if ($category->relationLoaded('children')) {
                    $visit($category->children);
                }
            }
        };

        $visit($categories);

        if ($selectedCategory instanceof PageCategory && $selectedCategory->getKey()) {
            $models->push($selectedCategory);

            if ($selectedCategory->relationLoaded('children')) {
                $visit($selectedCategory->children);
            }
        }

        return $models->values();
    }

    protected function collectPageModelsForLocalization(
        Collection $categoryModels,
        ?Collection $categoryPages,
        ?Page $currentPage
    ): Collection {
        $models = collect();
        $visit = function (Collection $categories) use (&$models, &$visit): void {
            foreach ($categories as $category) {
                if (! $category instanceof PageCategory) {
                    continue;
                }

                if ($category->relationLoaded('pages')) {
                    $models = $models->concat(
                        $category->pages->filter(fn ($page) => $page instanceof Page && $page->getKey())
                    );
                }

                if ($category->relationLoaded('children')) {
                    $visit($category->children);
                }
            }
        };

        $visit($categoryModels);

        if ($categoryPages instanceof Collection) {
            $models = $models->concat(
                $categoryPages->filter(fn ($page) => $page instanceof Page && $page->getKey())
            );
        }

        if ($currentPage instanceof Page && $currentPage->getKey()) {
            $models->push($currentPage);
        }

        return $models->values();
    }

    protected function loadLocalizedTitlesForModels(array $categoryIds, array $pageIds, array $locales): array
    {
        $categoryTitles = [];
        $pageTitles = [];
        $pagePreviews = [];

        if ($categoryIds !== []) {
            $categoryBlocks = TextBlock::query()
                ->select(['page_category_id', 'locale', 'body'])
                ->where('type', 'subtitle')
                ->whereNull('page_id')
                ->whereIn('locale', $locales)
                ->whereIn('page_category_id', $categoryIds)
                ->get();

            foreach ($categoryBlocks as $block) {
                $title = $this->extractLocalizedTitleFromSubtitle($block->body);

                if ($title === null || ! $block->page_category_id) {
                    continue;
                }

                $categoryTitles[$block->page_category_id][$block->locale] ??= $title;
            }
        }

        if ($pageIds !== []) {
            $pageBlocks = TextBlock::query()
                ->select(['page_id', 'locale', 'body'])
                ->where('type', 'subtitle')
                ->whereIn('locale', $locales)
                ->whereIn('page_id', $pageIds)
                ->get();

            foreach ($pageBlocks as $block) {
                $title = $this->extractLocalizedTitleFromSubtitle($block->body);
                $preview = $this->extractLocalizedPreviewFromSubtitle($block->body, $title);

                if ($title === null || ! $block->page_id) {
                    if ($preview !== null && $block->page_id) {
                        $pagePreviews[$block->page_id][$block->locale] ??= $preview;
                    }

                    continue;
                }

                $pageTitles[$block->page_id][$block->locale] ??= $title;

                if ($preview !== null) {
                    $pagePreviews[$block->page_id][$block->locale] ??= $preview;
                }
            }
        }

        return [
            'categories' => $categoryTitles,
            'pages' => $pageTitles,
            'page_previews' => $pagePreviews,
        ];
    }

    protected function applyLocalizedTitlesToModels(
        Collection $models,
        array $localizedTitles,
        string $preferredLocale,
        string $fallbackLocale
    ): void {
        $locales = array_values(array_unique(array_filter([$preferredLocale, $fallbackLocale])));

        foreach ($models as $model) {
            $modelId = $model?->getKey();

            if (! $modelId || ! isset($localizedTitles[$modelId])) {
                continue;
            }

            foreach ($locales as $locale) {
                $localizedTitle = $localizedTitles[$modelId][$locale] ?? null;

                if (is_string($localizedTitle) && $localizedTitle !== '') {
                    $model->setAttribute('title', $localizedTitle);
                    break;
                }
            }
        }
    }

    protected function applyLocalizedPagePreviewsToModels(
        Collection $models,
        array $localizedPreviews,
        string $preferredLocale,
        string $fallbackLocale
    ): void {
        $locales = array_values(array_unique(array_filter([$preferredLocale, $fallbackLocale])));

        foreach ($models as $model) {
            if (! $model instanceof Page) {
                continue;
            }

            $modelId = $model->getKey();

            if (! $modelId || ! isset($localizedPreviews[$modelId])) {
                continue;
            }

            foreach ($locales as $locale) {
                $localizedPreview = $localizedPreviews[$modelId][$locale] ?? null;

                if (is_string($localizedPreview) && $localizedPreview !== '') {
                    $model->setAttribute('text', $localizedPreview);
                    break;
                }
            }
        }
    }

    protected function extractLocalizedTitleFromSubtitle(?string $body): ?string
    {
        if (! is_string($body) || trim($body) === '') {
            return null;
        }

        $plainText = $this->normalizeLocalizedTitleCandidate(strip_tags(html_entity_decode($body, ENT_QUOTES | ENT_HTML5, 'UTF-8')));

        if ($plainText === '') {
            return null;
        }

        $candidates = [];

        if (preg_match('/^\s*(?:<p\b[^>]*>\s*)?<strong\b[^>]*>(.*?)<\/strong>/isu', $body, $matches) === 1) {
            $candidate = $this->normalizeLocalizedTitleCandidate($matches[1] ?? null);

            if ($candidate !== '') {
                $candidates[] = $candidate;
            }
        }

        foreach ([
            '/^(.+?)\s+[—-]\s+/u',
            '/^(.+?)\s+\b(?:to|jest|są|służy|używa się|używane|używany|oznacza|opisuje|pokazuje|is|are|means|describes|shows|used)\b/iu',
        ] as $pattern) {
            if (preg_match($pattern, $plainText, $matches) === 1) {
                $candidate = $this->normalizeLocalizedTitleCandidate($matches[1] ?? null);

                if ($candidate !== '') {
                    $candidates[] = $candidate;
                }
            }
        }

        if (preg_match('/<strong\b[^>]*>(.*?)<\/strong>/isu', $body, $matches) === 1) {
            $candidate = $this->normalizeLocalizedTitleCandidate($matches[1] ?? null);

            if ($candidate !== '' && ! in_array($candidate, $candidates, true)) {
                $candidates[] = $candidate;
            }
        }

        foreach ($candidates as $candidate) {
            if ($this->isValidLocalizedTitleCandidate($candidate)) {
                return $candidate;
            }
        }

        return $this->isValidLocalizedTitleCandidate($plainText) ? $plainText : null;
    }

    protected function extractLocalizedPreviewFromSubtitle(?string $body, ?string $title = null): ?string
    {
        if (! is_string($body) || trim($body) === '') {
            return null;
        }

        $plainText = $this->normalizeLocalizedTitleCandidate(
            strip_tags(html_entity_decode($body, ENT_QUOTES | ENT_HTML5, 'UTF-8'))
        );

        if ($plainText === '') {
            return null;
        }

        $normalizedTitle = $this->normalizeLocalizedTitleCandidate($title);

        if ($normalizedTitle !== '') {
            $plainLower = Str::lower($plainText);
            $titleLower = Str::lower($normalizedTitle);

            if (Str::startsWith($plainLower, $titleLower)) {
                $plainText = trim(mb_substr($plainText, mb_strlen($normalizedTitle)));
                $plainText = ltrim($plainText, " \t\n\r\0\x0B-–—:;,.|");
            }
        }

        if ($plainText === '') {
            return null;
        }

        return Str::limit($plainText, 180);
    }

    protected function normalizeLocalizedTitleCandidate(?string $value): string
    {
        $normalized = html_entity_decode((string) $value, ENT_QUOTES | ENT_HTML5, 'UTF-8');
        $normalized = preg_replace('/\s+/u', ' ', strip_tags($normalized)) ?? $normalized;

        return trim($normalized, " \t\n\r\0\x0B-–—:;,.|");
    }

    protected function isValidLocalizedTitleCandidate(string $candidate): bool
    {
        $length = mb_strlen($candidate);

        if ($length < 3 || $length > 110) {
            return false;
        }

        if (preg_match('/[.?!]$/u', $candidate) === 1 && $length > 40) {
            return false;
        }

        return true;
    }

    protected function categoryList(): Collection
    {
        $preferredLocale = $this->preferredLocale();
        $fallbackLocale = $this->fallbackLocale();
        $language = $this->resolveCategoryLanguage($preferredLocale, $fallbackLocale);

        $categories = PageCategory::query()
            ->whereNull('parent_id')
            ->when($this->pageType === 'theory', fn ($query) => $query->where('type', 'theory'))
            ->when($language, fn ($query, $lang) => $query->where('language', $lang))
            ->with([
                'pages' => fn ($query) => $this->applyPageTypeFilter($query)->orderBy('title'),
                'children' => function ($query) {
                    $this->applyCategoryChildrenRelations($query);
                },
            ])
            ->withCount([
                'pages' => fn ($query) => $this->applyPageTypeFilter($query),
            ])
            ->orderBy('title')
            ->get();

        $this->attachRecursivePageCounts($categories);

        if ($this->pageType !== 'theory') {
            return $categories;
        }

        $availableTitles = $this->collectTheoryTitles($categories);
        $this->siteTreeOrdering = $this->siteTreeOrdering ?? $this->siteTreeLinkOrdering($availableTitles);
        $ordering = $this->siteTreeOrdering;

        return $this->applyTheoryRootCategoryOrdering(
            $this->applySiteTreeOrdering($categories, $ordering)
        );
    }

    protected function attachRecursivePageCounts(Collection $categories): void
    {
        foreach ($categories as $category) {
            if ($category instanceof PageCategory) {
                $this->setRecursivePageCount($category);
            }
        }
    }

    protected function setRecursivePageCount(PageCategory $category): int
    {
        $count = (int) ($category->pages_count ?? ($category->relationLoaded('pages') ? $category->pages->count() : 0));

        if ($category->relationLoaded('children')) {
            foreach ($category->children as $child) {
                if ($child instanceof PageCategory) {
                    $count += $this->setRecursivePageCount($child);
                }
            }
        }

        $category->setAttribute('recursive_pages_count', $count);

        return $count;
    }

    protected function applyCategoryChildrenRelations($query): void
    {
        $language = $this->resolvedCategoryLanguage;

        $query->when($this->pageType === 'theory', fn ($q) => $q->where('type', 'theory'))
            ->when($language, fn ($q, $lang) => $q->where('language', $lang))
            ->withCount(['pages' => fn ($q) => $this->applyPageTypeFilter($q)])
            ->with([
                'pages' => fn ($q) => $this->applyPageTypeFilter($q)->orderBy('title'),
                'children' => function ($childQuery) {
                    $this->applyCategoryChildrenRelations($childQuery);
                },
            ])
            ->orderBy('title');
    }

    /**
     * Build a flattened ordering map for linked theory pages/categories based on the site tree variant.
     */
    protected function siteTreeLinkOrdering(array $availableTitles): array
    {
        $variant = SiteTreeVariant::getBase();

        if (! $variant) {
            return [];
        }

        $availableLookup = [];
        foreach ($availableTitles as $title) {
            $availableLookup[$title] = true;
            $availableLookup[$this->normalizeTitle($title)] = true;
        }

        $roots = SiteTreeItem::query()
            ->where('variant_id', $variant->id)
            ->whereNull('parent_id')
            ->with(['children' => function ($query) {
                $query->with('children')->orderBy('sort_order');
            }])
            ->orderBy('sort_order')
            ->get();

        $ordering = [];
        $position = 0;

        $collectOrdering = function ($items) use (&$collectOrdering, &$ordering, &$position, $availableLookup) {
            foreach ($items as $item) {
                $linkedTitle = $item->linked_page_title;

                if (! $linkedTitle) {
                    $linkedTitle = $this->findMatchingTheoryTitle($item->title, $availableLookup);
                }

                if ($linkedTitle) {
                    $normalized = $this->normalizeTitle($linkedTitle);
                    $ordering[$linkedTitle] = $position;
                    $ordering[$normalized] = $position;
                    $position++;
                }

                if ($item->children?->isNotEmpty()) {
                    $collectOrdering($item->children);
                }
            }
        };

        $collectOrdering($roots);

        return $ordering;
    }

    /**
     * Sort categories and nested pages according to the site tree ordering map.
     */
    protected function applySiteTreeOrdering(Collection $categories, array $ordering): Collection
    {
        $sorted = $categories->map(function (PageCategory $category) use ($ordering) {
            if ($category->relationLoaded('children')) {
                $category->setRelation('children', $this->applySiteTreeOrdering($category->children, $ordering));
            }

            if ($category->relationLoaded('pages')) {
                $category->setRelation('pages', $this->sortCollectionByOrdering($category->pages, $ordering, fn ($page) => $page->title));
            }

            $category->setAttribute('ordered_tree_items', $this->sortCategoryItems($category, $ordering));

            return $category;
        });

        return $this->sortCollectionByOrdering($sorted, $ordering, fn (PageCategory $category) => $category->title);
    }

    protected function applyTheoryRootCategoryOrdering(Collection $categories): Collection
    {
        if ($categories->isEmpty()) {
            return $categories;
        }

        $ordering = array_flip($this->theoryRootCategorySlugs());

        return $categories
            ->sortBy(fn (PageCategory $category) => [
                $ordering[$category->slug] ?? PHP_INT_MAX,
                mb_strtolower($category->title),
            ])
            ->values();
    }

    protected function theoryRootCategorySlugs(): array
    {
        return [
            'basic-grammar',
            'imennyky-artykli-ta-kilkist',
            'zaimennyky-ta-vkazivni-slova',
            'maibutni-formy',
            'pytalni-rechennia-ta-zaperechennia',
            'prykmetniky-ta-pryslinknyky',
            'some-any',
            'tenses',
            'passive-voice',
            'modal-verbs',
            'conditionals',
            'reported-speech',
            'clauses-and-linking-words',
            'prepositions-and-phrasal-verbs',
            'common-mistakes',
            'sentence-transformations',
            'verb-patterns',
        ];
    }

    protected function sortPagesWithOrdering(Collection $pages, array $ordering): Collection
    {
        if ($pages->isEmpty()) {
            return $pages;
        }

        return $this->sortCollectionByOrdering($pages, $ordering, fn ($page) => $page->title);
    }

    /**
     * Sort a collection with site tree ordering first and fallback alphabetical.
     */
    protected function sortCollectionByOrdering(Collection $items, array $ordering, callable $getTitle): Collection
    {
        return $items
            ->sortBy(function ($item) use ($ordering, $getTitle) {
                $title = $getTitle($item);
                $order = $this->resolveOrderingValue($title, $ordering);

                return [$order, mb_strtolower($title)];
            })
            ->values();
    }

    /**
     * Combine child categories and pages into a single ordered collection that mirrors the site tree.
     */
    protected function sortCategoryItems(PageCategory $category, array $ordering): Collection
    {
        $items = collect();

        if ($category->relationLoaded('children') && $category->children->isNotEmpty()) {
            $items = $items->concat($category->children->map(fn (PageCategory $child) => [
                'type' => 'category',
                'model' => $child,
            ]));
        }

        if ($category->relationLoaded('pages') && $category->pages->isNotEmpty()) {
            $items = $items->concat($category->pages->map(fn ($page) => [
                'type' => 'page',
                'model' => $page,
            ]));
        }

        return $items
            ->sortBy(function ($item) use ($ordering) {
                $title = $item['model']->title;
                $order = $this->resolveOrderingValue($title, $ordering);

                return [$order, mb_strtolower($title)];
            })
            ->values();
    }

    protected function resolveOrderingValue(string $title, array $ordering): int
    {
        $normalized = $this->normalizeTitle($title);

        return $ordering[$title]
            ?? $ordering[$normalized]
            ?? PHP_INT_MAX;
    }

    protected function normalizeTitle(string $title): string
    {
        $cleaned = preg_replace('/^\d+[.\d\s]*\s*/u', '', $title) ?? $title;

        return Str::lower(trim($cleaned));
    }

    protected function findMatchingTheoryTitle(string $title, array $availableLookup): ?string
    {
        $normalizedTitle = $this->normalizeTitle($title);

        if (isset($availableLookup[$title])) {
            return $title;
        }

        return isset($availableLookup[$normalizedTitle]) ? $normalizedTitle : null;
    }

    protected function collectTheoryTitles(Collection $categories): array
    {
        $titles = [];

        foreach ($categories as $category) {
            $titles[] = $category->title;

            if ($category->relationLoaded('pages')) {
                foreach ($category->pages as $page) {
                    $titles[] = $page->title;
                }
            }

            if ($category->relationLoaded('children') && $category->children->isNotEmpty()) {
                $titles = array_merge($titles, $this->collectTheoryTitles($category->children));
            }
        }

        return $titles;
    }

    /**
     * Get all categories (flat list) that have pages of this type.
     * Used for cases where we need all categories regardless of hierarchy.
     */
    protected function allCategoriesFlat(): Collection
    {
        return PageCategory::query()
            ->whereHas('pages', fn ($query) => $this->applyPageTypeFilter($query))
            ->withCount([
                'pages' => fn ($query) => $this->applyPageTypeFilter($query),
            ])
            ->orderBy('title')
            ->get();
    }

    protected function categoryDescriptionData(
        ?PageCategory $category,
        ?string $preferredLocale = null,
        ?string $fallbackLocale = null
    ): array
    {
        $preferredLocale = $preferredLocale ?? $this->preferredLocale();
        $fallbackLocale = $fallbackLocale ?? $this->fallbackLocale();

        if (! $category) {
            return [
                'blocks' => collect(),
                'subtitleBlock' => null,
                'columns' => [
                    'left' => collect(),
                    'right' => collect(),
                ],
                'locale' => $preferredLocale,
                'hasBlocks' => false,
            ];
        }

        $blocks = ($category->textBlocks ?? collect())->whereNull('page_id')->values();
        [$blocks, $locale] = $this->filterBlocksByChosenLocale($blocks, $preferredLocale, $fallbackLocale);

        $subtitleBlock = $blocks->firstWhere(fn ($block) => $block->type === 'subtitle');

        $columns = [
            'left' => $blocks->filter(fn ($block) => $block->column === 'left'),
            'right' => $blocks->filter(fn ($block) => $block->column === 'right'),
        ];

        return [
            'blocks' => $blocks,
            'subtitleBlock' => $subtitleBlock,
            'columns' => $columns,
            'locale' => $locale,
            'hasBlocks' => $blocks->isNotEmpty(),
        ];
    }

    protected function resolveCategoryLanguage(string $preferredLocale, string $fallbackLocale): ?string
    {
        if ($this->resolvedCategoryLanguage !== null) {
            return $this->resolvedCategoryLanguage;
        }

        $baseQuery = PageCategory::query()
            ->whereNull('parent_id')
            ->when($this->pageType === 'theory', fn ($query) => $query->where('type', 'theory'));

        if ((clone $baseQuery)->where('language', $preferredLocale)->exists()) {
            return $this->resolvedCategoryLanguage = $preferredLocale;
        }

        if ((clone $baseQuery)->where('language', $fallbackLocale)->exists()) {
            return $this->resolvedCategoryLanguage = $fallbackLocale;
        }

        return $this->resolvedCategoryLanguage = null;
    }

    protected function applyPageTypeFilter($query)
    {
        return $this->pageType === null
            ? $query->whereNull('type')
            : $query->where('type', $this->pageType);
    }

}
