<?php

namespace App\Http\Controllers;

use App\Models\Page;
use App\Models\PageCategory;
use App\Models\Question;
use App\Models\SavedGrammarTest;
use App\Services\AutoGeneratedTestService;
use Illuminate\Support\Collection;

class PageController extends Controller
{
    private const LEVEL_ORDER = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];

    protected ?string $pageType = null;

    protected string $routePrefix = 'pages';

    protected string $indexView = 'engram.pages.index';

    protected string $categoryView = '';

    protected string $showView = 'engram.pages.show';

    protected string $sectionTitle = 'Теорія';

    public function __construct(
        private AutoGeneratedTestService $autoGeneratedTestService
    ) {
    }
    /**
     * Display the available categories with the first category's pages.
     */
    public function index()
    {
        $categories = $this->categoryList();
        $selectedCategory = $categories->first();

        $selectedCategory?->load([
            'pages' => fn ($query) => $this->applyPageTypeFilter($query)->orderBy('title'),
            'textBlocks',
        ]);

        return view($this->indexView, [
            'categories' => $categories,
            'selectedCategory' => $selectedCategory,
            'categoryPages' => $selectedCategory?->pages ?? collect(),
            'categoryDescription' => $this->categoryDescriptionData($selectedCategory),
            'routePrefix' => $this->routePrefix,
            'sectionTitle' => $this->sectionTitle,
        ]);
    }

    /**
     * Display a specific category with its related theory pages.
     */
    public function category(PageCategory $category)
    {
        $categories = $this->categoryList();
        $category->load([
            'pages' => fn ($query) => $this->applyPageTypeFilter($query)->orderBy('title'),
            'textBlocks',
            'tags',
        ]);

        // Get saved tests with matching tags
        $categoryTagIds = $category->tags->pluck('id')->toArray();
        $relatedTests = $this->getRelatedTestsWithMetadata($categoryTagIds, $category->tags);

        // Get auto-generated tests
        $autoGeneratedTests = $this->autoGeneratedTestService->generateTests($category->tags, $category->title);

        // Use category-specific view if defined, otherwise fall back to indexView
        $view = $this->categoryView !== '' ? $this->categoryView : $this->indexView;

        return view($view, [
            'categories' => $categories,
            'selectedCategory' => $category,
            'categoryPages' => $category->pages,
            'categoryDescription' => $this->categoryDescriptionData($category),
            'relatedTests' => $relatedTests,
            'autoGeneratedTests' => $autoGeneratedTests,
            'routePrefix' => $this->routePrefix,
            'sectionTitle' => $this->sectionTitle,
        ]);
    }

    /**
     * Display the specified theory page using structured text blocks.
     */
    public function show(PageCategory $category, string $pageSlug)
    {
        $page = Page::query()
            ->with(['textBlocks', 'tags'])
            ->forType($this->pageType)
            ->where('slug', $pageSlug)
            ->where('page_category_id', $category->getKey())
            ->firstOrFail();

        $blocks = $page->textBlocks;

        $subtitleBlock = $blocks->firstWhere(fn ($block) => $block->type === 'subtitle');

        $columns = [
            'left' => $blocks->filter(fn ($block) => $block->column === 'left'),
            'right' => $blocks->filter(fn ($block) => $block->column === 'right'),
        ];

        $locale = $subtitleBlock->locale
            ?? ($blocks->first()?->locale)
            ?? 'uk';

        $categories = $this->categoryList();

        $categoryPages = Page::query()
            ->where('page_category_id', $category->getKey())
            ->where('id', '!=', $page->getKey())
            ->forType($this->pageType)
            ->inRandomOrder()
            ->limit(3)
            ->get();

        if ($categoryPages->isEmpty()) {
            $categoryPages = collect([$page]);
        }

        // Get saved tests with matching tags
        $pageTagIds = $page->tags->pluck('id')->toArray();
        $relatedTests = $this->getRelatedTestsWithMetadata($pageTagIds, $page->tags);

        // Get auto-generated tests
        $autoGeneratedTests = $this->autoGeneratedTestService->generateTests($page->tags, $page->title);

        $breadcrumbs = [
            ['label' => 'Home', 'url' => route('home')],
            ['label' => $this->sectionTitle, 'url' => route($this->routePrefix.'.index')],
            ['label' => $category->title, 'url' => route($this->routePrefix.'.category', $category->slug)],
            ['label' => $page->title],
        ];

        return view($this->showView, [
            'page' => $page,
            'breadcrumbs' => $breadcrumbs,
            'subtitleBlock' => $subtitleBlock,
            'columns' => $columns,
            'locale' => $locale,
            'categories' => $categories,
            'selectedCategory' => $category,
            'categoryPages' => $categoryPages,
            'relatedTests' => $relatedTests,
            'autoGeneratedTests' => $autoGeneratedTests,
            'routePrefix' => $this->routePrefix,
            'sectionTitle' => $this->sectionTitle,
        ]);
    }

    protected function categoryList(): Collection
    {
        return PageCategory::query()
            ->whereHas('pages', fn ($query) => $this->applyPageTypeFilter($query))
            ->withCount([
                'pages' => fn ($query) => $this->applyPageTypeFilter($query),
            ])
            ->orderBy('title')
            ->get();
    }

    protected function categoryDescriptionData(?PageCategory $category): array
    {
        if (! $category) {
            return [
                'blocks' => collect(),
                'subtitleBlock' => null,
                'columns' => [
                    'left' => collect(),
                    'right' => collect(),
                ],
                'locale' => app()->getLocale() ?? 'uk',
                'hasBlocks' => false,
            ];
        }

        $blocks = $category->textBlocks ?? collect();
        $subtitleBlock = $blocks->firstWhere(fn ($block) => $block->type === 'subtitle');

        $columns = [
            'left' => $blocks->filter(fn ($block) => $block->column === 'left'),
            'right' => $blocks->filter(fn ($block) => $block->column === 'right'),
        ];

        $locale = $subtitleBlock->locale
            ?? ($blocks->first()?->locale)
            ?? app()->getLocale()
            ?? 'uk';

        return [
            'blocks' => $blocks,
            'subtitleBlock' => $subtitleBlock,
            'columns' => $columns,
            'locale' => $locale,
            'hasBlocks' => $blocks->isNotEmpty(),
        ];
    }

    /**
     * Get related tests with enriched metadata including level ranges and matching tags.
     * 
     * This method fetches saved grammar tests that have questions matching the given tag IDs,
     * then enriches each test with computed properties:
     * - level_range: Collection of unique levels (e.g., ['A1', 'A2', 'B1']) sorted in proper order
     * - matching_tags: Collection of tag names that match between the source and test questions
     *
     * @param array $tagIds Tag IDs to match against (from page or category)
     * @param Collection $tags Tag collection for computing matching tag names
     * @return Collection Collection of SavedGrammarTest models with level_range and matching_tags properties
     */
    protected function getRelatedTestsWithMetadata(array $tagIds, Collection $tags): Collection
    {
        if (empty($tagIds)) {
            return collect();
        }

        $relatedTests = SavedGrammarTest::withMatchingTags($tagIds)->orderBy('name')->get();

        if ($relatedTests->isEmpty()) {
            return collect();
        }

        // Get all question UUIDs for all tests at once
        $allQuestionUuids = $relatedTests->flatMap(fn($test) => $test->questionLinks->pluck('question_uuid'))->unique()->toArray();
        
        // Fetch all questions with their tags in one query
        $allQuestions = !empty($allQuestionUuids)
            ? Question::whereIn('uuid', $allQuestionUuids)->with('tags')->get()->keyBy('uuid')
            : collect();
        
        $levelOrder = array_flip(self::LEVEL_ORDER);
        
        return $relatedTests->map(function ($test) use ($allQuestions, $tagIds, $tags, $levelOrder) {
            $questionUuids = $test->questionLinks->pluck('question_uuid')->toArray();
            
            if (!empty($questionUuids)) {
                // Get questions for this test from the pre-loaded collection
                $testQuestions = collect($questionUuids)
                    ->map(fn($uuid) => $allQuestions->get($uuid))
                    ->filter();
                
                // Extract unique levels and sort them
                $levels = $testQuestions->pluck('level')->filter()->unique();
                $levels = $levels->sortBy(fn($lvl) => $levelOrder[$lvl] ?? 99)->values();
                
                // Find matching tags
                $testTagIds = $testQuestions->pluck('tags')->flatten()->pluck('id')->unique()->toArray();
                $matchingTagIds = array_intersect($tagIds, $testTagIds);
                $matchingTags = $tags->whereIn('id', $matchingTagIds)->pluck('name');
                
                // Add computed properties
                $test->level_range = $levels;
                $test->matching_tags = $matchingTags;
            } else {
                $test->level_range = collect();
                $test->matching_tags = collect();
            }
            
            return $test;
        });
    }

    protected function applyPageTypeFilter($query)
    {
        return $this->pageType === null
            ? $query->whereNull('type')
            : $query->where('type', $this->pageType);
    }
}
