<?php

namespace Database\Seeders\V3\SentenceTransformations;

require_once __DIR__ . '/SentenceTransformationsRelativeClausesLinkingWordsAllLevelsV3Seeder/SentenceTransformationsRelativeClausesLinkingWordsAllLevelsV3Seeder.php';
