<?php

// Read-only author extraction and finite editorial audit. Existing M24 native
// body strings are never regenerated by this helper.
function m40Json(array $value, bool $pretty = false): string
{
    return json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR
        | ($pretty ? JSON_PRETTY_PRINT : 0)).($pretty ? "\n" : '');
}

function m40Plain(string $html): string
{
    $html = preg_replace('~</?(?:p|li|ul|ol|div|td|th|tr|table|thead|tbody|br|h[1-6])\b[^>]*>~i', ' ', $html);
    return trim(preg_replace('/\s+/u', ' ', html_entity_decode(strip_tags($html), ENT_QUOTES | ENT_HTML5, 'UTF-8')));
}

function m40Words(string $html): int { return preg_match_all('/\S+/u', m40Plain($html)); }
function m40Sentences(string $html): int { return preg_match_all('/[.!?](?:\s|$)/u', m40Plain($html)); }

function m40LearnerValues(mixed $value, bool $root = false): string
{
    if (is_string($value)) { return $value; }
    if (!is_array($value)) { return ''; }
    $parts = [];
    foreach ($value as $key => $child) {
        if (in_array($key, ['color', 'url', 'href', 'current', 'level', 'icon'], true) || ($root && $key === 'title')) { continue; }
        $parts[] = m40LearnerValues($child);
    }
    return implode(' ', $parts);
}

function m40Inner(DOMNode $node): string
{
    $out = '';
    foreach ($node->childNodes as $child) { $out .= $node->ownerDocument->saveHTML($child); }
    return trim($out);
}

function m40AppendSections(string $html): array
{
    if (!preg_match('~^<h4>(.*?)</h4>\s*([\s\S]*?)<h4>(.*?)</h4>\s*([\s\S]*?)<section id="([^"]+)">([\s\S]*)</section>\s*$~', $html, $parts)) {
        throw new RuntimeException('M24 appended source must contain exactly A, B and the self-check section.');
    }
    $dom = new DOMDocument;
    libxml_use_internal_errors(true);
    $dom->loadHTML('<meta charset="UTF-8"><section id="'.$parts[5].'">'.$parts[6].'</section>', LIBXML_NONET);
    libxml_clear_errors(); $xp = new DOMXPath($dom); $section = $xp->query('//section')->item(0);
    $prompts = $xp->query('./ol/li', $section); $answers = $xp->query('./details/ol/li', $section);
    if ($prompts->length !== 6 || $answers->length !== 6) { throw new RuntimeException('M24 author self-check task/key count differs.'); }
    $author = ['section_title' => trim($xp->query('./h4', $section)->item(0)->textContent),
        'intro' => m40Inner($xp->query('./p', $section)->item(0)),
        'prompts' => array_map('m40Inner', iterator_to_array($prompts)),
        'title' => trim($xp->query('./details/summary', $section)->item(0)->textContent),
        'answers' => array_map('m40Inner', iterator_to_array($answers))];
    return [['title' => html_entity_decode($parts[1], ENT_QUOTES | ENT_HTML5, 'UTF-8'), 'html' => trim($parts[2])],
        ['title' => html_entity_decode($parts[3], ENT_QUOTES | ENT_HTML5, 'UTF-8'), 'html' => trim($parts[4])],
        ['title' => $author['section_title'], 'legacy_practice_id' => $parts[5], 'author_self_check' => $author]];
}

function m40DetailAudit(array $lesson, array $parts): array
{
    $audit = [];
    $append = static function (string $path, string $candidate, string $context, string $section, string $kind, string $reason) use (&$audit): void {
        $audit[] = ['source_path' => $path, 'section' => $section, 'point' => $kind, 'candidate_html' => $candidate,
            'basic_word_count' => m40Words($context) - m40Words($candidate), 'detail_word_count' => m40Words($candidate),
            'detail_sentence_count' => m40Sentences($candidate), 'decision' => 'visible_basic', 'reason' => $reason];
    };
    $summaryReasons = [
        'perfect-comparison' => [
            5 => ['For/since й неавтоматичний вибір часу — core period meaning.',
                'Звичайні stative meanings і scope іншого значення потрібні поруч з моделлю.',
                'Дві live-форми й триваючий стан — центральне порівняння з перекладом.',
                'Continuous не доводить наміру переїхати; це essential factual boundary.',
                'How long із known пояснює саме звичайний тривалий стан.'],
            6 => ['Часова рамка й конкретний yesterday — basic selection step.',
                'Result/state/activity — основне запитання вибору, не optional depth.',
                'Значення know/live визначає допустиму модель.',
                'Маркери не обирають форму автоматично; recently example є core caveat.',
                'Counted result та continuing state не можна приховати як доповнення.',
                'Інструкція й відкриті варіанти — коротка межа конкретного тренажера.'],
        ],
        'narrative-tenses' => [3 => ['Основна послідовність і її переклад — core example.',
            'Процес при повідомленні не встановлює припинення читання.',
            'Раніше виймання карти пояснює центральний Past Perfect example.',
            'Одночасність не доводить причинності; це basic scope.',
            'After і допустимість двох форм — core meaning comparison.',
            'Past Perfect потребує минулої точки, яка може бути в контексті.',
            'Зміна meaning між two valid forms є центральним зіставленням.',
            'Повернення до основної лінії — коротка narrative instruction.']],
        'b1-mixed-revision' => [1 => ['Perfect/narrative direction і markers — essential B1 overview.',
            'Майбутній процес/межа не стають виконаною роботою; core models.',
            'Modal passive/causative roles і короткий get note — visible basic.',
            'Reported question/command/pronoun context — основна модель.',
            'Defining information/although/comma/contrast — core forms і переклади.',
            'Wish/third conditional/might strength — essential review, не optional chapter.']],
    ];
    foreach ($lesson['existing_blocks'] as $block) {
        $index = $block['source_index']; $data = $block['replacement_body_json'];
        $context = m40LearnerValues($data, true); $section = $data['title'] ?? 'hero';
        $base = 'existing_blocks['.$index.'].replacement_body_json';
        if (isset($data['warning'])) {
            $append($base.'.warning', $data['warning'], $context, $section, 'native-warning',
                'Коротке застереження обмежує основне правило; до будь-якого кліку лишається basic.');
        }
        foreach ($data['rows'] ?? [] as $i => $row) {
            if (isset($row['note'])) { $append($base.'.rows['.$i.'].note', $row['note'], $context, $section, 'native-row-note',
                'Note пояснює роль саме цього bilingual comparison row; core table column, не hidden depth.'); }
        }
        foreach ($data['sections'] ?? [] as $i => $point) {
            if (isset($point['note'])) { $append($base.'.sections['.$i.'].note', $point['note'], $context, $section, 'native-usage-note',
                'Note зберігає центральну межу counted completion/recent activity цього прикладу.'); }
        }
        if ($block['preserve_type'] === 'summary-list') {
            foreach ($data['items'] as $i => $item) {
                $append($base.'.items['.$i.']', $item, $context, $section, 'native-summary-unit', $summaryReasons[$lesson['key']][$index][$i]);
            }
        }
        if ($lesson['key'] === 'narrative-tenses' && $block['preserve_type'] === 'forms-grid') {
            foreach ($data['items'] as $i => $item) {
                preg_match_all('/[^.!?]+[.!?](?:\s|$)/u', m40Plain($item['subtitle']), $sentences);
                $last = trim($sentences[0][count($sentences[0]) - 1]);
                $append($base.'.items['.$i.'].subtitle#last-sentence', $last, $context, $section, 'native-form-boundary',
                    'Did+base / was / past reference пояснюють core form поруч із прикладом.');
            }
        }
        if ($lesson['key'] === 'b1-mixed-revision' && $block['preserve_type'] === 'forms-grid') {
            $append($base.'.intro', $data['intro'], $context, $section, 'native-scope-and-notation',
                'Рівень/межа огляду та V3/V-ing notation — visible orientation, не окреме поглиблення.');
            $append($base.'.items[3].subtitle', $data['items'][3]['subtitle'], $context, $section, 'native-instruction-boundary',
                'Коротка межа інструкції та finite answer set потрібна для розуміння практики.');
        }
    }
    foreach (array_slice($parts, 0, 2) as $i => $part) {
        $dom = new DOMDocument; libxml_use_internal_errors(true);
        $dom->loadHTML('<meta charset="UTF-8">'.$part['html'], LIBXML_NONET); libxml_clear_errors();
        $paragraphs = $dom->getElementsByTagName('p'); $candidate = m40Inner($paragraphs->item($paragraphs->length - 1));
        $append('append_blocks[0].body_html#pre-section-'.($i + 1).'/final-paragraph', $candidate, $part['html'], $part['title'],
            'pre-practice-final-paragraph', $i === 0
                ? 'Аналіз фактів/часів пояснює саме попередній навчальний текст; core, не independent depth.'
                : 'Коротка інструкція контролю facts/chronology та вигаданого контексту лишається visible basic.');
    }
    return $audit;
}
