<?php

namespace Tests\Unit;

use App\Models\Question;
use App\Models\Tag;
use App\Services\AutoGeneratedTestService;
use App\Services\VirtualSavedTest;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AutoGeneratedTestServiceTest extends TestCase
{
    use RefreshDatabase;

    private AutoGeneratedTestService $service;

    protected function setUp(): void
    {
        parent::setUp();
        $this->service = new AutoGeneratedTestService();
    }

    /** @test */
    public function it_returns_empty_collection_when_no_tags_provided()
    {
        $tags = collect();
        $tests = $this->service->generateTests($tags);
        
        $this->assertTrue($tests->isEmpty());
    }

    /** @test */
    public function it_generates_virtual_tests_for_level_pairs_with_enough_questions()
    {
        // Create a tag
        $tag = Tag::factory()->create(['name' => 'test-tag']);
        
        // Create 20 questions with flag=2 for each level pair
        $levels = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];
        foreach ($levels as $level) {
            Question::factory()
                ->count(20)
                ->create([
                    'flag' => 2,
                    'level' => $level,
                ])
                ->each(function ($question) use ($tag) {
                    $question->tags()->attach($tag->id);
                });
        }

        $tests = $this->service->generateTests(collect([$tag]), 'Test Context');
        
        // Should generate 5 tests (one for each level pair)
        $this->assertCount(5, $tests);
        
        // Check first test is a VirtualSavedTest (not persisted)
        $firstTest = $tests->first();
        $this->assertInstanceOf(VirtualSavedTest::class, $firstTest);
        
        // Check test has correct attributes
        $this->assertNotNull($firstTest->uuid);
        $this->assertNotNull($firstTest->slug);
        $this->assertNotNull($firstTest->name);
        $this->assertIsArray($firstTest->filters);
        
        // Check filters
        $filters = $firstTest->filters;
        $this->assertTrue($filters['only_ai_v2']);
        $this->assertEquals(['test-tag'], $filters['tags']);
        $this->assertContains('A1', $filters['levels']);
        $this->assertContains('A2', $filters['levels']);
        $this->assertEquals(15, $filters['num_questions']);
        $this->assertTrue($filters['randomize_filtered']);
        $this->assertEquals('filters', $filters['__meta']['mode']);
    }

    /** @test */
    public function it_skips_level_pairs_without_enough_questions()
    {
        $tag = Tag::factory()->create(['name' => 'test-tag']);
        
        // Create only 10 questions for A1 and A2 (not enough for 15 questions test)
        Question::factory()
            ->count(10)
            ->create([
                'flag' => 2,
                'level' => 'A1',
            ])
            ->each(function ($question) use ($tag) {
                $question->tags()->attach($tag->id);
            });

        $tests = $this->service->generateTests(collect([$tag]));
        
        // Should not include A1-A2 test
        $this->assertEmpty($tests);
    }

    /** @test */
    public function it_filters_by_flag_2_only()
    {
        $tag = Tag::factory()->create(['name' => 'test-tag']);
        
        // Create questions with different flags
        Question::factory()
            ->count(10)
            ->create([
                'flag' => 0, // Not AI
                'level' => 'A1',
            ])
            ->each(function ($question) use ($tag) {
                $question->tags()->attach($tag->id);
            });

        Question::factory()
            ->count(20)
            ->create([
                'flag' => 2, // AI v2
                'level' => 'A1',
            ])
            ->each(function ($question) use ($tag) {
                $question->tags()->attach($tag->id);
            });

        Question::factory()
            ->count(20)
            ->create([
                'flag' => 2,
                'level' => 'A2',
            ])
            ->each(function ($question) use ($tag) {
                $question->tags()->attach($tag->id);
            });

        $tests = $this->service->generateTests(collect([$tag]));
        
        // Should generate test for A1-A2 with only flag=2 questions
        $this->assertNotEmpty($tests);
        
        // Verify the generated test only uses flag=2 questions
        $firstTest = $tests->first();
        $this->assertInstanceOf(VirtualSavedTest::class, $firstTest);
        
        // Count available questions matching the test filters
        $filters = $firstTest->filters;
        $questionCount = Question::query()
            ->where('flag', 2)
            ->whereIn('level', $filters['levels'])
            ->whereHas('tags', fn($q) => $q->whereIn('name', $filters['tags']))
            ->count();
        
        // Should be 40 (20 A1 + 20 A2), not 50 (excluding flag=0)
        $this->assertEquals(40, $questionCount);
    }

    /** @test */
    public function it_does_not_persist_tests_to_database()
    {
        $tag = Tag::factory()->create(['name' => 'test-tag']);
        
        // Create enough questions
        $levels = ['A1', 'A2'];
        foreach ($levels as $level) {
            Question::factory()
                ->count(20)
                ->create([
                    'flag' => 2,
                    'level' => $level,
                ])
                ->each(function ($question) use ($tag) {
                    $question->tags()->attach($tag->id);
                });
        }

        // Generate tests first time
        $tests1 = $this->service->generateTests(collect([$tag]), 'Same Context');
        $this->assertNotEmpty($tests1);
        
        // Verify tests are VirtualSavedTest instances
        $firstTest = $tests1->first();
        $this->assertInstanceOf(VirtualSavedTest::class, $firstTest);
        $this->assertFalse($firstTest->exists);
        
        // Generate tests second time
        $tests2 = $this->service->generateTests(collect([$tag]), 'Same Context');
        $this->assertNotEmpty($tests2);
        
        // Both should be virtual tests (not persisted)
        $this->assertInstanceOf(VirtualSavedTest::class, $tests2->first());
        
        // No tests should be saved to the database
        $this->assertEquals(0, \App\Models\SavedGrammarTest::count());
    }
}
